### ISSUE TITLE
Timerbar Customization

### ISSUE THREAD

**Issue by dethmoose** [quisquous/cactbot#101]
I've been trying to customize the style of the raidboss timerbars, but not all changes apply to them? 
I'm not the best with code, but I can manage css a bit. I assume the resize-helper-bars aren't the same style as the ones during testing? Is there a way to apply whatever changes you've made to the resize-helpers to the other bars?

**Comment by quisquous** [comment]
What in particular are you trying to do?

**Comment by meciuPL** [comment]
Like for example change the colours of the bars and the font. I've been having a similar problem.

**Comment by rsigim** [comment]
I guess Im doing wrong too, like [changing the raidboss.css](https://i.imgur.com/QqoMPb0.jpg) some modifs come only in helper. And like dethmoose I dont have much experience with coding, so if I create a new css its will overwrite what suppose to be the default one?

**Comment by quisquous** [comment]
The timeline is a bit hard to change because it's in nested web components.  Sorry about that.

/deep/ is deprecated, but this will give you the border radius you're looking for, I think?

```
/* this works but not really because the boxes don't change size */
#timeline /deep/ #root {
  font-size: 16px;
}

#timeline /deep/ #fg {
  border-radius: 5px;
}

#timeline /deep/ #bg {
  border-radius: 5px;
}

/* these are in the raidboss css file */
.timeline-bar-color {
  background-color: papayawhip;
}
.timeline-bar-color.soon {
  background-color: red;
}
```

This should get you a little bit of the way there.  I think I need to make some changes to the timeline itself to allow more extensive changes.

Sorry for the headaches.  This really isn't clear at all how to do.  I think the raidboss pop up text is easy to modify, but the timeline is not at the moment.

**Comment by rsigim** [comment]
Oh, I see :[
You mean its hard to get customs from user/ directory, or the bars himself?
Because I did direct in the timerbar.js and got same result, yet I thought it was doing something wrong, because looks like the bars is a [stretching image](https://i.imgur.com/GiPmzf9.jpg), comes from square and become rounded.

Yet, "works". thanks for your effort on that.

**Comment by rsigim** [comment]
Oh, I see :[
You mean its hard to get customs from user/ directory, or the bars himself?
Because before I did direct in the timerbar.js and got same result, yet I thought it was doing something wrong, because looks like the bars is a stretching image, comes from square and become rounded.

Yet, "works". thanks for your effort on that.

**Comment by quisquous** [comment]
I mean that it's a little bit tricky to style the bars themselves.  They're embedded inside two custom elements.  They also animate quickly, so it's hard to use devtools to investigate inside of them.  Either that or you have to go read all the code setting them up.

It looks like the stretching is because the bars are using transform and not width to animate.  I fixed that, and now border-radius should work properly.  Sorry for the hassle.

I added more reasonable class names in 
cc7c676, so you can style #timeline, .timerbar-root, .timerbar-fg, .timerbar-bg, .timerbar-lefttext, .timerbar-centertext, .timerbar-righttext, and .text classes inside #timeline /deep/.

It looks like offhand that the MaxNumberOfTimerBars option combined with the height of #timer-container determine how big the bars are.  So, if you want to make the bars taller to have a bigger font size, then you can adjust that.

Was there anything else you were trying to do?

**Comment by quisquous** [comment]
I'm going to close this issue for now.  Let me know if there's more customization you want here or if any of this is too cumbersome.
