### ISSUE TITLE
NM's names sometime stay highlited even after end of FATE

### ISSUE THREAD

**Issue by ghost** [quisquous/cactbot#1036]
## Description

Sometime the names of NMs on the map stay highlighted as just popped even if they were killed,
This time it happened with a distant FATE I didn't complete myself but I saw it happening in the past with FATEs where I participated as well

## Additional information

![image](https://user-images.githubusercontent.com/60162875/74193463-b1f96a00-4c57-11ea-89b3-6c89a894f8c7.png)

I'll add relevant logs here or in the comments as soon as I manage to isolate the problem in one run with ACT. I just wanted to open the issue for now to see if other people have the same problem

**Comment by Akurosia** [comment]
i think this is a known bug as they changed fate behaviour in eureka.
I think the PR https://github.com/quisquous/cactbot/pull/903 was created to fix this

**Comment by KattTails** [comment]
This isn't necessarily due to the changes to Eureka's NMs as they didn't modify Anemos, Pagos or Pyros in any way. However, when #903 is finished this shouldn't happen again due to changes in how FATEs are handled.

As for what's causing this now, it's possible the NM combatant removed messages are being missed, which would cause the fate not to despawn on cactbot's map.

**Comment by leewdch** [comment]
I don't really know how added/removed combatant messages are handled but I noticed they are somewhat abused in certain mechanic, for example when Jack spawns in Pyros a series of added combatant messages are spammed via TTS because certain actions generate multiple added combatant messages in the logs meaning that maybe multiple instances of the same entity are generated for some actions (?) but I'm just guessing here

**Comment by quisquous** [comment]
#903 has been merged, so this should be fixed.
