### ISSUE TITLE
BrowserConsole: Not allowed to load local resource

### ISSUE THREAD

**Issue by Areslunatic** [quisquous/cactbot#104]
As the title says, i have this weird massage in ACT since a few days.
i've changed nothing and now the "bsides_HORIZOVERLAY_pointer" wont work anymore.
It tells me there is NO PAGE FOUND. 

Thats the full errorcode:

17.04.2018 14:05:17: Info: DBM: BrowserConsole: Not allowed to load local resource: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/user/raidboss.js (Source: https://quisquous.github.io/cactbot/ui/raidboss/raidboss.html, Line: 0)

(DBM is the name for my cactbot)

**Comment by quisquous** [comment]
Are you on the latest version of cactbot?

If you're trying to do user overrides, you need to set a user config folder in cactbot 0.6.5 to a local folder, e.g. **file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/user** if you're using github pages.

**Comment by mattddonovan** [comment]
This might be useful. I have a feeling that it might be related to Chrome's security settings that by default prevent access to locally hosted files.  There are several workarounds available on the web, but this one is worth a shot:
http://www.chrome-allow-file-access-from-file.com/windows.html

Of course it depends on the users locally installed version of Chrome. I'm not entirely sure how chrome is launched or instantiated via ACT and this Overlay Plugin, but adding `--allow-file-access-from-files` as a flag to launching the browser like this `PATH_TO_CHROME_INSTALLATION\chrome.exe --allow-file-access-from-files` might work.  

I believe the issue is with the code attempting to directly access a local file with an explicit path. Other's have suggested using a local web server to reference the assets as well, using a plugin like: [Web Server for Chrome ](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb?hl=en).

Hope this helps. It might require some digging and trial and error.

**Comment by quisquous** [comment]
Coming back to this, are you still having this issue? Are you using a pointer file to redirect to some remote file?  If so, can you paste the contents of that pointer file?

**Comment by quisquous** [comment]
I'm going to close this due to lack of response.  Let me know if you still want me to take a look at this.
