### ISSUE TITLE
Questions / suggestions to Responses

### ISSUE THREAD

**Issue by Akurosia** [quisquous/cactbot#1044]
Based of the start of #1034 and #1035 there are open question in regards to responses:
All functions are abbreviated from e.g. Responses.silence(), to .silence(),

1) How do we deal with all types of aoe? (e.g. small aos, big aoe, line aoe, donut aoe)
2) We have .silence() but shouldn't this be changed to .interupt() due to game changes? if not we would need stun/interupt
3) Whats the difference between .killAdds() and .killExtraAdd()?
4) How do we deal with add anouncments when there are specific names e.g. Bennu add in t12 or dreadnaught add in t8? (maybe use .killExtraAdd("Name") for specific and .killAdds() just as a generall announcement)
5) How do we deal with add/skill specific silences? (t8 = blue golem, t7(and others) = ram's/dragon's voice)
6) Whats the difference between .getUnder() and .getIn()
7) Whats the difference between .awayFromFront() and .outOfFront()
7) Whats the difference between .outOfMelee() and .getOut()

Following are some Response i think would be good:

.sleep()
.stackMiddle() or .stackTogether() (maybe with a parameter e.g. .stack("middle"))
.spreadThanStack()
.stackThanSpread()
.charge() or .chargeAt() or .chargeOn()
.moveClockwise()
.moveCounterClockwise()
.goAwayFrom()
.breakChains()
.moveChainsTogether()
.earthshacker()
.knockbackFrom()
.hideBehind("target")

**Comment by quisquous** [comment]
So, my overall thoughts here are that not everything should be in Responses.  Things that are common and get used at least 3 if not more times across encounters should be there.  Things that are rare should probably just stick with the 

I think part of my thinking is that maybe in the future we can give users the option to change the text for these (although there's some thought that would have to happen with respect to functions), and so the more there are, the more confusing it is to differentiate them?  Everybody will probably have these same questions that you do.

Another feeling I have here is that any parameters that are sent to Response functions should already be translated.  I don't want anything like `stack("middle")`, because having to translate middle everywhere defeats the purpose of having a common translation function, if that makes sense.  So, parameters to Response functions should be things that come from the game (player names, monster names, skill names, effect names) ideally.  And things like `stack("middle")` should just be baked into the a response called `stackMiddle()`.

All of these are just me being opinionated.  If other folks (especially folks who write translations) want to chime in on this, feel free.  @Jaehyuk-Lee @mooondark @Bing-su

> 1. How do we deal with all types of aoe? (e.g. small aos, big aoe, line aoe, donut aoe)

I don't see any "small aoe" anywhere.  I think "big aoe" could be a separate item if you wanted it to be, but I think it's pretty uncommon.  Donut could be its own item, although usually when there's a donut it says "get in".  Do you have examples of donut callouts?

"line aoe" sounds like something on the floor, and I'm generally opposed to triggers that just say "avoid things on the floor you can see", so maybe just remove those triggers.

> 2. We have .silence() but shouldn't this be changed to .interupt() due to game changes? if not we would need stun/interupt

I guess technically it's now "interrupt" and not silence, that's fair.  Maybe it'd be good to change everything to that.

I do think there are things that need to be stunned and can't be interrupted, and those should continue to say stun.

> 3. Whats the difference between .killAdds() and .killExtraAdd()?

I think killAdds is like "here are adds that happen normally, make sure they die" and "killExtraAdd" is like "whoops somebody messed up on Titania and there's an unexpected add here?"

> 4. How do we deal with add anouncments when there are specific names e.g. Bennu add in t12 or dreadnaught add in t8? (maybe use .killExtraAdd("Name") for specific and .killAdds() just as a generall announcement)

Yeah, I think they should take a name, and ideally that name should come from the line that is matched so that it doesn't need to be translated.

> 5. How do we deal with add/skill specific silences? (t8 = blue golem, t7(and others) = ram's/dragon's voice)

We might need silenceMob(mob) and silenceSkill(skill)? I'm not sure if the grammar ends up being different on those.

> 6. Whats the difference between .getUnder() and .getIn()

Under is like "be in the hitbox" and in is more like "get close but maybe even melee range is fine".

> 7. Whats the difference between .awayFromFront() and .outOfFront()

I think these are the same.

> 8. Whats the difference between .outOfMelee() and .getOut()

Maybe a degree of difference? "Out of melee" is "get out a little bit" "get out" is like "get out a lot"

> .sleep()

Sounds good, maybe with a target?

> .stackMiddle() or .stackTogether() (maybe with a parameter e.g. .stack("middle"))

I think "stack together" is the same as "stack".  stackMiddle could be a separate response.

> .spreadThanStack()
> .stackThanSpread()
> .charge() or .chargeAt() or .chargeOn()

These seem reasonable.

> .moveClockwise()
> .moveCounterClockwise()

Does this happen anywhere but Innocence?

> .goAwayFrom()

Where does this happen?

> .breakChains()
> .moveChainsTogether()
> .earthshacker()

These seem reasonable.

> .knockbackFrom()

Does this happen other than Dun Scaith? Maybe o9s?

> .hideBehind("target")

I'd say no on this one, as "target" will almost always need to be translated manually, so probably shouldn't live in responses.

I would also suggest `mechanicOnYou("mechanic")`

**Comment by Akurosia** [comment]
I agree with you that not everything should be a Response.

Why do parameters need to be translated? Couldn't the parameter just a keyword which is than handeled in the response function itself (it still would return the correct language in the end)?

1) The "small AoE" should just be the normal AoE (sorry for the confusion)
Donut AoE examples:
- Anemos (Poly)
- E1S (delta attack, middle of the fight with ice donut)
- Byakkos hugh electric donut aoe
But i also think you are right with the donut aoe would be equals to the .getIn()

For line Aoe i will make sure to remove it, when i see it :)

2) Ok so i will rename .silence() to .interupt() and change it wherever i see and create a .stun()

3) I would like to make a comment in the response file which explains the add behaviour as it should be than clear enought (same with similar elements)

4) For the add specific thing i think this is something someone else have to do as i am not really sure i can do it ^^'

5) See answer 4 (i could create the basic trigger for now which later gets adjusted)

6) See answer 3

7) I would remove .outOfFront() than so we have no duplications (and less questions in the future)

8) See answer 3


Which of the charges do you prefere? (.charge() or .chargeAt() or .chargeOn())

Ok i am pretty sure i saw some clockwise trigger when i did ARR and HW (or start SB) but cannot find them... so i am fine with not adding them.

Examples for the knoackback:
- Sephiroth blue puddles
- o5s (knockback ghost)
- e3s/shinryu (knockbacks from the water)
- o8 (the knockback lightning bolt)


I will also add than the responses for 
.bigAoe(), .sleep(), .spreadThanStack(), .stackThanSpread(), stackMiddle(), .breakChains(), .moveChainsTogether(), .earthshacker()
The .sleep() would be need to be adjusted later with the targets name (same as for silence)

**Comment by Akurosia** [comment]
FYI: i found the origin of clockwise/counter clockwise trigger idea: 'Orbonne Cid Holy Sword Three 1' and 'Orbonne Cid Holy Sword Three 2'

**Comment by quisquous** [comment]
Ok, maybe if it's in a couple of places it makes sense to have that, then.

**Comment by quisquous** [comment]
Is there anything else to be done in this issue? Or do you feel like this is solved?

There's some repeated swipe/swing in https://docs.qq.com/sheet/DSFRGa1V1d2pOZk1H?tab=qwmxvl&c=E42A0RF0, but probably those should be changed to out of front / get away.  I don't see anything else in there that's a really good candidate for responses.

**Comment by quisquous** [comment]
Ok, I think this is done.  Any followups can be done in pull requests at this point.  Thanks for the discussion.  :)
