### ISSUE TITLE
Encounter resets even without party wipe

### ISSUE THREAD

**Issue by cursedwithlazy** [quisquous/cactbot#105]
My encounter duration automatically resets if I die and rez, even without the party wiping. Is there a way to disable this?

**Comment by quisquous** [comment]
cactbot attempts to detect wipes by detecting when you go 0->some hp without rez sickness happening.

By encounter duration, I assume you mean DPS meter? I assume this isn't because of some really short encounter cutoff time and this works just fine if you use miniparse instead of cactbot as the overlay for your dps meter?

Are you using a different language than English in game? It's looking for log lines like "gains the effect of Weakness from", so if it can't find that then it won't think it's a wipe.

Finally, what zone is this happening in? I know this is a problem in original Steps of Faith because you can die and return there mid-fight, but that's an exception.

**Comment by cursedwithlazy** [comment]
Yes, the dps meter. I play in English. It happens in every encounter I'm in where I am happen to die and rez. Sigma savage, Sigma normal, Byakko EX, etc. If I stay dead on the floor, the encounter will continue from the initial pull. It only resets as soon as I rez.

**Comment by quisquous** [comment]
Hmmmmm that's very curious.  Could you try using this debug build of cactbot and when you get rezzed, let me know what it says in the ACT console log?  There should be a bunch of WipeTest output.  If you have the ACT logs / network log file from that, that'd be helpful too.

**Comment by quisquous** [comment]
[wipe-debugging.zip](https://github.com/quisquous/cactbot/files/1934064/wipe-debugging.zip)

**Comment by cursedwithlazy** [comment]
I'm not sure what's going on now. I tried using the debug build you linked, and the encounters I tried (O8 nm and O5S) didn't reset the duration if I died and rezzed. I switched back to the normal cactbot build and the encounter hasn't been resetting anymore if I die and rez.

Seems like it's working properly for now. If I see it happen again I'll try to have the log file ready.

**Comment by cursedwithlazy** [comment]
There have been times where I've loaded ACT but the cactbot timeline didn't load (though my other plugins loaded fine). I'd have to restart ACT to get it to show up. I can't remember if it happened with oopsyraidsy too or if it was just the timeline.

**Comment by quisquous** [comment]
I'm going to close this as you mentioned that you felt like it was working properly for now.  There's a separate issue with wipes (#124) open right now but this seems different than that.
