### ISSUE TITLE
oopsy: reporting many warnings that it shouldn't

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#1060]
user report from discord that copied factory in particular reports a lot of warnings for abilities.  It's not clear which abilities this is coming from, so some debugging might be needed.

![image](https://user-images.githubusercontent.com/462317/75101118-80a06880-558c-11ea-8687-3702fcf6f34b.png)

**Comment by mooondark** [comment]
Hello, i'm the one who reported this (sorry my discord name is different from here).
In fact, **Oopsy will now always display any skill/abilitiy** that is cast by a nearby player. Even when not in a party (in town or open world).
(btw the screenshot above in from Dun Scaith, not copied factory).

**Comment by slashy** [comment]
I got this issue too.

At the moment it looks like it's reporting all sorts of crafting skills as well as usage of Sprint. 

I have my client in german.

![grafik](https://user-images.githubusercontent.com/162015/75273889-05e08300-5802-11ea-8eea-318422a31b9a.png)

**Comment by slashy** [comment]
I debugged a bit and it seems the problem is with those 2 triggers:

id: "Ala Mhigo Art Of The Swell"
id: "UWU Windburn"

Windburn is missing in both fr.json and de.json for kEffects, which makes the gainsEffectRegex being undefined. 

Ala Mhigo ones defines the gainsEffectRegex as gLang.kEffect.DamageDown which can't be found anywhere else. Thus this one also triggers, but it SHOULD trigger in every language.
