### ISSUE TITLE
util/make_timeline.py -lf isn't finding all fights

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#1061]
`-lf` finds no e8s fights in this log file:
[Network_2052_20200222.zip](https://github.com/quisquous/cactbot/files/4240429/Network_2052_20200222.zip)

`-lf` finds only e8s and not e7s in this log file:
[Network_2051_20200222.zip](https://github.com/quisquous/cactbot/files/4240430/Network_2051_20200222.zip)

(CC @JLGarber)

**Comment by JLGarber** [comment]
It looks like what's happening is that you're starting ACT after entering the instance. [This runs up against the "are you in an instance?" check](https://github.com/quisquous/cactbot/blob/170bbd9f24941858d5b601a7148d7fdc47c40d2f/util/encounter_tools.py#L95). I would like to use the `01` line for instance names instead, but that would catch every zone change.

One thing that would be relatively simple is to add a chat command that the script would pick up on. This would require logging chat, however, and isn't really a good solution.

**Comment by quisquous** [comment]
I feel like we've had this conversation before, but I can't remember what's wrong with using `01` as well and catching every zone change?

**Comment by JLGarber** [comment]
At this time I'm not aware of a more graceful way to cull open-world encounters. Locking things to an instance avoids that clutter. (We are able to avoid dungeon trash clutter because of zone seals, but I'm not sure how to deal with open-world combat.) If we don't do this culling somehow, there's a strong chance you could end up with 100+ encounters in the listing.

It's possible that we could do a deny/allow list, but I feel like that's too much manual work. Maybe the best solution is to allow the user to select whether or not they use a culling version of the script? I feel like we could pass Yet Another Flag™ that would choose between allowing all encounters and showing only encounters within the instance as it is now.

**Comment by quisquous** [comment]
Ok yes, thanks for the reminder of what the issue was.

Thinking about this a little bit more, I think there are a couple of `21` log lines that we could use to say that something is in a battle instance vs an open-world encounter.  Maybe https://gist.github.com/quisquous/250001cbce232a48e6a9ce772a56675a#file-actor-control-line-investigation-L6

**Comment by JLGarber** [comment]
If I'm understanding this correctly, the `21` line indicates a zone with an attached timer? If so, that would probably be "simple". Just look for a 21 line with an attached `400000XX` value and that will indicate a valid instance. That might require splitting the "what is the zone name" logic from "is this a valid instance" check, but should work.

This wouldn't be guaranteed to catch the entirety of the first encounter after opening ACT, since the logs you attached seem to send that line after engaging. However, that's still far better than the current situation. 

I think we should keep the current "[INSTANCE] has begun" check as an automatically-correct "is this an instance" check, since when it fires it's guaranteed to be right. I'll poke at this a little and see how we could best integrate the `21` lines alongside that.

**Comment by quisquous** [comment]
Yes agreed! I think we could handle both.  I think seeing any of the wipe, recommence, initial lockout `21` messages are all things that only happen in instances.  And we can also use "has begun" as a definitive clue.  If you have time to take a look, it would be much appreciated, thanks!

**Comment by JLGarber** [comment]
It seems the "has begun" lines are no longer completely reliable. There's a random line feed (or what I assume is one, but I'm not knowledgeable about such things, the terminal shows it as `\xlf`,) and the colons in zone names appear to have been replaced with pipes:

`00|2020-02-22T14:10:31.0000000-05:00|0839|Eden's Verse| Refulgence (Savage) has begun.|e54920126daf352d31cc8c3633c3b418`

This isn't insurmountable, but it's immensely frustrating. Eliding the superfluous line feed is no big deal, but the use of the pipe separator means more extra work, potentially a lot. I'm not sure whether this is a Square thing or an accidental addition from Ravahn. (It's worth noting that the colon is still used as a separator in the `01` zone change lines.)

**Comment by JLGarber** [comment]
Hmm. It looks like that may be a false alarm. I've looked through more recent logs and that phenomenon isn't occurring, so that's probably just an artifact from the beta release of the plugin.

I think I'm nearly finished fixing this issue, but I need to test a little more. There should be a pull request tonight or tomorrow.
