### ISSUE TITLE
E6 (Normal & Savage) superstorm

### ISSUE THREAD

**Issue by mooondark** [quisquous/cactbot#1155]
Hello,
There's something weird with superstorm.
In E6N, I got the info once (only on the first set of nails) then nothing (even for Raktapaksa).
In E6S, nothing is displayed. The only id for now is 4BF7, but in my log I have :
- for Garuda : 4BD[7F], 4BF[EF], 4C00
- for Raktapaksa : 4BE[346]

Am I missing something ?

**Comment by JLGarber** [comment]
Does Raktapaksa actually use Superstorm again? [Here's a random 10-minute log from the first page of Normal](https://www.fflogs.com/reports/TN39HvyjRdzAVWqk#fight=1&type=damage-done&hostility=1&ability=19415), and I see only the one cast used.

**Comment by JLGarber** [comment]
Welp. Ferostorm definitely does not work currently. I'm bad at spelling:

`Regexes.startsUsing({ source: ['Garuda', 'Raktapaska']`

`Raktapaska`

I'll put together a request for that right away. E6s doesn't even *have* a Ferostorm callout, but I'll leave that out of this since that's not technically broken. (I think also Quisquous was hoping to have the triggers call the direction of the Ferostorm as well as simply alert the user, so that may have played into it.)

**Comment by mooondark** [comment]
Sorry,
I meant Ferostorm not Superstorm ... Thanks @JLGarber for the spelling fix.
@Akurosia yeah you're right, ids of E6n&E6s where mixed in my log file because i've run it the same day (without looking at the time in the log file ...)
