### ISSUE TITLE
Issues with triggers in last encounter of The Vault

### ISSUE THREAD

**Issue by valarnin** [quisquous/cactbot#1167]
## Description

The last encounter of `The Vault` against `Ser Charibert` has numerous issues with the fight-specific triggers.

## Additional information

The `Evade marching knights` trigger fired as soon as the last trash pack before the boss was killed, before we even left that tower room. At least one other fight-specific trigger fired at the wrong time though I didn't manage to catch what the text was.

The generic AoE and tankbuster triggers seemed to be fine.

The actual fight timeline also seemed to be fine.

**Comment by JLGarber** [comment]
That's one of my older submissions, yes. It shouldn't be too hard to fix the knight evasion trigger, just make it conditioned on seeing Charibert use an ability, probably Holy Chains. I'll get that taken care of tonight.

The only other thing I can think of that would have failed is if your party pushed him to the intermission within 5 seconds of the next use of Altar Candle. Because it's an instant-cast, the only way to warn against it is with a timeline trigger,
