### ISSUE TITLE
E5S-E7S-E8S triggers

### ISSUE THREAD

**Issue by lollirenzo** [quisquous/cactbot#1183]
I noticed that during E5S cactbot doesn't call anymore twisters or donuts mechanics, clouds and  when to pick up an orb. Every other savage floor works well

EDIT: E7S triggers to be revised too. Some triggers work, others don't, like colours triggers
EDIT #2: E8S triggers to be revised too. Few triggers work, others don't. First mirror mechanic doesn't work, chain or orb debuff doesn't work and a lot more

**Comment by Una-P** [comment]
I think plugin needs an update corresponding to 5.21, so it's no wonder it doesn't work.

**Comment by ngld** [comment]
Make sure you're on parser version 2.0.5.7, 2.0.5.6 broke a bunch of Cactbot triggers.

**Comment by lollirenzo** [comment]
Everything up to date here, few of my friends noticed the same things with cactbot

**Comment by beckyeeky** [comment]
Did you switch to winpcap parse?
Some people switched to memory and forgot to switch back.

**Comment by illhatjr28** [comment]
So is there any news on a fix for this? I currently use Network for my parse mode and all the other previous expansion fights and timelines work except for the new eden verse tier. Im currently on the 2.0.5.9 version of the FFXIV_ACT_Plugin

 Cactbot 0.16.10.0 version.

Again most the fights are working fine except the new normal and savage edenverse fights, timeline, text, and TTS are all not working.

**Comment by quisquous** [comment]
Sorry for the lack of response.  I had assumed this was related to the 5.21 update.  I am not sure what's going on here.

- What language are you playing in?
- What is your raidboss url? If you look in the `data/05-shb/raid/e8s.js` file adjacent to that url, is that file filled in?
- Were there any errors when you updated, like #1149?
- Are there any errors in the overlayplugin log when you do these fights?

**Comment by illhatjr28** [comment]
Playing in English,

url is: file:///E:/cactbot-master/cactbot-0.15.1/cactbot/ui/raidboss/raidboss.html

So maybe since its not 0.16.x that must be causing the issue?

Also not sure what you mean by filled in but when i select the e8s.js file I do get some text appearing in the text box section of the where the timeline normally goes.

I dont remember any errors to my knowledge, last error i had was simply from the update and me not re clicking the check box after installing the new update to ACT.

I will have to double check when raiding tonight if there are any error codes when doing the fights. From memory I will say no but I will have to double check.

**Comment by quisquous** [comment]
That 0.15.1 path is just because of the way that ACT's Get Plugins unzips folders.  Aditu didn't want to change how ACT unzipped things and I didn't want to change the folder structure I was using.  It's just cosmetic and should not impact anyhing.

By "filled in", I meant open up that file in notepad and look at what's in it.  It should look similar to https://github.com/quisquous/cactbot/blob/master/ui/raidboss/data/05-shb/raid/e8s.js which is the latest.

**Comment by quisquous** [comment]
Hi, have you gotten this sorted? Is this still happening?

**Comment by illhatjr28** [comment]
Nope it's working. Thanks!

Sent from Yahoo Mail on Android 
 
  On Sun, Apr 12, 2020 at 1:53 PM, Adrienne Walker<notifications@github.com> wrote:   


Hi, have you gotten this sorted? Is this still happening?
