### ISSUE TITLE
WipeDetector detecting personal deaths as wipes

### ISSUE THREAD

**Issue by HailZaros** [quisquous/cactbot#124]
Starting with patch 4.3, using CactbotOverlay with any variant of DPS meters causes the meters to reset after a personal death.
Prior to this, it would have kept tracking without issue.

Tested on both English and JP game clients, with cactbot 0.7.0

**Comment by quisquous** [comment]
Thanks for the report.  I'm out of town this weekend, but I'll try to take a look as soon as I can.

(Insert joke here about have you tried just not dying? :P)

**Comment by HailZaros** [comment]
Just to note that this seems to be working (mostly) OK with the new FFXIV ACT Plugin update, but it still happens every so often.

**Comment by quisquous** [comment]
Thanks. This seems likely to be due to the missing "gains effect" changes that ravahn made in the last ffxiv act plugin release.  The wipe detector uses weakness / brink of death / lb3 and some hacky timers to determine when something is a raise vs a wipe.  So, if those aren't there, it'll consider things a wipe.

I did a little bit of work before 4.3 to track down some additional wipe detection method which I think will be much more robust but haven't had a chance to implement and test it yet.  Hopefully in the next week or two.  I'm going to close this issue now as I think we're now back to the same state before 4.2, and I'll try to improve this in the future.
