### ISSUE TITLE
language filter needed in "oopsyraidsy" and "raidboss" trigger

### ISSUE THREAD

**Issue by DieMoe233** [quisquous/cactbot#1257]
Different servers have different dealing with mechanism, so it should make "opps" and "raidboss" trigger not fired in several conditions to avoiding confusing.
For example, in Hades(EX), players would not dodge"Bad Faith" in CN servers, but "oopsyraidsy" trigger will be fired and give warning of "failure to dealing with mechanism", it confused some CN players. Similar conditions also appear in E4S.
Therefore, we need a language filter in "oopsyraidsy" and "raidboss" trigger to make specific triggers not be fired in specific language.

**Comment by quisquous** [comment]
What do people do differently in E4S? Stacking in Bad Faith is what folks do on my server as well.

My hope for oopsy is that it points out when you're hit by stuff that is avoidable.  If there's a mechanic that everybody just stands in, then maybe oopsy should just not call that out. (Or if we wanted to be more complicated, if ~4 or more people got hit, assume it's intentional and not mention it.)

**Comment by JLGarber** [comment]
It might be better to add a GUI Oopsy configuration for this? I realize that's always a lot of work, but lowering the barrier for players to disable this for themselves could be the best way to go, rather than trying to determine intentionality.

(Humorously speaking, we could exempt BLM from Oopsy altogether, unless the avoidable damage inflicts damage down or kills/wipes instantly.)

**Comment by quisquous** [comment]
I think in this case, like triggers, I'd want an option to be off by default since it being on causes confusion like this bug.  In that case, it seems likely that nobody would ever go turn this on.  That makes me lean against having an option.

If determining intentionality seems a bit awkward (and I agree with that), maybe it'd be better to just ignore Bad Faith entirely.  Or, throw a warning if anybody got hit by more than two?

(Re: BLM.  Whenever a BLM gets hit, it will just say "healers adjust" in oopsy and not blame the BLM.  :P)

**Comment by JLGarber** [comment]
Oh, I meant more generally a configuration GUI of the same sort Raidboss has. It would get around the whole "should we special-case this?" situation. If players can easily turn off Bad Faith in much the same way they would turn off any Raidboss trigger, I think that would avoid the intentionality issue as well. We already name the Oopsy triggers uniquely to enable this sort of per-mechanic toggling, so I feel like having a wall of checkboxes inside dropdowns could kind of make sense? 

BLM could have its own checkbox for whether or not they get included in mechanics. ^_^

**Comment by quisquous** [comment]
Ah, I see.  A general configuration might be nice.  There's no reason we couldn't do that too.  Unlike triggers though, I wonder how much people want to configure particular abilities off.

I don't think this issue counts as "wanting to configure something off", because it will still cause confusion and people will think something is wrong vs it being something they don't want.  I think this is what most people do, and so in some senses it's not a mistake even though it's avoidable.

**Comment by quisquous** [comment]
The linked patch above handles the Bad Faith issue.  If there are other mechanics that are being warned about that everybody commonly gets hit by, please let me know.

I'd like to avoid "localized strats" for oopsy unless it becomes absolutely necessary.
