### ISSUE TITLE
UCoB Doom order not being parsed

### ISSUE THREAD

**Issue by xDemonessx** [quisquous/cactbot#126]
This may be the same issue as #123 where the packet structure is reading the log differently (unfortunately I can't tell you as I had log saves disabled) however the triggers for Doom were not registering (it usually calls for who to cleanse and in which order).

FYI

**Comment by quisquous** [comment]
I think this is https://github.com/ravahn/FFXIV_ACT_Plugin/issues/167.  Because it uses the debuff time remaining to calculate which doom you have (and I'm guessing that time is 9999) it doesn't know what to do.  If you do this again saving logs, it'd be nice to confirm that's the case.

Sorry about the issues.  Hopefully ravahn will be able to get these things sorted.

**Comment by xDemonessx** [comment]
that makes total sense. I'll leave it open for now and let you know if it resolves or not. 

Thanks!

**Comment by Hoshiyuu** [comment]
mostly the 1A entry for gains the effect of Doom from is gone completely, but suffering from doom text should still be there @quisquous , same goes for o7s

**Comment by xDemonessx** [comment]
Just to confirm from last nights run, this is indeed an issue with the ACT Plugin itself:

![capture](https://user-images.githubusercontent.com/3487603/40623041-6db54c7a-626a-11e8-9f7c-b767c7a448ec.PNG)

**Comment by theBladeee** [comment]
Chiming in to confirm that this is still the case. I have the latest update.

**Comment by xDemonessx** [comment]
Assuming fixed with the new release:
Will reopen on Saturday when i go back in if there is issue.
https://github.com/ravahn/FFXIV_ACT_Plugin/releases/tag/v1.7.0.11
