### ISSUE TITLE
Add repository of common translations

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#1307]
Mentioned in several discussions at this point, and so collecting into a single issue here.

`responses.js` has done a good job of eliminating large translations, but it got a little bit complicated to handle a lot of things like tankbusters.  Each property on `Responses` is a function that takes a severity and returns an object for a response field on a trigger, e.g. `{ alertText: { en: 'Buster on YOU', de: etc etc } }`.  This is complicated to use in any real way.

I think we need some separate global object that folks can get translations from? It could also live in `responses.js` because it's probably going to be used for responses, but it should be a separate object from` Responses` itself.  Putting it in the `responses.js` file also means it'd be straightforward to have all of the things in `Responses` use these new translations too, which sounds nice to avoid even more duplication.

Opinions welcome for what we should call this new thing? `Translations` feels long.  Names are hard.

**Comment by JLGarber** [comment]
That's exactly the solution I was thinking of, glad to see it makes sense to others.

I don't think there's a single word that covers this situation, since we don't want to collide on `Popup` or `TriggerText`. `TextDump` is only eight characters, I suppose. Maybe `CommonText`? It's ten characters but is explicitly obvious as to what it does.

**Comment by quisquous** [comment]
`LocaleText`? Maybe `Translations` is fine too?

**Comment by JLGarber** [comment]
I like `LocaleText`, now that you mention it. That may be the optimum combination of brevity and clarity.
Thinking about it more, reducing horizontal width may not be as important as it could be elsewhere. In theory, the end of any given line of code where one of these text replacements appears will *probably* not be past column 20-30 or so. In exchange, we will be going from this:

```
alertText: {
  en: 'Back Then Front',
  de: 'Nach Hinten, danach nach Vorne',
  fr: 'Derrière puis devant',
  ko: '뒤로 => 앞으로',
  cn: '后 => 前',
},
```
To this:
```
alertText: LocaleText.backThenFront(),
```

It's not comfortable, but it's no worse than the status quo.

**Comment by Legends0** [comment]
How about i18n?

**Comment by JLGarber** [comment]
Hmm. I like that in terms of "it's *really* short", but I'm not sure whether we want to deliberately introduce industry jargon as a project keyword.

**Comment by VanSlanzar** [comment]
And why not (common respons), because either it will be used with (respons), or replace it. The principle of this file is to make it all simple and common for all languages if I understood correctly.

**Comment by JLGarber** [comment]
Thinking about this more, and after some discussion, I'm a little unsure how we want to handle the structure of this new element. Personally, I think it should be an object of functions just like `Responses`. This would maintain commonality with how the rest of the replacement elements work. However, because of stuff like `'stack on ' + matches.target` we would need to figure out some way to pass that information to these functions. As I see it, we have two options there:

1. Nest functions horribly:

```
let LocaleText = {
  stackOnTarget: () => {
    let intermediaryFunction = (data, target) => {
      return {
        en: 'Stack on ' + data.ShortName(target),
        de: 'Auf ' + data.ShortName(target) + ' sammeln',
        fr: 'Packez-vous sur ' + data.ShortName(target),
        ja: data.ShortName(target) + 'にスタック',
        cn: '靠近 ' + data.ShortName(target) + '集合',
        ko: '쉐어징 → ' + data.ShortName(target),
      };
    }
    return intermediaryFunction;
  }
}
```

The advantage to this is that no matter what, we could call `LocaleText` functions in exactly the same way we would any other replacement, and they would just work. (Here, we would write `alertText: LocaleText.stackOnTarget()`.) The downside is that it's just so *bad*.

Or, option 2:

```
let LocaleText = {
  stackOnTarget: (data, target) => {
      return {
        en: 'Stack on ' + data.ShortName(target),
        de: 'Auf ' + data.ShortName(target) + ' sammeln',
        fr: 'Packez-vous sur ' + data.ShortName(target),
        ja: data.ShortName(target) + 'にスタック',
        cn: '靠近 ' + data.ShortName(target) + '集合',
        ko: '쉐어징 → ' + data.ShortName(target),
      };
  },
}
```

This makes sense and doesn't nest any extra functions. Unfortunately, we now have to remember how to call each `LocaleText` function. ("Does it take 1 argument? 2? I'm not sure, I gotta look at the `LocaleText` file again".) We would call this as `alertText: LocaleText.stackOnTarget(data, matches.target)`. That still saves the tons of vertical space we want, but it does tend to creep over horizontally.

Maybe I'm overthinking this and we *could* figure out a good way to just return bare text objects? I feel like limiting this to stuff that doesn't require access to `data` or `matches` might make stuff harder in the future, but there's of course the very reasonable counterpoint "that's what `responses` is there for!"

Sorry this is so rambly. I've not had a lot of luck sitting down and putting something really solid together, so I'm instead just trying to get some thoughts written down in hopes someone else can make something good out of the pieces.

(Also, to be clear, I'm not taking this as a situation where I feel that `LocaleText` is settled, just that I'm using it as a placeholder until we *do* work that out.)

**Comment by VanSlanzar** [comment]
I am not competent in this area, so I cannot help you. But I thought about it:
- could the new file work like (common).
- If this is the case, it would suffice to fill with a maximum of translation all the situations that we have in the files (raid, trial and other). What the file does (respon).
- You just have to push it further, and have as many triggers as possible. What we forget, would be added afterwards.

This is only my reflection, I do not know if it will help you.

**Comment by quisquous** [comment]
Coming back to this, I think with output strings, this repository of common translations could be a repository of output strings to reuse.  I think this would easily let us make a dictionary of bare text objects that could be reused, as those strings can now have parameters in them.
