### ISSUE TITLE
Support network log lines in cactbot

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#1328]
Mentioned in #1312.

cactbot currently only operates on act log lines, but this has some limitations.  There's more data in the network log lines that would be nice to write triggers against (like lightsteeped stacks, or zone ids, or effect ids, or cast bar lengths, etc).

Options look like this:

(1) provide network log lines in addition to act log lines (cons: now you're parsing 2x as much data for every trigger
(2) replace act log lines with network log lines (cons: a bunch of work, also risky, maybe confusing to developers)
(3) implement hypothetical new log injection technique to add new act log lines with this info, continue to use act log lines (cons: farther in the future, also a bunch of work)

I think #2 is plausible. Timelines use raw act log lines, but they're all faiiiirly normalized and we could...convert them magically into network log lines, and use tests to verify that they can be converted as such. Most other things use regex helpers, which could be converted to network log lines too.

This would also solve the zone id issue and effect id issues (to avoid translations on both of them), would provide positioning information on more lines, and some other good stuff.

**Comment by FabulousCupcake** [comment]
Has anyone observed/measured the actual performance impact of option 1?  
Doubling parsing load sounds bad, but maybe it's still well within the acceptable range

**Comment by JLGarber** [comment]
Whee, yes please! This would also mean no more need for supporting both types of log lines in the timeline utilities. That was a major source of confusion for me when I first started the updates to them.

Off the top of my head, I want to say that 1 isn't an option. It's a guarantee that it will double processing time, and that's only going to get worse as the plugin gets older. That being said, FabulousCupcake is right that we should get some hard numbers on it. Didn't panicstevenson do some benchmarking for us when we moved regexes to global case insensitivity? Maybe we could ~bribe~ persuade them to whip something up for us here too?

Honestly, I don't think it's *too* risky to switch to network lines. Just about all the timelines use `15` lines for everything, so in theory automatic conversion there should Just Work. I know there are a few here and there that use other lines (Fractal Continuum comes to mind) but the majority should be fine.

**Comment by quisquous** [comment]
Re: Option 1.  Yeah, agreed that maybe I'm overthinking the performance impact, but it sure *feels* bad.  There's also (unmeasured) overhead for the plugin having to turn all the logs into strings and send them to javascript too.  An additional negative that there's also just added developer burden to have multiple kinds of log lines to match against, and some fields that would only work in certain cases.  It'd be simpler to think about everything if there was only one kind of log line.

Re: Option 2.  Another negative is any triggers or timelines that folks have made in their user directories.  I could certainly publish some "deprecation" warnings for a while to give people a chance to update them to regex helpers, and then we could switch over.  I'm not sure if there's a better way to do this, though.

**Comment by JLGarber** [comment]
I'd like to say that most people who use the user folder would be able to fix things at that point, or at least would know where/how to ask for help on it, but that's probably not a safe assumption. (I know for Eden's Gate I put some user triggers together for some static members who weren't comfortable with anything beyond "drop this into your user folder".) 

I think you're right about a long-term deprecation warning as you did for the move to ngld. The population affected by this would be a lot smaller than the ngld move anyway.

**Comment by valarnin** [comment]
This sounds like the sort of thing that should be done to coincide with a new major content drop or expac. Maybe add raw lines in the last raid tier for ShB along with a deprecation warning, and remove the old lines when the next expac releases, since custom triggers and such should be naturally phased out for the most part by that point?

**Comment by JLGarber** [comment]
I think you're right about aligning it with a new tier, but maybe a little prior. We *really* want to ensure any bugs are shaken out before everyone has to focus on Savage to the exclusion of everything else.

As far as straight replacement vs both alongside each other, my view is that the entirety of Eden's Verse has had regex replacements available. The only major content that would be affected by this is Ultimates, and I *do* think it's a ~safe~ not unreasonable assumption that anyone using cactbot for Ultimate content should be capable of fixing their own user files.

**Comment by valarnin** [comment]
> We really want to ensure any bugs are shaken out before everyone has to focus on Savage to the exclusion of everything else.

That's why I was suggesting adding the second alongside the first, so that things can be tested and transitioned to the new format over time rather than doing everything at once and risking that something isn't working or got lost in the shuffle.

So the timeline (heh) for Cactbot releases would look like:

- Eden's ??? release: Add the raw lines
- After Eden's ??? release: Replace helpers
- After Eden's ??? release: Replace timelines
- After Eden's ??? release: Replace triggers, etc
- Next expac release: Remove old lines

**Comment by ngld** [comment]
I think you're overthinking the performance impact. OverlayPlugin already has an event for network log lines (`LogLine`). Due to the way it's implemented, the whole log line parsing and JSON encoding happens regardless of whether an overlay subscribes to the event or not.
ACTWS overlays always subscribe to that event since SkillDisplay requires that data and I have no way of telling whether the ACTWS overlay is SkillDisplay or MopiMopi.
Either way, OverlayPlugin already provides network log lines and that part seems to work fine.

**Comment by quisquous** [comment]
Well, if the performance concerns aren't really an issue, then a hypothetical plan:

- add support for triggers to use network logs
  - add some new netRegex / netRegexDe / etc ?
  - add some different NetRegexes file, akin to Regexes?
- convert triggers to use new netRegex / NetRegexes
  - surely there's going to be some difference here that will bite us
  - I verified that nothing uses `regex: /match/` anymore, so maybe this is just a search+replace?
- auto-convert timelines to use network regexes
  - I think we should start with doing this implicitly in code rather than converting them in text
  - this would also let us convert to using NetRegexes, which match faster
  - probably need some tool to figure out which ones don't auto-convert
  - maybe somebody could make better hw trial timelines (ravana, sophia, etc) to fix these
    - insert JLGarber bat signal here
- possibly remove the old regex stuff eventually? Or maybe just leave it??

**Comment by JLGarber** [comment]
I can certainly look into the Heavensward timelines, yes. Some of them will be *rather* more difficult though, since I don't have people on Crystal to drag through for the amount of time necessary. Sephirot in particular would be extremely difficult, for example. (I suppose given that we already have the existing timelines, I can try building them out from FFLogs. Not something I've done so far, but it has to be doable.)

**Comment by quisquous** [comment]
I think everything supports network log lines and NetRegexes at this point.  I don't think it's a good idea to remove normal parsed log lines or Regexes.  So, I think this is done.
