### ISSUE TITLE
ucob encounter issues

### ISSUE THREAD

**Issue by Karasu77** [quisquous/cactbot#1394]
Hello ! I'm having a problem with cactbot, sometimes ucob alerts/timeline didn't work at all. and someday, it work for like 1 time (generally when I restart the duty) and it didnt work after a wipe. It seems tied totally to RNG, I don't understand because I don't have any problem with every 5.0+ fights.
I'm unsure about others old encounters but i'm pretty sure it happens to me too sometimes on others content.
my high performance parsing filter is not disabled and I already checked if my in game log was hiding something but it seems everything is fine also cactbot don't send any error in the log.

EDIT: Sorry to add this: it seems it happens only when I am resetting the parse manually before the pull but it didnt happens on new encounter even if i am resetting the parse manually between pulls.

**Comment by wsoxfan1214** [comment]
I also get this pretty frequently. Also have issues with de-syncing when pushes happen early in P1, effectively making the timeline unusable the rest of the phase.

**Comment by Karasu77** [comment]
same things for UwU

**Comment by quisquous** [comment]
Are there errors in the overlayplugin log when this is happening? In the cactbot options, if you click developer options, and the the debug option for raidboss, this will add a "timeline time" (among some other debug output in the console) by the timeline.  One thing to check is if it is still running after a wipe, and that's why this is happening.

Re: timelines.  ucob phase 1 is tricky to sync.  I could probably do a better job, but there's a large amount of time between when twin drops the neurolink and when the next ability comes to sync to, and so timelines are always going to be a bit messy.  If you can attach some [network logs](https://github.com/quisquous/cactbot/blob/master/docs/FAQ-Troubleshooting.md#how-to-find-a-network-log), I can try to make something that works.

Sorry, but  "same things for UwU" is a bit vague.  Do you mean the timeline? Do you mean that it's not working sometimes?

**Comment by quisquous** [comment]
> EDIT: Sorry to add this: it seems it happens only when I am resetting the parse manually before the pull but it didnt happens on new encounter even if i am resetting the parse manually between pulls.

What do you mean by resetting the parse manually? And you're saying when you do that, that's when the problem occurs?

**Comment by wsoxfan1214** [comment]
I'll see if I can get some network logs uploaded for you later. Thanks!

**Comment by Karasu77** [comment]
Timeline didnt work at all, I only have basic triggers (provoke sound, hallowed ground sound, etc)
but nothing work in the fight.
By resetting the parse manually, i mean pressing "Clear Encounter" on ACT. I do that each wipe, that's why the timeline work only the first try and then i didnt work again.
Same things for uwu means it's exactly the same thing as ucob, it work only the first try.
I'm gonna see if I can use logs

**Comment by quisquous** [comment]
Hi, just checking back here again.  I heard from @panicstevenson that uwu seems to be working.

If any of you are still having uwu or ucob issues, the best thing to do is to [attach a zipped up Network log](https://github.com/quisquous/cactbot/blob/master/docs/FAQ-Troubleshooting.md#how-to-find-a-network-log) to this issue.  Even a video would help at this point.  This would help a lot with whatever's going on in p1 ucob especially.

A second thing to try is to go into the cactbot config, turn on developer mode, and then turn on raidboss debug mode.  This will add a small timer to the side of raidboss timelines (and add a bunch of debug output).  If the timer is still running when you're starting a fight, then that's an issue.

A third thing is wondering if this is #1453?

**Comment by soveriegn3** [comment]
Hi, wanted to add I'm also having issues with the UCOB timeline, and fire in/out continuing to fire (ha) incorrectly even after a wipe. The fire in/out spam after wipe has so far happened every time we've made it to Nael. I also experienced issues with the timeline all-together disappearing, but I'm not sure if it's related to this existing issue. I found this thread after we were done raiding, so I plan to record with developer mode and debug mode on next time. I'm attaching an affected network log.

[Network_20510_20200623.zip](https://github.com/quisquous/cactbot/files/4828019/Network_20510_20200623.zip)

**Comment by quisquous** [comment]
@soveriegn3 The delayed triggers I filed as #1513.  It's not ucob specific, but it's worse in ucob because all the fire triggers all get launched with delays at the start of the phase.  My recommendation is to not wipe in Nael phase.  :wink:

The timeline disappearing is weirder.  I have seen that happen when there's a crash, which you would find in your OverlayPlugin log afterwards.  If you see it again, check there and let me know any additional info.

This all sounds different than the previous issues of "phase 1 desyncing" and "sometimes the timeline doesn't start" too.  I'm still hoping my timeline changes fixed the desyncing, and I don't know what's going on with the timeline not starting.

**Comment by soveriegn3** [comment]
Finally got back into UCOB today, and couldn't replicate the issues of the timelines being out of sync or not loading at all. I did get a few samples of fire in/out firing after a wipe but it looks like you covered that in  #1513. thought I'd update.

**Comment by quisquous** [comment]
Sounds like this is maybe fixed.  Let me know if this is still happening.
