### ISSUE TITLE
Eureka Baldesion Timeline 

### ISSUE THREAD

**Issue by VanSlanzar** [quisquous/cactbot#1403]
I make this request because arrived at the end of Ozma fight, the timeline continues while it was enrage.
**Start cast enrage**
![1 Enrage](https://user-images.githubusercontent.com/61565834/80894386-d99e2280-8cda-11ea-9534-cb551f3dd499.PNG)
**Timeline continue, but this enrage cast**
![2 Enrage](https://user-images.githubusercontent.com/61565834/80894403-018d8600-8cdb-11ea-9210-d3fc4182abfe.PNG)
**End of cast, party wipe, 0.1%, sadly**
![3 Enrage](https://user-images.githubusercontent.com/61565834/80894431-2e419d80-8cdb-11ea-8359-7d11fedc420b.PNG)

**Log Prot-Ozma**
[Proto-Ozma-2020.04.26-17.52.15.zip](https://github.com/quisquous/cactbot/files/4569323/Proto-Ozma-2020.04.26-17.52.15.zip)

**Start cast Enrage,10s cast i think**
[18:02:36.000] 00:282b:Proto-Ozma prépare Étoile filante.
**Repull after wipe, after raise XD, ignore it.**
[18:02:49.000] 00:0839:Ouverture de l'enceinte de confinement de Proto-Ozma!

**Comment by quisquous** [comment]
Ah, sorry for the confusion.  I took a look at the timeline itself, and the enrage just isn't listed.  Because this fight has so many random phases, it doesn't know that you are on the "final" star phase.  That's why there's a black hole counter as a trigger, so that if you're not going to make the dps check, you can just take the final black hole out safely.

I'll add an enrage from your log, thanks!

**Comment by VanSlanzar** [comment]
Thank you for your work.
