### ISSUE TITLE
util: test_timeline breaks when there is a # in the text

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#1499]
See #1498 for an example, but:

```
$ python util/test_timeline.py -f Network_20190328.log -t unending_coil_ultimate.txt -lf 8
0.000: Matched entry: 1200.0 Teraflare (+1200.000s)
1230.921: Matched entry: 1230.9 --sync-- (-0.021s)
    Warning: 30.921s since last sync
1453.799: Matched entry: 1453.7 Morn Afah Enrage (-0.099s)
    Warning: 222.899s since last sync
``

If the `#` gets removed, then this works properly.  It would be good to verify that this is not broken in game too.

(cc @JLGarber)

**Comment by JLGarber** [comment]
I forgot to look at this one yesterday and I won't be able to immediately, but off the top of my head I'm inclined to say the problem is in the `clean_line` helper:

`return line.split("#")[0]`

So as I see it, we need to check for whether a line containing `#` contains it as a(n intended) literal or as a control character. Shouldn't be too hard to regex "is this character inside quotes?"

**Comment by JLGarber** [comment]
Huh. It looks like it's not as easy to do something useful with "is this inside quotes" as I thought. It's doable by splitting the line on double quotes and *then* dropping everything after `#`, but that seems messy:

```
line_groups = line.split('"')
line_groups[2] = line_groups[2].split("#")[0]
return '"'.join(line_groups[i] for i in range(0,3))
```

Still, given current assumptions about how timeline lines are formatted, it would work.

**Comment by quisquous** [comment]
Yeah, I think that's reasonable.  I think you also need to handle cases where the aren't quotes too, e.g. `# just a comment`.
