### ISSUE TITLE
Inline TTS / Alarms?

### ISSUE THREAD

**Issue by IrealiTY** [quisquous/cactbot#152]
https://github.com/quisquous/cactbot/blob/b9c4c5732b6d181595fc10537c708b0c3d9b72c6/user/raidboss-example.js#L138

is it possible to use TTS or Alarms for inline reminders or events?

```
     infotext "Final Sting" before 5 SoundAlert 
```

**Comment by quisquous** [comment]
At the moment, no.  You can only info/alert/alarm, and there's no way to configure it.

I think it'd be possible to add a separate section for timelineTriggers in the triggers file where the triggers behave like normal triggers.

**Comment by veltall** [comment]
I've been monkeying around with cactbot for the last 3 hours since I found out about it, and this is my top-priority feature as well. I'm emulating this behavior with a lengthy workaround.

## How-to

1. Enable global `SpeechAlert` in `~/user/raidboss.js`
  This means all triggers and timeline alerts will activate TTS unless specifically disabled.
2. Specifically disable TTS for all built-in triggers in `~/user/raidboss.js`
  Screenshot: https://i.imgur.com/EqASdtO.png
3. Toggle on specific built-in triggers as desired (see `Tsukuyomi Bright Blade` above).
4. Insert custom timeline reminders as desired.
  Screenshot: https://i.imgur.com/GqAPsmP.png

## Effects
- Allow for use of built-in triggers in conjunction with custom timeline alerts
- Allow for precise control of TTS-enabled alerts
  All trigger-based alerts are toggle-able
  All timeline-based alerts are forced to be TTS-enabled

## Drawbacks
- Confusing config schema
  There are two types of alerts.
  Timeline-based alerts can be defined in (1) a self-contained timeline source file, or declared (2) contextually in the self-contained triggers file, or overridden (3) in the user config file.
- Lengthy toggle section in user config file
  Screenshot: https://i.imgur.com/EqASdtO.png
- Even more confusing config schema
  There's no way to contain the toggles in the encounter-specific files themselves, they have to be included in the massive user config file. This makes it a non-trivial problem to find the toggle needed.

**Comment by quisquous** [comment]
oh no :sob:

If you end up having to do something like list every trigger in your user config, then that's really no good at all.  Please let me know if you have to go to such lengths in the future, because clearly something needs to be changed.

As I said above, I think this is a good feature.  I should be able to get to it this weekend and make it possible to configure/disable timeline-based triggers without having to list every trigger.

Regarding the confusing config schema, let me maybe try to explain why it is the way that it is.  The timeline files themselves are meant to be 100% compatible with ACT timeline, so folks who aren't using cactbot can still use them.  That's why all of the overrides are in the triggers file and not in the timeline itself.  They can be strings, but many of them are in javascript so allow for more configuration, like only showing if you're a tank or for particular languages, which is more extensive than what the timeline grammar allows for.  Finally, user config file is where users should add their own alerts (which is where your #4 should go).  Cactbot releases will include the timeline and triggers files, so any changes you make to those (and not in user) will get clobbered.

If anybody wants to write a tool that autogenerates some (web?) ui from trigger files and can then autogenerate a **user/raidboss.js** from that, I'd be happy to review it.

**Comment by veltall** [comment]
The design choice makes sense; you want the timeline (with its limitations) to do as little as possible for cross-compatibility purposes, and you want to separate custom configs with built-in configs for ease of upgrading those triggers `.js` files in the future.

The only problem I have with this schema is that the userconfig file `~/user/raidboss.js` gets too big to navigate even with code folding. If we could make `raidboss.js` source from other smaller config files for each encounter, that'd make it easier to keep things neat and tidy. Something like

```
cactbot
|-- resources
|-- ui
+-- user
    |-- raidboss
    |   |-- raidboss.js
    |   |-- tsukuyomi.conf
    |   |-- o8s.conf
    |   +-- uwu.conf
    |-- oopsyraidsy
    +-- jobs
```

**Comment by quisquous** [comment]
Are you configuring that many triggers? Can you pastebin or gist your raidboss.js just so I can see what you're trying to do? https://github.com/quisquous/cactbot-user/blob/master/raidboss.js is mine, for example.

**Comment by veltall** [comment]
It probably will no longer be a problem once the timeline-alerts can be configured. Like you said, I shouldn't have to list every trigger to be able to control them. My suggestion is only a continuation of the workaround I had to do to achieve a similar result; it's only worth doing if it takes under 30 minutes.

---

The following discussion is not really relevant since it's just my impression from learning to use cactbot. I'm happy with the changes to be made this weekend, tentatively. Anyway, some feedback!

Long-term, I agree that `Options.DisabledTriggers` and `Options.PerTriggerOptions` are probably fine for most use cases (most people are happy with defaults), but I still think it's slightly too unfriendly towards user customization. Here's what I mean:

Imagine a user who wants to edit all the alert texts for built-in triggers. Her reasons may vary, but these are two I cooked up on the fly for discussions:

1. Someone might prefer to be told specifically what to do (Shield the tank), while
2. Someone else might prefer to be informed of the event so they can come up with the correct response (e.g. no need to shield the tank if he's already used Holmgang)

The triggers shipped with Cactbot cannot satisfy all use cases, so there is some argument to be made for small but overarching modifications like changing the text.

So, let's say that this user's desire is legitimate. How does she go about achieving it? She can't modify the triggers directly in the `~/ui/raidboss/triggers/tsukuyomi-ex.js` file, since those are meant to be overwritten with future updates. She would have to get the `trigger id`s from that file and modify each entry like I did in the `~/user/raidboss.js` config file.

In terms of keystrokes, both options don't differ by much, but in terms of usability, it's a huge gap. An average user can find the text and replace it with what they want; an average user can't read the appropriate README to understand that they need to reference each trigger by unique keys in a specific Javascript object in a specific file.

It's not a big deal but it discourages you from making small "quality of life" changes.

I love the JSON user config schema, but I think that use case and ours are significantly different. Take VSCode, for example, the user config in that context is content-agnostic: it doesn't matter if I'm editing a javascript file or a python file, or if I'm doing webdev or game design, I want my font to be size 12. These settings are global, so they should be grouped together in one place.  
User config in Cactbot is not content-agnostic; changing the text for tank buster in Tsukuyomi doesn't do anything for the tank busters in o8s. Since the effect of the settings are less than globals, I think it makes some sense to have them localized into their own scope, so that if I want to change something about the tank buster in o8s (like an alert for which cooldown to use), I don't have to browse through 20 other fights.

What I have in mind instead is to duplicate the triggers file into `~/user/raidboss/tsukuyomi-ex.js`, comment out all the values, and allow the user to toggle it on as they find/modify it. Since `~/user/raidboss.js` already sources `~/ui/raidboss/data/triggers/tsukuyomi-ex.js`, we only need to make `~/ui/.../tsukuyomi-ex.js` source `~/user/raidboss/tsukuyomi-ex.js` where the user config for that fight sits.

Back to reality, your config file is less than 100 LOCs, but it basically only modifies one encounter. At any given time, a user may expect to go into 4~6 different encounters. If you run with pug groups and have to make on the fly modifications in between pulls, it'll be a bad time.

**Comment by quisquous** [comment]
Thanks a lot for the feedback.  It's super appreciated.

I think an assumption that I make is that most folks won't add too many triggers of their own.  cactbot comes with a lot of triggers (too many triggers?) so I figure folks can turn off what they don't want.  I think you are right that most folks are happy with the defaults, so I haven't put a ton of time into making customization easier, just possible.

My assumption about text replacement is that at some point you should just disable the built-in trigger and copy and paste it and make your own trigger that does what you want.  I think text replacement could be easily added, though.

I am not sure about having customization be content-agnostic.  What you do for tank busters in UwU is going to be different than tank busters in Ridorana.  I don't think the cooldown for the tank buster in o8s applies to what you do for other tank busters (or even every tank buster in o8s).

cactbot has a lot of sharp edges (especially around installing and customization), and those largely haven't gotten better because my cactbot to-do list has a pile of things I prioritize higher and I just don't really have time for it at the moment, sorry.

I'm supportive of improving customization and I'm happy to talk about it if somebody wants to contribute.  I think if I was picturing something I'd want, I would make something that could load all the trigger files in a web page and present the user with auto-generated UI for disabling / configuring / replacing text / etc all of the triggers.  Maybe there'd be a separate file for this auto-generated config so that it could be separate from the manual one, and also cleanly reloaded in the future to repopulate the ui.  That would probably be a lot more user friendly.

I also think there is a lot to be said about having something that makes it easy to remind you of pug strats and cooldowns.  I'm not sure if that's just like an input text entry where you just write down "I'm going to A", or something complicated with cooldowns and timings that's part of the timeline (or a separate cooldown timeline??).  It's a problem that you can see from my user config that I try to solve with timelines some, but I don't know that's a satisfying answer either.

**Comment by xDemonessx** [comment]
> I'd want, I would make something that could load all the trigger files in a web page and present the user with auto-generated UI for disabling / configuring / replacing text / etc all of the triggers.

This is a big take away. As a user who often deeply customizes these sorts of things, this is the biggest thing cactbot is missing - ease of use when it comes to customization. I modify my UCoB timeline to match my groups use of waymarks when calling divebombs, as one timeline example. I also find it very frustrating to have to disable sound alerts every update via a text file, since its always easiest to overwrite the directory as a "clean install" every new update imo. CSS is also something I do modify, but that's really secondary to this whole issue. 

Even something so simple as the ability to quickly navigate to where these files live would help. Its very cumbersome navigating through all the data by hand, and for a user who may not understand the directory structure its confusing to know where the files _should_ live.

**Comment by quisquous** [comment]
Re: disabling sound alerts.  Does setting `Options.SoundAlertsEnabled = false` in your **user/raidboss.js** not get you what you want?  Or, are you only disabling some of them?

Please let me know if there's something that's onerous to modify.  I could have probably added some option for changing what the ucob markers are if I had known that folks were using something other than A, B, C.

**Comment by xDemonessx** [comment]
It does what I need it to do; I disable sounds then enable TTS. Backing up my user settings in general/knowing what files I've tampered with is what makes the process cumbersome. 

I'm just one person though and am likely going about this the wrong way as well.

**Comment by quisquous** [comment]
@xDemonessx Yeah, I'm wondering a bit if you're going about this the wrong way.  In general, you should add and touch files in the **user/** directory and not touch anything in the **ui/** directory.  (If you need to touch **ui/** to do something that you can't do in **user/** you should let me know so that I can make it more configurable).

What I was trying to say is that if you add a line to your **user/raidboss.js** file that says `Options.SoundAlertsEnabled = false`, then this will turn off sound alerts forever and will never get overwritten in future cactbot updates.  Similarly, css files in **user/** will not be overwritten and can be used to override the built-in css.

I tried to explain some of this here: https://github.com/quisquous/cactbot/blob/master/AdvancedCactbot.md#configuring-ui-modules but it could probably be clearer.

What kinds of things do you find yourself having to re-do every cactbot update?

**Comment by xDemonessx** [comment]
I see; thanks for explaining that. I didn't realize I could add that line to raidboss.js and it would take priority, that makes it a lot easier. Aside from that it's really only been the UCoB marker thing which is very specific; 1 2 and D vs ABC. I've changed language on some timelines like O8S as well: "bait then stay" for forsaken 2 would just constantly confuse me; personally I like to see/hear mechanic names (Future/Past) clearly stated flat out to know what to execute. ESPECIALLY in any prog. I know what to do, I dont like to hear what action to perform - it was difficult for me to understand Nael's timeline and actions in UCoB with cactbot because "in/out" didn't make sense to me (it does now). 

Having several version of timelines for these specific cases isn't necessary - my brain simply works differently than some players.
