### ISSUE TITLE
Raidboss; UCOB Nael Divebombs

### ISSUE THREAD

**Issue by torchick11** [quisquous/cactbot#1521]
For some reason there's specific types of patterns but in these specific ones the term "(WIDE)" appears and the third indication of a divebomb spot isn't safe at all. We had "NW SE W (WIDE)" but it was definitely meant to be placed on SW, what does (WIDE) mean? Why is the third one in the patterns with (WIDE) incorrect?

**Comment by quisquous** [comment]
See: https://github.com/quisquous/cactbot/blob/master/ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.js#L1778-L1784

If your dragons are N, NE, E, SE, SW.  The first mark needs to go NW.  The second mark needs to go SE (to not get hit by the NE dragon).  The third mark could go S between the last two dragons, but the second dragon is pointing there.  It's not wrong to put it S, but the timing is much tighter.  cactbot suggests to put this mark W instead.  This takes up more of the arena space and so it calls it "wide" when this happens.  (And everybody should be very close to the middle or move east after the Nael mechanic to avoid the third dive.)

**Comment by torchick11** [comment]
The problem is the wide isn't making middle safe, its literally making dragons running through the middle, We had W (Wide) and it had one dragon go straight through the middle.

**Comment by quisquous** [comment]
One possibility that might have happened is if the W (Wide) mark goes too far north, then it will cut off even more of the middle.

**Comment by torchick11** [comment]
Possibly? but one of them directly came from SE

**Comment by quisquous** [comment]
Yeah, agreed.  SE->W is the case I'm describing here.  That line does cut through the middle some, but not entirely, which is why there's a "wide" callout. 

I think there's a trade-off here between what's unsafe for the individual and what's unsafe for the group and maybe this trigger should tell people to go S in that case, even if it was more likely to get them killed.  I asked around about feedback for "wide dives" a few times and nobody really had great opinions on what they wanted.  So, I wrote what worked for my group at the time, which maybe doesn't work for everybody's group.

I guess what I'm trying to explain is that this is working as expected.  (If I can help explain more, I can do that too? But it sounds like we're on the same page here.)  So you have a couple of options?
* Accept it: When you see a wide dive, everybody should move east after the Nael mechanic (and be on the NE side of the middle)
* Ignore it: When you see a wide dive, that person should go between the last two dragons instead of clockwise of the final one.
* Change it: have me (or you?) implement an option that would call out S for this case instead of W (Wide).

**Comment by quisquous** [comment]
Closing this old issue, as I don't have anything else to add here.
