### ISSUE TITLE
Util: Make_timeline key failures when generating from FFLogs

### ISSUE THREAD

**Issue by JLGarber** [quisquous/cactbot#1538]
For some encounters, when generating a timeline from FFLogs, `make_timeline.py` will fail with a key error:

```
  File "make_timeline.py", line 440, in <module>
    print("\n".join(main(args)))
  File "make_timeline.py", line 234, in main
    entries, start_time = parse_report(args)
  File "make_timeline.py", line 106, in parse_report
    "combatant": enemies[event["sourceID"]],
KeyError: 24
```

You can replicate this with:
`python make_timeline.py -k KEY -r z6m4AX1qMVLRFDHk -rf 3`
`python make_timeline.py -k KEY -r MjRzayFgmHZA3Bxk -rf 7`
`python make_timeline.py -k KEY -r J4vzBkLgT7wcPAGQ -rf 24`

In each case, it seems to fail on an event where the ability used is an untargeted AoE, rom-wide or not. It looks like the list of enemies generated here:

```
    for enemy in report_data["enemies"]:
        enemies[enemy["id"]] = enemy["name"]
```
may not be complete. That may be a bug in what FFLogs is returning? Could be worth poking Kihra over, I'm not sure.

**Comment by quisquous** [comment]
So, looking at this E4S pull: https://www.fflogs.com/reports/PdgY73nvWp89ayMc#fight=8&type=damage-done

`util/make_timeline.py -k KEY-r PdgY73nvWp89ayMc -rf 8`

It's missing enemy id 31 with repeated events.
* `{'timestamp': 4508394, 'type': 'cast', 'sourceID': 31, 'sourceInstance': 1, 'sourceIsFriendly': False, 'target': {'name': 'Environment', 'id': -1, 'guid': 0, 'type': 'NPC', 'icon': 'NPC'}, 'targetIsFriendly': False, 'ability': {'name': 'Earthen Fury', 'guid': 17384, 'type': 1024, 'abilityIcon': '000000-000405.png'}, 'pin': '0'}`
* `{'timestamp': 4527034, 'type': 'cast', 'sourceID': 31, 'sourceInstance': 2, 'sourceIsFriendly': False, 'target': {'name': 'Environment', 'id': -1, 'guid': 0, 'type': 'NPC', 'icon': 'NPC'}, 'targetIsFriendly': False, 'ability': {'name': 'Weight of the Land', 'guid': 16648, 'type': 1, 'abilityIcon': '000000-000405.png'}, 'pin': '0'}`

I think this is just what fflogs is returning.  I don't remember it doing this before, but it's been a bit since I've used this feature to create timelines.  For example, the enemy list from https://www.fflogs.com/v1/report/fights/PdgY73nvWp89ayMc?api_key=KEY does not contain any enemy with source id 31.  The event list from https://www.fflogs.com/v1/report/events/PdgY73nvWp89ayMc?api_key=KEY&start=4508394&end=4508394 contains events with a sourceID of 31.  The errors all seem like the sourceID just doesn't exist when targeting the environment.

That said, if you look at the list of events from the second link, there are valid events with real sourceIDs that hit valid targets.  I'm partially inclined to just ignore these errors? Or only put them in some sort of "verbose" mode? Or something?

**Comment by quisquous** [comment]
Searching fflogs discord for 'Environment' nets me: https://discordapp.com/channels/192732719879290880/192732719879290880/608682913843773658

```
Kihra 08/07/2019
hmm one thing i am noticing is the Environment actor broke
you get an actor with no name instead
something changed in ACT with this
maybe it's that E00000 thing
when it used to just be empty
```

**Comment by quisquous** [comment]
Kihra made a fix to this.  There's now a "source" field and the guid of any of these "script bunnies" will always be 9020.

Compare with above: `{'timestamp': 4508394, 'type': 'cast', 'source': {'name': 'Titan Maximum', 'id': 31, 'guid': 9020, 'type': 'NPC', 'icon': 'NPC'}, 'sourceInstance': 1, 'sourceIsFriendly': False, 'target': {'name': 'Environment', 'id': -1, 'guid': 0, 'type': 'NPC', 'icon': 'NPC'}, 'targetIsFriendly': False, 'ability': {'name': 'Earthen Fury', 'guid': 17384, 'type': 1024, 'abilityIcon': '000000-000405.png'}, 'pin': '0', 'sourceID': 31}`

make_timeline could probably use the new event.source.name field here?

**Comment by JLGarber** [comment]
I think that would probably work, yes. I'll poke at that over the weekend. Thanks for checking in with Kihra!
