### ISSUE TITLE
npm install fail on windows

### ISSUE THREAD

**Issue by luis-echegaray** [quisquous/cactbot#1590]
```bash
C:\Users\leche\workspace\cactbot [master ≡ +0 ~1 -0 !]> npm install -g husky
C:\Program Files\nodejs\husky-run -> C:\Program Files\nodejs\node_modules\husky\bin\run.js
C:\Program Files\nodejs\husky-upgrade -> C:\Program Files\nodejs\node_modules\husky\lib\upgrader\bin.js

> husky@4.2.5 install C:\Program Files\nodejs\node_modules\husky
> node husky install

husky > Setting up git hooks
husky > Done

> husky@4.2.5 postinstall C:\Program Files\nodejs\node_modules\husky
> opencollective-postinstall || exit 0

At line:1 char:28
+ opencollective-postinstall || exit 0
The token '||' is not a valid statement separator in this version.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine
```

looks to be a powershell issue w/ husky:

a quick google search on husky issues:

https://github.com/typicode/husky/issues/690

got npm install working for me by setting:

```bash
npm config set script-shell null
```

**Comment by quisquous** [comment]
Hmm.  @panicstevenson: Do you think this is something we should add to ... documentation? or somehow have run automatically?

**Comment by panicstevenson** [comment]
Thanks for doing the heavy lifting here!

It feels pretty bad that husky seems to have a number of issues... I'd like to see this fixed upstream (doesn't seem like they could just ignore it...?) but there's also a few workarounds -- using git bash or cmd should also work, but I wonder if there's a decent way to inform anyone that runs into this. I don't know if documentation is the right answer? At least, intuitively it doesn't feel like _I_ would go searching cactbot documentation before running a Google search for that exact error.

**Comment by luis-echegaray** [comment]
If you all want, I can PR a markdown file for developer setup or something to that effect and that can have some of these caveats. This issue was across git bash, powershell and cmd so the only fix was that npm setting above

**Comment by panicstevenson** [comment]
Hmm, interesting. I just did some testing over in https://github.com/quisquous/cactbot/issues/1568#issuecomment-659653688 the other day and I did not see these issues. However, I was doing `npm install` from the repository's base instead of doing `npm install -g husky`. Is there a reason to install husky globally?

Also, testing from the same Windows VM in that linked comment, I can't reproduce this issue:

Git Bash:
```
$ npm install -g husky
C:\Users\me\AppData\Roaming\npm\husky-upgrade -> C:\Users\me\AppData\Roaming\npm\node_modules\husky\lib\upgrader\bin.js
C:\Users\me\AppData\Roaming\npm\husky-run -> C:\Users\me\AppData\Roaming\npm\node_modules\husky\bin\run.js

> husky@4.2.5 install C:\Users\me\AppData\Roaming\npm\node_modules\husky
> node husky install

husky > Setting up git hooks
husky > Done

> husky@4.2.5 postinstall C:\Users\me\AppData\Roaming\npm\node_modules\husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

+ husky@4.2.5
added 48 packages from 22 contributors in 3.155s
```

Command Prompt:
```
npm install -g husky
C:\Users\me\AppData\Roaming\npm\husky-upgrade -> C:\Users\me\AppData\Roaming\npm\node_modules\husky\lib\upgrader\bin.js
C:\Users\me\AppData\Roaming\npm\husky-run -> C:\Users\me\AppData\Roaming\npm\node_modules\husky\bin\run.js

> husky@4.2.5 install C:\Users\me\AppData\Roaming\npm\node_modules\husky
> node husky install

husky > Setting up git hooks
husky > Done

> husky@4.2.5 postinstall C:\Users\me\AppData\Roaming\npm\node_modules\husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

+ husky@4.2.5
added 48 packages from 22 contributors in 2.707s
```

PowerShell:
```
npm install -g husky
C:\Users\me\AppData\Roaming\npm\husky-run -> C:\Users\me\AppData\Roaming\npm\node_modules\husky\bin\run.js
C:\Users\me\AppData\Roaming\npm\husky-upgrade -> C:\Users\me\AppData\Roaming\npm\node_modules\husky\lib\upgrader\bin.js

> husky@4.2.5 install C:\Users\me\AppData\Roaming\npm\node_modules\husky
> node husky install

husky > Setting up git hooks
husky > Done

> husky@4.2.5 postinstall C:\Users\me\AppData\Roaming\npm\node_modules\husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

+ husky@4.2.5
added 48 packages from 22 contributors in 2.763s
```

I am on Windows 10, 64-bit with the following:

```
$ node --version
v12.18.2
$ npm --version
6.14.5
$ npm config list
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.14.5 node/v12.18.2 win32 x64"

; builtin config undefined
prefix = "C:\\Users\\me\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\me\Documents\GitHub\cactbot
; HOME = C:\Users\me
; "npm config ls -l" to show all defaults.
```

Is this similar to what you're seeing? Sorry if it comes off as excessive; I really have no issue with adding docs. My intent was kind of to go set out and just solve this issue upstream myself sometime this week, but I can't reproduce it.

**Comment by luis-echegaray** [comment]
ah that was just sloppy on my part!

the npm install was indeed giving off the error and I narrowed it down to husky dependency so I was running a global install just to throw the error in different contexts.

@panicstevenson is right, this issue can go away by itself in a few days especially if we can't reproduce easily.  I ran into this on two machines WIN 10 PRO install 19041.388 on all the different shells but my dev machine and dev VM on my mac might not be a large enough sample size.  Especially since I probably have to many random stuff cluttering my shell :octocat: 

at the very least, if a future contributor has the issue, this thread will come up easily!

**Comment by panicstevenson** [comment]
Definitely; I think this thread is good, and I think there's _something_ on the internet... which is also nice. Potentially we could do better? I just wonder what that better would be, especially if we don't know the exact root cause here. I think a lot of us (myself included) don't have an in-depth knowledge of npm or the node package lifecycle (especially since we aren't publishing a package), so I would be interested if there's anything that you potentially have in your environment that seems like a red flag with respect to this issue.

I think that a majority of contributors to this project are on Windows, and are committing either via Git Bash or via the GitHub Desktop application. In general, it feels like I'm the person that usually catches the non-UNIX compliant things in our scripts, so I was very surprised to hear that Windows 10 + Git Bash was a potential non-starter for _anyone_ since that seems like the most well-trodden path.

**Comment by ngld** [comment]
Using `||` and `&&` in the `package.json` scripts section is fairly common for NPM packages. `husky` isn't at fault here IMO. `yarn` implemented a custom shell parser to avoid issues like this (it parses these expressions in JS and runs them without relying on any OS shell).
However, this should work even with `npm` since it [defaults to `cmd.exe`](https://docs.npmjs.com/using-npm/config#shell) which supports this syntax.

The *only* way to encounter this error is to *manually* tell `npm` to use `powershell.exe` instead of `cmd.exe` which is unsupported by the vast majority of NPM packages and *will* cause further issues similar to this one. IMO the best we could do is tell people to run `npm config get shell` on Windows and to fix their config if it doesn't return `C:\Windows\system32\cmd.exe`.
