### ISSUE TITLE
Pull data from oopsyraidsy into logfile

### ISSUE THREAD

**Issue by JK-JNM** [quisquous/cactbot#1858]
## Summary

I was thinking about using the data from oopsy to turn it into data/graphs for my static, in order to help them understand where to improve better, currently it appears to only be possible in a manual way by copying everything to your clipboard and then importing it.
It would be nice to have the option to automatically output oopsyraidsy data into a logfile in order to enable a secondary programm to access it.

**Comment by quisquous** [comment]
I don't think it will be possible to automatically output oopsy data into a logfile.  Or, it's not impossible, but because cactbot is all javascript-based, it would require likely adding some overlayplugin c# function to write said files.

I think better approaches here are:
(1) automatic ways to process log files after the fact to generate these logfiles
(2) an export button on `oopsy_summary.html` that will save the current page in some easier to parse format
