### ISSUE TITLE
util: gen_effect_id.py missing some useful effect

### ISSUE THREAD

**Issue by Echoring** [quisquous/cactbot#1865]
Seems that`Stormbite: '4b1'` and `CausticBite: '4b0'` is missing in effect_id.js
Maybe it is because there are two different Stormbite/CausticBite effect share a same name?

**Comment by quisquous** [comment]
Yeah, that's exactly it.  It seems like from #1834 that there may be fields that say whether something is pvp or pve, so that might help to eliminate the pvp abilities that are causing conflicts.

**Comment by quisquous** [comment]
I don't see any fields for this to make this determination easier.  The two stormbites effects look impossible to differentiate.

I [asked in the XIVAPI discord](https://discordapp.com/channels/474518001173921794/474519195963490305/766828267746885632) but didn't get a good answer here.  It seems like there's nothing in the game data, and so in the future if these are missing, we'll just need to add them manually, sorry!

https://github.com/xivanalysis/xivanalysis/tree/master/src/data/STATUSES/root was also listed as a place where other people are trying to solve the same problem.  However, since that's not game data, I think it'd be better to just handle this inside of cactbot directly with our own set of ids.

I'm going to close this, as I don't think there's any automatic answers here, sorry.
