### ISSUE TITLE
User file ignored

### ISSUE THREAD

**Issue by mooztikette** [quisquous/cactbot#1892]
Hello, i had always been editing the raidboss.css file to have the timeline container go to the bottom right corner of the raidboss space upon every cactbot update.

A few months ago, only the "right" argument kept working, not the bottom, but since it wasn't that big of a deal and me being lazy, i just let it that way...

With the last update, you wrote a warning message about directly editing those files, which led me to have a look at the user file, and i started using it, according to the explanations here on Github.

My problem is that what i put and edit in the user file seems completely ignored.

I tried specifying it through OverlayPlugin > Cactbot options but it remains the same.

Did i forget to do something ?

Edit: i probably should have set this to question label, sorry about that

**Comment by quisquous** [comment]
It sounds like there's two issues, one is that (1) half of your previous CSS wasn't working and (2) all of your current CSS in the user directory isn't working.

So, one thing that I would suggest instead of trying to solve this CSS problem is that if you want to move the timelines and triggers separately from each other, there's now split presets.  If you go to ACT -> Plugins -> OverlayPlugin.dll -> New, there's `Cactbot Raidboss Alerts Only` and `Cactbot Raidboss Timeline Only`.  You can add these as two separate overlays and then move them wherever you'd like them to be.

If you want to solve the CSS problem, I suspect that your file is not loading at all.  Go to the cactbot options in ACT -> Plugins -> OverlayPlugin.dll -> Cactbot.  Enable "show developer options", then reload.  Then, enable the "debug" flag under raidboss, then reload ACT.  There should be a message that says something like `local user file: some/path/on/your/disk/cactbot/raidboss.css`.  If not, then make sure you have selected the cactbot folder in the cactbot options correctly.

**Comment by mooztikette** [comment]
Hey and thanks for the reply.

Indeed i got a message saying it has been loaded 👍 
`[18/10/2020 23:41:51] Info: Raidboss: BrowserConsole: local user file: C:\Advanced Combat Tracker\OverlayPlugin-ngld\cactbot\user\raidboss.css (Source: file:///C:/Advanced%20Combat%20Tracker/OverlayPlugin-ngld/cactbot/resources/user_config.js, Line: 83)`

But it seems to ignore what's inside :
![notepad++_YkRcRaZXv4](https://user-images.githubusercontent.com/39465024/96386576-3ebbd680-119c-11eb-9a37-74b530e4e84f.png)
I tried to have only that screenshotted part, or have a fresh copy of raidboss.css with just these 2 arguments edited, but nothing would work :(

**Comment by quisquous** [comment]
You're missing `left: auto;` in there.  Because `#timeline-container` already specifies `left: 0;`, you need to undo that to get it to attach to the right.

**Comment by mooztikette** [comment]
Oh ok, i believe this is the reason it stopped working at some point.
Did CSS modify something related to this ? Cause i never did anything else in a very long time to have my `timeline-container` attached to the bottom-right corner.

I did what you said, adding a `left: auto;` got it to attach to the right but i might be missing something to have it attach to the bottom.

Thanks :^)

**Comment by quisquous** [comment]
Similarly, add `top: auto;`.  The user file css works as if you appended it to the bottom of the real `raidboss.css` file.

**Comment by quisquous** [comment]
I still will suggest that you use the separate presets if you want to move them around separately.

**Comment by mooztikette** [comment]
Yes, i'm not home right now but unless i made a typo, i figured i had to do the same with `top: auto;` but it sticked to the top.

I probably will end up splitting the alerts and timeline as you suggest, but i like to understand what i do wrong and improve.

Just a question about splitting, i think i remember reading that it used more resources, is it actually the case ?

**Comment by quisquous** [comment]
Yes, splitting uses slightly more resources, but you will almost certainly not notice it.  I really think that is the easiest approach to this problem.

**Comment by mooztikette** [comment]
Alright then, i'll just use the splitted raidboss.
Thanks for your help :^)
