### ISSUE TITLE
Mounting Gullfaxi or Boreas sends a false Hallowed Ground or Holmgang call.

### ISSUE THREAD

**Issue by Lemagex** [quisquous/cactbot#191]
Not sure if intentional or not, figured I would report it anyway as 2 other friends reported the same to me.

Mounting either of the two mounts gives out the following calls targeted at the player.

Boreas - Holmgang, Gullfaxi - Hallowed Ground.

Steps to reproduce are simple, be on a tank class, mount on either of the mounts, and the call will appear on your screen.

**Comment by quisquous** [comment]
Thanks for this.  I always wondered why there were random Hallowed/Holmgangs at the start of frontlines matches and I could never quite figure it out.

It turns out that's what's in the log, though.  It has the ability id and the name of hallowed ground and holmgang.  I'm going to file this upstream with the ACT plugin.

**Comment by DAOWAce** [comment]
I've been seeing this for months since Boreas was my main non-flying mount, and I'm a tank main.

Just thought it was some oddity with mounting calling out Holmgang, never occurred to me it only happened with a specific mount..

**Comment by rsigim** [comment]
![image](https://user-images.githubusercontent.com/22231296/47827803-a2098f80-dd5e-11e8-82df-f20c80024431.png)
¯\_(ツ)_/¯

**Comment by quisquous** [comment]
This should be fixed now in the latest ffxiv plugin.
