### ISSUE TITLE
Allow choosing of what mechanics raidboss will call out regardless of which job you currently are

### ISSUE THREAD

**Issue by thefiz** [quisquous/cactbot#2076]
I use cactbot with my raid group using Yukkuri on discord to call out mechanics.  I was hoping there could be something added to cactbot, such as a "raid group" mode which would enable the calling out of all mechanics regardless of which job the person running it is on.  I have enabled this myself by commenting out the conditional lines in specific fights, but every update overwrites my changes.

Perhaps a toggle that disables all the "on you" triggers and enables everything else?  Just a thought

**Comment by quisquous** [comment]
Sorry, cactbot triggers are intended for individuals and not for group callouts.  There was for a long time a "groupTTS" field on triggers, but nobody ever ended up using it.  It's a lot of work to write triggers at all, and nobody is thinking about every trigger in this different "group mode".

My feeling is that people on PC should just use ACT themselves.  People not on PC should have somebody in the group do https://github.com/quisquous/cactbot/blob/main/docs/RemoteCactbot.md so that they can get dps meters and raidboss and whatever else they want.

You shouldn't update cactbot files themselves, as this no longer works. (See the last month of release notes for more information).  Instead, you should update user files as per https://github.com/quisquous/cactbot/blob/main/docs/CactbotCustomization.md#user-directory-overview

**Comment by Webberjo** [comment]
Why would you want your bot to call out mechanics for specific players/roles like "prey on YOU" and "get drainage tether" for everyone in the voice channel? That would just confuse everyone and likely result in deaths/wipes.

Also, in some fights mechanics happen very fast. Discord bots play TTS messages asynchronously, so mechanic callouts for every player and role would eventually get backed up resulting in callouts not happening until after the mechanic is over which defeats the intended purpose.

Either way is bad. If your bot is spurting irrelevant mechanics to everyone nonstop I guarantee you several people are just going to mute it for being obnoxious. You _should_ be wanting to _avoid_ unnecessary mechanic callouts. The less noise in voice chat the better.

**Comment by quisquous** [comment]
#2076 is also trying to get at this, so I'm going to close this, and follow up in that conversation.

**Comment by quisquous** [comment]
Oops, #2660 is about displaying the condition, not overriding it.  I'll leave my thoughts that I accidentally left on that issue here:

I am somewhat wary about this doing this in any generalized way, as conditions can have logic in them or are used to select one of several mutually exclusive triggers to fire.  So, blindly overwriting the condition function might cause some hard to track down bugs in some cases.  It's why I've avoided doing this in the past.

One option I've thought about in the past is adding some trigger field like `cannedCondition: 'isTank',` where we have a multiple choice set of conditions and then for such triggers in the ui you could pick from a list.  Unfortunately, there are many cases (e.g. inside of responses) that overwriting or replacing the condition itself won't be enough for users to be able to see them.  I think updating the condition function alone is somewhat of a dead end.

At a higher level, my question is: which triggers do people want to see that they can't see now, and what can we do to enable that.  In my opinion, what people ask about the most is probably tank busters, raidwide aoes, and tank abilities (invulns/provoke/frog legs/etc).  Maybe there are other things, but this is my understanding.  See: #2076.

A couple of ideas:

(1) **Just turn everything on for everybody**.  Long ago, there wasn't a config ui, and so it was hard to turn on or off various triggers.  Now that you can, if you don't care about raidwide warnings, you can turn them off.  I could see an argument where cactbot moves towards defaulting to showing everything to everybody and letting people turn it off themselves.  This also means rewriting triggers to show callouts that we previously would have omitted, and removing some condition functions.

(2) **Add more options, use helper functions more**.  Use more `caresAboutX` style functions to determine if we should show callouts for mechanics that don't apply.  Then add some raidboss options that say "I care about aoes, even if I can't do anything about them" or "please show me tank stuff".  Then we check those options in `caresAboutX` helper functions, and triggers get rewritten to use helper functions as much as possible.

**Comment by marcjcs** [comment]
Friend of mine was bothered that he doesn't get AOE callouts even though he's playing a rdps, and then I found out that ```caresAboutAOE``` doesn't check for rdps, the closest issue I could find is this one.

I think it'd be great if we had a way to override those conditions, or at least change the AoE condition because as far as I know, you have DNC's Shield Samba, BRD's Troubadour and MCH's Tactician that mitigates AoEs.

**Comment by quisquous** [comment]
This should be fixed by #3432.
