### ISSUE TITLE
Wrong common translation works

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [quisquous/cactbot#2146]
## Description

Some timelines are not translated correctly.
Happens in e9s

## Additional information

`S` does not mean `South` but it translates to south in each languages.
![스크린샷(3)](https://user-images.githubusercontent.com/4695371/101865041-8ff2b000-3bb8-11eb-8538-abdb76b94114.png)

**Comment by MaikoTan** [comment]
This is added via #1836 , it is designed to translate `S` in bracket for `South`.

**Comment by quisquous** [comment]
Hmmm.  I wanted to differentiate the left or right version of Art of Darkness from the protean/clock or partner stack version.  I don't know if there's a good abbreviation that can sum that up.

**Comment by quisquous** [comment]
We could just say `(stack?)` to differentiate those, if that's clearer? Does anybody else have better suggestions? Mostly my worry is that this ability name is very long already.

**Comment by JLGarber** [comment]
I feel like you mentioned, some time ago, the possibility of adding English to the timeline translations object. This could enable us to do something like `Art of Dark. (Clock/Stack)` without compromising scripted translation work.

**Comment by quisquous** [comment]
Yeah, I think mostly I haven't tested that adding English to the timeline translations works.  I think it would also need to be special for tests so that testing didn't complain about missing translations for it.  So, maybe a feature request for the future rather than a fix here.  I think I'm inclined to just remove (p/s) for now.
