### ISSUE TITLE
Matoya's Relict Porxie Sucked In Trigger Won't Disable

### ISSUE THREAD

**Issue by Felys1998** [quisquous/cactbot#2207]
## Description

I have set the "Matoyas Porxie Sucked In" trigger to disabled and I am still getting multiple overlapping text alarms and sounds for the mechanic which is painfully loud and annoying. I have reloaded the plugin after changing the settings and the issue persists across restarting ACT entirely.

## Additional information

![image](https://user-images.githubusercontent.com/2600400/102026349-3b833800-3d52-11eb-9ff0-6acdeb3ede07.png)

**Comment by imynwulf** [comment]
I can confirm that the barbeque trigger is also painfully loud and annoying. 

I tried adding a targetIsYou condition to the run away trigger, but that didn't seem to help the matter. It's as if the effect is being put on the character rapidly multiple times in a row.

**Comment by JLGarber** [comment]
The RUN AWAY text is worthwhile being an alarm, since that *will* kill the player if failed. It's based on "player gains the effect of Sucked In", which is applied repeatedly. I've sent in a PR that should make this a little less annoying by making Sucked In sound only once, as well as dropping Barbeque down to Alert.

**Comment by MaikoTan** [comment]
Sorry didn't notice this.
Glad to see it has been fixed.
