### ISSUE TITLE
Raidboss: Better go direction alert for MT

### ISSUE THREAD

**Issue by MaikoTan** [quisquous/cactbot#2247]
## Summary

  goLeft and goRight function is based on the direction of players who stand behind boss.
  For MT which facing boss, direction is reversed.
  With aggro condition, we can give a reversed alert to MT to make them feel better.

cc @DieMoe233 (who is the first one mentioned this) @ShadyWhite
(And thanks to @Echoring for translating this.)

**Comment by MaikoTan** [comment]
@DieMoe233 mentioned that there are few features in OverlayPlugin which can help us to fetch the current aggro target of Boss.
Maybe we can work from that first.

**Comment by quisquous** [comment]
Sorry, but this is something I disagree with.  I think it's better to be consistent here and always give left/right boss positions as if you were at the back of the boss.  I agree that it's confusing for tanks (and I've been a tank since forever, so trust me), but having directions that always mean the same thing is important.

Some people pipe cactbot into discord tts callouts, and so anybody who is a tank and doing this would confuse the rest of their group.  There are situations in e12s where the boss is fixed in place and I might be anywhere in the arena, and so having to think "ok I have aggro, so even though I'm behind the boss then left means right here".  It's simpler to always think "left means left side of boss" and trust that the callout is going to be correct without any other conditions.

I think if this is something you want locally, then it's better for a user folder, but for the shipped cactbot triggers I think it's important to be extremely consistent with directions.
