### ISSUE TITLE
Text-to-speech

### ISSUE THREAD

**Issue by Culerpica** [quisquous/cactbot#2320]
I have been using cactbot for so long. It is an amazing app and thx for the development of this tool. Since last few updates I haven't been able to enable text-to-speech. I usually open the raidboss-config.js and change the options.SpokenAlertsEnabled = true; however this is not working. If anyone can help with this I would appreciate it.

**Comment by MaikoTan** [comment]
Please follow this:

- Did you changed the "Default alert output" to "🆙💬 Text and TTS" or "💬 TTS Only"? (this option is below `OverlayPlugin -> Cactbot -> RAIDBOSS`)
- Did you installed some TTS plugins in ACT? (such as TTSYukkuri or FoxTTS, etc)
- If you're using System TTS instead of an independent TTS plugin, Does it functioned normally in system settings?

**Comment by Culerpica** [comment]
Oh! I didn't know I have the change the setting from inside the ACT itself. That solve it. Thank you for the support Maiko
