### ISSUE TITLE
Issue with importing files in user js files

### ISSUE THREAD

**Issue by Datachange** [quisquous/cactbot#2406]
I have been dabbling in adjusting and adding a few raidboss triggers. I am a software dev who happens to work with js, so I know a tiny bit of js. (Frameworks mask all the important bits.)

With the new user file paradigm, I am definitely liking the persistence of my changes across updates! But I have been having a couple issues with some code.

I tend to modify triggers in simple ways. I like to copy-paste the triggers from the data js files (e.g. e12s.js), and then make those modifications. When copying a few triggers, recently, I was getting a few null-reference/undefined errors. I had copied constants that were defined in the e12s.js file, and thus were not in global scope (tangent enhancement request). It would be nice if such global were exported, but not required as I can simply redefine them. However, I could not find a way around the Outputs being undefined (e.g. copying 'E12S Promise Junction Shiva').

I had tried importing Outputs, just like the e12s.js file did, but seeing as file references are different, that did not work. Then I tried using relative filepath from my user folder. That did not work. Then I tried as if it was in the ui/raidboss/ directory (like sound file references). Then I tried a direct, full filepath reference. ....Still nothing, all with the same error:

`Unexpected identifier at loadUser (<filepath>/cactbot/dist/config.bundle.js:1:41226) (<filepath>/cactbot/dist/config.bundle.js)`

...I since figured out a workaround for what I was doing, but I figured it was worth mentioning this hole I found with user files. ...Or I am doing something wrong. That could be it, too.

Thank you very much for all your work and help!

**Comment by quisquous** [comment]
Unfortunately, the trigger files themselves and user files are used in different ways.  Each built-in trigger file is an ESM module, with imports and exports.  The user files (because they can be loaded anywhere) are eval'd.  As such, the eval itself cannot import or export anything because import is not valid inside of an eval context.  There are a few default imports that a user file is provided (things like Regexes, NetRegexes, Conditions, etc) but they cannot import anything directly.  Additionally, each user file is evaluated into a single value (which in practice is the array of trigger sets because that is the last statement in the file), and so values from one user file do not leak into other use files.

It is a little bit unfortunate that in some cases where triggers are complicated and use some shared data structure or shared helper function at the top of the function, it is not as simple as just copying and pasting the trigger directly and you need to copy those constants around as well.  As the [documentation](https://github.com/quisquous/cactbot/blob/main/docs/CactbotCustomization.md#user-directory-overview) says, `At this point, you are writing JavaScript and CSS, and so you might need a little bit of programming savvy.`.  I think that's just how it is, even if it's unfortunate.

One thing that you can do (and that I do), is to pull the cactbot source tree down and put your user folder in `cactbot/user/` in the source tree.  Then you can run things like `npm run lintfix` and `npm run test` and this will give you some basic smoke tests on your triggers and give you better error reporting.  It would have almost certainly caught this.  Another debugging tip is to use the raid emulator, and try your triggers there.

**Comment by Datachange** [comment]
That all makes sense, and regardless, I was able to figure out a workaround.
I tempered expectations with my js knowledge, because I tend to know less of the more complex intricacies of js, but I know enough to be decent. So I get what you are saying.

Could there be more objects (which are commonly used in trigger files) that can be provided in your list of default imports, which might help ease the burden in situations like these? (Also, documentation on which libraries/resources we have access too, would be nice, too.)

Thanks again for your help!
