### ISSUE TITLE
feature request: support TTS/Tips/sound queue in one trigger

### ISSUE THREAD

**Issue by Trim21** [quisquous/cactbot#2502]
Currently, if user want to output multiple text though TTS, user will have to create multiple trigger with same condition and different delay.

```javascript
export default {
    triggers: [
        {
            id: 'trigger 1',
            regex: /patten/,
            delay: 1,
            infoText: 'tips 1',
        }, {
            id: 'trigger 2',
            regex: /patten/,
            delay: 2,
            infoText: 'tips 2',
        }, {
            id: 'trigger 3',
            regex: /patten/,
            delay: 3,
            infoText: 'tips 3',
        },
    ]
}
```

become something like this:

```JS
export default {
    triggers: [
        {
            id: 'trigger 1',
            regex: /patten/,
            infoText: () => [
                { delay: 1, text: 'tips 1' },
                { delay: 2, text: 'tips 2' },
                { delay: 3, text: 'tips 3' },
            ],
        },
    ]
}

```
or, add a TTS method on data, user can call data.TTS('something') in promise so that core part don't need to handle extra returned value from `*Text()`

```JS
function sleep(second) {
    return new Promise(resolve => setTimeout(resolve, second * 1000));
}
export default {
    triggers: [
        {
            id: 'trigger 1',
            regex: /patten/,
            run: function (data, matches) {
                (async (data, _) => {
                    await sleep(1)
                    await data.TTS("tips 1")
                    await sleep(1)
                    await data.TTS("tips 2")
                    await sleep(1)
                    await data.TTS("tips 3")
                })()
            }
        },
    ]
}

```

**Comment by Trim21** [comment]
current workaround:
```JS
function TTS (text) {
  const cmd = { 'call': 'cactbotSay', 'text': text }
  window.callOverlayHandler(cmd)
}
```

**Comment by quisquous** [comment]
Hmm.  I think I'd want to think about this a little bit more before implementing something like this.  Triggers are already pretty complicated, and this is something that is currently possible, but is just a little bit awkward and cumbersome.

I do think there are times where there is a collect/trigger/cleanup sort of pattern (when you need to wait to find 2 or more things, alert about them, and then clean up data afterwards) that all trigger on the same regex with different delays.  This pattern gets used a few times a tier and is kind of cumbersome but it's still possible.

On the other hand, I don't know that the tts delaying pattern is a particular use case I've seen a lot of.  What are you using this for, out of curiosity?

I think I wouldn't want to add just a "chain infotext/tts" and if this was a feature, it would be "chain this entire trigger to run after this other trigger".  That would allow for triggers to be implicitly consolidated in the back end (only one regex to check for all triggers that share the same regex).  But in that case, the chaining would really look about the same as your very first example, other than not needing to add the regex each time.  I'm not totally convinced that it adds enough functionality or ergonomics to be worth the extra complexity.

**Comment by valarnin** [comment]
I have a set of custom triggers that run into this limitation as well. I look at this as, functionally, two distinct use cases:

1. Triggers that need to execute a set of chained actions based on some sort of timing setup or other internal logic, all based on the same initial log line
2. Triggers that need to execute a set of chained actions based on expected future log lines

My set of custom triggers run into `1.` above. They're for e12s lions, calling out when and where to bait for line lions strat for my static.

`2.` above as an example could be the statue baits, or e12s p2 relativity mechanics.

If there's an equivalent of `Observable` in JS, a proposal to resolve these could be something like the following (could be split out into two separate properties if needed):
```js
        {
            id: 'trigger 1',
            regex: /pattern/,
            chain: (data, matches, output, continueObservable, logLineObservable) => {
                logLineObservable.then((line) => {
                    if (/someRegex/.matches(line))
                        continueObservable.next();
                });
                window.setTimeout(() => {
                    data.someVar = 1;
                    continueObservable.next();
                }, 1000);
                window.setTimeout(() => {
                    data.someVar = 2;
                    continueObservable.next();
                }, 1000);
                window.setTimeout(() => {
                    data.someVar = 3;
                    continueObservable.next();
                }, 1000);
            },
            infoText: (data) => 'tips ' + data.someVar,
        }
```

The accompanying changed code in `PopupText` would be relatively simple, functionally similar to the way `promise` is handled currently for the `continueObservable` property, and `logLineObservable` would need to be tracked and passed lines in some manner. The question mark with a setup like this is how to handle cleanup.

Another option would be some sort of event listener setup (since that's functionally what `Observable` is under the hood).

There are plenty of options, and I'm willing to code up whatever is decided on since it's useful for me, and send a PR for it.

**Comment by quisquous** [comment]
I think I would need to see a more solid use case here for any of these suggestions.  I'm not sure why relativities or statues or lions would be easier to do this way than some other way.  It feels like everything proposed is achievable with triggers as it is, and subjectively to me does not feel that cumbersome.  What is the downside of multiple triggers?  Do you want to show me an A vs B comparison where you feel like chaining creates a better abstraction?

I will add also that I am extra hesitant of imperative vs declarative forms here.  I think there are a lot of tests, emulator code, and ui that all deal with trigger objects as the core primitive, and anything that circumvents that to create trigger-like objects in code will be opaque to these systems.

**Comment by valarnin** [comment]
In the case of lions, it ends up being 5 extra triggers which means 5 extra regexes running on each log line. Not a problem for me because my computer is good but some people might struggle with slower comps.

**Comment by quisquous** [comment]
I guess I'm kind of surprised that it takes so many extra triggers.  Do you have a link?

If it's a performance issue vs an ergonomics issue, then I think that's a different discussion.  I think we could implicitly consolidate triggers that shared the same regex on the backend without changing the trigger format, so that you'd only match it once and then run several triggers in succession.  That doesn't add the same complexity to the raid emulator / the ui / the tests / etc as changing the trigger format does.

**Comment by valarnin** [comment]
Player names swapped out for privacy. It's actually 6 triggers, I wasn't counting the tether itself in the original calculation (1 + 5 extra).

```js
const getBaitText = (data, count) => {
  if (data.lionMarker)
    return 'Bait at ' + data.lionMarker;

  switch (count) {
  case 1:
  case 3:
    switch (data.me) {
    case 'Second Bait T/H North':
    case 'Second Bait T/H South':
    case 'Second Bait DPS North':
    case 'Second Bait DPS South':
      return 'West';
    case 'First/Third Bait T/H North':
    case 'First/Third Bait DPS North':
      return 'North';
    case 'First/Third Bait T/H South':
    case 'First/Third Bait DPS South':
      return 'South';
    }
    break;
  case 2:
    switch (data.me) {
    case 'First/Third Bait T/H North':
    case 'First/Third Bait DPS North':
    case 'First/Third Bait T/H South':
    case 'First/Third Bait DPS South':
      return 'West';
    case 'Second Bait T/H North':
    case 'Second Bait DPS North':
      return 'North';
    case 'Second Bait T/H South':
    case 'Second Bait DPS South':
      return 'South';
    }
    break;
  }
};
// ...
    {
      id: 'Custom - E12S Promise Small Lion Tether',
      netRegex: NetRegexes.tether({ source: 'Beastly Sculpture', id: '0011' }),
      netRegexDe: NetRegexes.tether({ source: 'Abbild Eines Löwen', id: '0011' }),
      netRegexFr: NetRegexes.tether({ source: 'Création Léonine', id: '0011' }),
      netRegexJa: NetRegexes.tether({ source: '創られた獅子', id: '0011' }),
      promise: async (data, matches) => {
        data.lionsblazeCount = 0;
        if (!Conditions.targetIsYou(data, matches))
          return;

        const id = parseInt(matches.sourceId, 16);
        const lionData = await window.callOverlayHandler({
          call: 'getCombatants',
          ids: [id],
        });

        if (lionData === null || !lionData.combatants || !lionData.combatants.length)
          return;

        data.lion = lionData.combatants[0];
      },
      // Don't collide with reach left/right call.
      delaySeconds: 0.5,
      durationSeconds: 32,
      infoText: (data, matches) => {
        if (!Conditions.targetIsYou()(data, matches))
          return;
        const x = Math.floor(data.lion.PosX);
        const y = Math.floor(data.lion.PosY);
        let marker = null;
        if (x <= 0) {
          if (y <= -75) {
            // Northwest lion
            marker = 'Marker 2';
          } else {
            // Southwest lion
            marker = 'Marker 3';
          }
        } else {
          if (y <= -75) {
            // Northeast lion
            marker = 'Marker 1';
          } else {
            // Southeast lion
            marker = 'Marker 4';
          }
        }
        data.lionMarker = marker;
        return marker;
      },
    },
    {
      id: 'Custom - E12S Promise Lionsblaze bait 1',
      netRegex: NetRegexes.ability({ source: 'Eden\'s Promise', id: '(?:58A[DE])' }),
      condition: (data, matches) => data.lionsblazeCount !== undefined && matches.target === '',
      delaySeconds: 0.8,
      durationSeconds: 4,
      alertText: (data) => {
        return getBaitText(data, 1);
      },
    },
    {
      id: 'Custom - E12S Promise Lionsblaze KB Imm',
      netRegex: NetRegexes.ability({ source: 'Eden\'s Promise', id: '(?:58A[DE])' }),
      condition: (data, matches) => data.lionsblazeCount !== undefined && matches.target === '',
      delaySeconds: 5.7,
      durationSeconds: 4,
      response: Responses.knockback('alert'),
    },
    {
      id: 'Custom - E12S Promise Lionsblaze bait 2',
      netRegex: NetRegexes.ability({ source: 'Eden\'s Promise', id: '(?:58A[DE])' }),
      condition: (data, matches) => data.lionsblazeCount !== undefined && matches.target === '',
      delaySeconds: 9.9,
      durationSeconds: 4,
      alertText: (data) => {
        return getBaitText(data, 2);
      },
    },
    {
      id: 'Custom - E12S Promise Lionsblaze release',
      netRegex: NetRegexes.ability({ source: 'Eden\'s Promise', id: '(?:58A[DE])' }),
      condition: (data, matches) => data.lionsblazeCount !== undefined && matches.target === '',
      delaySeconds: 15.1,
      durationSeconds: 4,
      alertText: (data, _, output) => {
        const text = getTetherString(data.stockedTethers, output);
        if (!text)
          return;
        if (!data.junctionSuffix)
          return text;
        return output.junctionSuffix({
          text: text,
          junction: output[data.junctionSuffix](),
        });
      },
      outputStrings: primalOutputStrings,
    },
    {
      id: 'Custom - E12S Promise Lionsblaze bait 3',
      netRegex: NetRegexes.ability({ source: 'Eden\'s Promise', id: '(?:58A[DE])' }),
      condition: (data, matches) => data.lionsblazeCount !== undefined && matches.target === '',
      delaySeconds: 21.2,
      durationSeconds: 4,
      alertText: (data) => {
        delete data.lionsblazeCount;
        return getBaitText(data, 3);
      },
    },
```

**Comment by quisquous** [comment]
Coming back to this much later, I still am not really convinced that combining multiple outputs into one trigger makes things conceptually simpler here.  I'm not sure that the e12s triggers are that much worse than combining them into a single trigger.  The extra trigger code would just be replaced with more lines in one trigger.

My concern here really is that creating triggers imperatively will just make testing, emulating, and config ui a lot more complicated.  My inclination here is to keep the trigger building blocks more conceptually simple even if that makes some constructions slightly more wordy because it keeps the whole system a lot simpler.

Also, as I said before, if this is a performance issue concern on regexes, we could collapse triggers with identical regexes in the backend and only match once for all of these triggers instead of matching every time.

If some example comes up where something like this would make something possible that wasn't possible before or creates a huge burden, I'm happy to rediscuss and reopen, but I am not convinced by the examples here that the complexity required to implement this feature is worth it.
