### ISSUE TITLE
bug： timeline Trigger can't modify data in raid emulator

### ISSUE THREAD

**Issue by Trim21** [quisquous/cactbot#2504]
## Description

I'm testing a set of triggers, and I found that timeline trigger can't modify data in any way. And `run`, `preRun` method are omitted. If I modify data in funxtion like `infoText` the modifition will be omitted.

## Additional information

log: 
[pure.log](https://github.com/quisquous/cactbot/files/6023557/pure.log)

trigger:
```JS
Options.Triggers.push({
  zoneId: ZoneId.TheEpicOfAlexanderUltimate,
  timelineTriggers: [
    {
      id: 'TEA 子言 时停阶段',
      regex: /Propeller Wind/,
      // delaySeconds: 20,
      infoText: (data, _, output) => {
        data.userPhase = 'Temporal Stasis';
// modify data here and it doesn't works,
// weather in `run(data)` or `preRun(data)` in later trigger infomation
// There's no such property or any other modification I made here
        console.log(data.userPhase); // output 'Temporal Stasis'
        return '提前进入时停阶段，反正中间也没啥东西'; // but this works fine and output correctly
      },
    },
  ],
});

```

**Comment by valarnin** [comment]
I've not had any issues with `data` modification in emulator. I think I need a bit more info to diagnose this.

To be clear, per https://github.com/quisquous/cactbot/blob/main/docs/RaidbossGuide.md#miscellaneous-trigger-info, if you make a change to `data` in `infoText`, it should be available in `run` but not in `preRun` due to the order of evaluation.

If this isn't the behavior you're seeing, I will need the exact trigger you're running that isn't working as expected as well as the log line that triggers it.

**Comment by Trim21** [comment]
I have uploaded the log and trigger.
This event happened at about 4:45.
In this case, I can see the info text, console.log, but in the debugging information about 5:00, there isn't such property `userPhase`

**Comment by valarnin** [comment]
This appears to be because you're using a timeline trigger which isn't currently tracked in raidemulator. It's on my todo list but I'll see if I can bump it up in priority.
