### ISSUE TITLE
Capturing the entity ID of the startsUsing source / target?

### ISSUE THREAD

**Issue by miaonima** [quisquous/cactbot#2575]
## Question

What would you like to ask?
I would like to implement triggers for e11s Prismatic Deception. There are several images shown in ACT log, and the key is to know the ID of the image that is actually casting. Here is a working trigger condition for this scenario as implemented in Triggernometry:

${_ffxiventity[${func:format(System.Int32,"X"):${numeric:hex2dec(${id})-1}}].**casttargetid** (NOT EQUALS “0”) 

NetRegexes.startsUsing seems to give names only, but not ID's. This is not enough to distinguish between the images because they have the same name.
`await window.callOverlayHandler( call: "getCombatants", names: [...] )` gives all possible ID but does not give cast bar information. Any suggestions?

**Comment by quisquous** [comment]
(See also #2329.  I think this is something that I don't want to add to cactbot proper because it feels a little bit over the line for me as something you couldn't figure out directly.  It'd be better for a user trigger or something "unofficial", if that makes sense.)

`NetRegexes.startsUsing` has a `sourceId` field: https://github.com/quisquous/cactbot/blob/main/resources/netregexes.ts#L115

You'll need to do a getCombatants to get the entity locations during startsUsing.

**Comment by miaonima** [comment]
Got it. Just started practicing writing/debugging a trigger. Thanks for your help!
