### ISSUE TITLE
raidboss regular expressions

### ISSUE THREAD

**Issue by red-perilla** [quisquous/cactbot#267]
The raidboss files such as o9s.js includes regular expressions such as:

regex: / 14:3170:Chaos starts using Chaotic Dispersion on (\y{Name})/,

However, my ACT log shows this line

00|2018-10-23T19:34:52.0000000-05:00|282b||Chaos readies Chaotic Dispersion.|80b0f1e52ff05545af5232798de439ee

Note that the log says "readies", while the regular expression looks for "starts using". Also the log does not have the "on <name>" portion. I'm using the North America client.

Why the discrepancy and is it why my raidboss isn't working? How does the o9s.js work for others?

**Comment by red-perilla** [comment]
That explains a lot. Thank you for clarifying. Is there a discussion group where I can find this kind of information?

**Comment by quisquous** [comment]
Cactbot has its own API in terms of writing triggers, but the regex that it's matching on comes directly from the encounter log.  It's not doing anything special there.

The lines you're looking at (e.g. opening up your Network_date.log file) would be something like:
```
20|2018-10-23T20:03:12.2990000-07:00|4000C836|Chaos|3170|Chaotic Dispersion|1048638C|Tini Poutini||9eb86bb01aa878c666c86e1b2d5b98bf
00|2018-10-23T20:03:11.0000000-07:00|282b||Chaos readies Chaotic Dispersion.|bce10bbac28bbf2436a32ea14613f0e0
21|2018-10-23T20:03:17.2950000-07:00|4000C836|Chaos|3170|Chaotic Dispersion|1048638C|Tini Poutini|730003|26A24801|E80F|2B70000|1C|31708000|0|0|0|0|0|0|0|0|0|0|46321|76138|4560|4560|880|1000|99.65981|95.5883|0|16190780|19751250|12000|12000|1000|1000|99.47351|100.0839|0||8eaf88474ed5069aedcdce159e213e2c
00|2018-10-23T20:03:17.0000000-07:00|282b||Chaos uses Chaotic Dispersion.|58e282fa0ee4a4c9304b7ef5ec7ca15c
```

If you go to an ACT encounter, right click, and look at "View Logs", you can see the encounter log.  The FFXIV plugin parses the network lines and then generates the more readable encounter lines.  This is what cactbot is parsing against.  The equivalent lines will look something like:
```
[20:03:12.299] 14:3170:Chaos starts using Chaotic Dispersion on Tini Poutini.
[20:03:11.000] 00:282b:Chaos readies Chaotic Dispersion.
[20:03:17.295] 15:4000C836:Chaos:3170:Chaotic Dispersion:1048638C:Tini Poutini:730003:26A24801:E80F:2B70000:1C:31708000:0:0:0:0:0:0:0:0:0:0:46321:76138:4560:4560:880:1000:99.65981:95.5883:0:16190780:19751250:12000:12000:1000:1000:99.47351:100.0839:0:
[20:03:17.000] 00:282b:Chaos uses Chaotic Dispersion.
```

The encounter lines that start with `00:` (e.g. readies, uses) are all battle log lines.  These match up with the network lines that begin with `00|`.  You'll see these lines in game.

The encounter lines that start with `14:` (e.g. starts using an ability) or `15:` (single target attack) are parsed versions of the network log line.  These are the same as the `20|` and `21|` lines.  One is value is hex, the other is decimal (https://www.google.com/search?q=0x14+in+decimal).  Some of these lines get some extra text for readability, like the `14:` line becomes "starts using" but the `15:` line is much closer to the network line.  Here's a little info on different message types: https://github.com/quisquous/cactbot/blob/master/ui/oopsyraidsy/oopsyraidsy.js#L125

The reason cactbot uses the parsed network log lines (`14:`) instead of the battle log lines (`00:`) is because they show up faster.  Also the battle log lines don't show up sometimes, so don't seem as reliable.  Also, they contain more information, like who the ability is targeting or how long the effect is.

There's not really a discussion group.  Probably the fflogs discord (https://www.fflogs.com/home/discord/) #act-stuff channel is the closest thing.

**Comment by quisquous** [comment]
Also, if your raidboss isn't working and you're only seeing the `00|` lines, then you are not parsing network log lines.  Maybe your firewall isn't configured right or you're not running as admin.  Or, possibly the "Parse Mode" in your ACT -> Plugins -> FFXIV Settings tab is not set to "Network".  (You can click "test game connection" on that tab.)

**Comment by red-perilla** [comment]
Thank you for the detailed explanation. Cactbot is working now. I guess the problem was somehow I gote multiple Cactbot defined in the OverlayPlugin.dll tab. May be because I had updated Cactbot.
