### ISSUE TITLE
Spoken alerts through Discord

### ISSUE THREAD

**Issue by red-perilla** [quisquous/cactbot#271]
Is it possible to have the spoken alerts go to either my headset, and/or Discord? There is an ACT bot for Discord, but it seems intended to the built-in triggers, not Cactbot.

**Comment by Cerily** [comment]
There's a plugin for act that uses slimdx to allow you to send all ACT audio to any sound device you have.  It works for every sound ACT generates and can be used as the mic input in discord when used along with VB-Audio virtual cable software.  Can find a write up on how to set up both searching google with the phrase slimdx_xaudio2 plugin act.

**Comment by quisquous** [comment]
I think the comments in #120 are probably going to be the best place to look.  Due to the version of Chrome that CEF uses (which can't be updated due to Chrome bugs that still haven't been fixed), there's no support for choosing the media device.  So, I can't make cactbot do anything here.  You have to reroute the audio externally, either through Windows or through some other software.
