### ISSUE TITLE
Pyros Map Not Working

### ISSUE THREAD

**Issue by illhatjr28** [quisquous/cactbot#277]
As noted above, I have zoned into both Anemos and Pago's and both maps work correctly. But for some reason after re-downloading cactbot with the new additions of Pyro's it is not giving me the new map nor pings when NMs pop. Am I updating the files incorrectly? Any help would be appreciated

**Comment by TheTweets** [comment]
There has not been a release that has included a Pyros map to my knowledge (the latest I see is 0.8.6 from before Pyros' release), so you will not get a map, NM notifications, or weather timer for that zone. 

As far as a map not appearing, NM notifications etc not occurring in Pagos, it is likely you have not Unblocked the .zip file that includes the release before installing it. If you have a known working backup restore that and do this to double-check, otherwise remove Cactbot entirely and re-install to check. 

If this isn't what's happening, could you go into some more depth as to what you're doing (specific steps, potentially with pictures)? 

I'm no coder so I can't speak to that, but I've made this mistake so many times I know how easy it is to forget, and as 0.8.6 is functioning for me in Anemos and Pagos (the supported zones) with exception of the weather tracker, I don't see it being an issue with the release.

**Comment by illhatjr28** [comment]
No everything in pago's and anemos works perfectly. I simply saw "updates in pyro's" on certain files and just assumed that map was added. Thanks for responding.

**Comment by TheTweets** [comment]
Looking at the main repo I can see a few additions roughly a week ago to this effect, but it appears to be rudimentary and very much a work-in-progress (from what I can ascertain it appears that it has been made to understand when the player is in Pyros, but has not yet been equipped with a map to display, and not yet been given any NM info either). 

As a layman, I find my best bet is to watch the [Releases](https://github.com/quisquous/cactbot/releases) exclusively, and typically leave the actual code a wide berth so as not to confuse myself!

**Comment by quisquous** [comment]
Sorry!  I've been out of town for a week.  I should have a Pyros update this weekend once I figure out why all the Eureka weather is broken.

**Comment by quisquous** [comment]
Fixed now.  It'll be in the next release.
