### ISSUE TITLE
Browser TTS stopped working

### ISSUE THREAD

**Issue by godman59** [quisquous/cactbot#2860]
#2860 
So for the past few days sound aletrs on my cactbot stopped working, not  sure why but probably because the last ACT update 29.04? Tried reinstalling the plugin, setting up the raidboss anew, but nothing seems to work. Any suggestions?

EDIT: I'll add that non browser TTS works, though I'm mildly happy about it, as its weird to hear english phrases in my native tongue and for some reason I can't change system tts.  

EDIT2: I've also tried turning the instance check, but it still didn't help. 
Errors I'm getting
[5/14/2021 6:32:46 PM] Info: TTS: BrowserConsole: Uncaught (in promise) NotSupportedError: Failed to load because no supported source was found. (Source: about:blank, Line: 0)

**Comment by panicstevenson** [comment]
I'm a little perplexed by this, since there is another open issue on (what I assume to be) the same issue: https://github.com/quisquous/cactbot/issues/2858.
However, there hasn't been a cactbot release in 16 days, a FFXIV ACT Plugin release in 17 days, or an OverlayPlugin release in 28 days. I don't see any relevant pull requests that have touched this code recently that would impact this area if you were pointing to the GitHub URL.
I have tried using my local files, building the repository locally, and using the upstream GitHub URL and I cannot reproduce this with any variation, with any language. Would you mind sharing more information about what you're running that is giving you this error?

**Comment by godman59** [comment]
I don't really have anything running except this and a dps overlay, both of them in pretty much default state as I'm not really too advanced in this stuff, but it worked fine for over a year. 
To add salt to a wound, right now it's using polish system speech which really butchers english phrases to the point that I stopped understanding them. I uninstalled polish localization from my PC, changed speech language, changed even a region to the US, but it still somehow is using polish TTS. Any idea what is causing that?

**Comment by godman59** [comment]
I think there was an update today regarding this issue? Haven't read it carefully, because I was in the middle of a dungeon, but I think I did catch a glimpse of the issue number. Still doesn't work though.

**Comment by panicstevenson** [comment]
I don't see reference to this issue in the [latest release](https://github.com/quisquous/cactbot/releases/tag/v0.22.4), and I'm also not entirely sure what the best course of action here is. I can almost guarantee that with the error log you're getting that something is going wrong with the Google TTS API, but last time there was an issue there was a lot of people discussing it being broken. This time, there's just the two issues on here; not to say it's less significant, but it's a lot harder to pinpoint what is going on. What language are you running cactbot in, how do you have cactbot installed, are you in the United States?

**Comment by godman59** [comment]
No, I'm in Poland and the system was originally installed in Polish, thats why it is using now system TTS. I tried changing it to english, installed US english language pack for keyboard and speech, changed even region to US and deleted polish language packs but it stil somehow is using polish instead of english system TTS (even though they are not available to choose in system options).

**Comment by panicstevenson** [comment]
Quick heads up here: I finally got hit by this issue. When trying to play the TTS iframe, we get a response back `net::ERR_BLOCKED_BY_RESPONSE`. It looks as though Google is rolling out a `x-frame-options: SAMEORIGIN` header for all the responses to this API; if you're able to, you can try going to a URL like https://translate.google.com/translate_tts?q=Stack&tl=en&client=tw-ob, which is "Stack" in English, using the well-known hack to reach this API, despite it not being public. If you're lucky, this might sound like the voice you're familiar with, which won't have the new x-frame-option applied. However, it might sound different when you open the URL, and the slightly different voice will have this option applied.

I was lucky enough (I don't use TTS at all, so I don't mind) that this happened to my cactbot instance while testing, and I was able to look at this in the browser and see my normal browser behave as I would expect and my incognito behave in a way that I would expect to now have errors.

What does this mean? Well, unless Google decides to undo this change (unlikely -- they have a Google Cloud API for TTS, and people have been using this unofficial API for decades for free), I don't think there's much of a way around this. I attempted to stop using an iframe, instead using an <audio> tag, but to make that work the `rel` attribute needs to be "noreferrer", which apparently causes the request to return with a 404 Not Found altogether. It's possible that there's some clever way around this and maybe if enough people get affected someone on the internet will find a workaround, but that will only live for however long before getting patched as well, since ultimately this is a hack.

**Comment by SiliconExarch** [comment]
> Quick heads up here: I finally got hit by this issue. When trying to play the TTS iframe, we get a response back `net::ERR_BLOCKED_BY_RESPONSE`. It looks as though Google is rolling out a `x-frame-options: SAMEORIGIN` header for all the responses to this API; if you're able to, you can try going to a URL like https://translate.google.com/translate_tts?q=Stack&tl=en&client=tw-ob, which is "Stack" in English, using the well-known hack to reach this API, despite it not being public. If you're lucky, this might sound like the voice you're familiar with, which won't have the new x-frame-option applied. However, it might sound different when you open the URL, and the slightly different voice will have this option applied.
> 
> I was lucky enough (I don't use TTS at all, so I don't mind) that this happened to my cactbot instance while testing, and I was able to look at this in the browser and see my normal browser behave as I would expect and my incognito behave in a way that I would expect to now have errors.
> 
> What does this mean? Well, unless Google decides to undo this change (unlikely -- they have a Google Cloud API for TTS, and people have been using this unofficial API for over a decade for free), I don't think there's much of a way around this. I attempted to stop using an iframe, instead using an <audio> tag, but to make that work the `rel` attribute needs to be "noreferrer", which apparently causes the request to return with a 404 Not Found altogether. It's possible that there's some clever way around this and maybe if enough people get affected someone on the internet will find a workaround, but that will only live for however long before getting patched as well, since ultimately this is a hack.

Can you elaborate on how you replaced the iframe with an audio tag? I'm trying to do this myself and it seems to work if I add `<meta name="referrer" content="no- referrer" />` to raidboss.html but when I do the test at Summerford it works fine for the first run then it just repeats the last phrase over and over on subsequent runs.

**Comment by panicstevenson** [comment]
> Can you elaborate on how you replaced the iframe with an audio tag? I'm trying to do this myself and it seems to work if I add `<meta name="referrer" content="no- referrer" />` to raidboss.html but when I do the test at Summerford it works fine for the first run then it just repeats the last phrase over and over on subsequent runs.

```ts
class GoogleTTSItem implements TTSItem {
  readonly text: string;
  readonly lang: string;
  private item: HTMLAudioElement | null = null;

  constructor(text: string, lang: string) {
    this.text = text;
    this.lang = lang;
    const audio = document.createElement('audio');
    audio.src = `https://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&tl=${lang}&q=${encodeURIComponent(text)}`;
    document.body.appendChild(audio);
  }

  play() {
    void this.item?.play();
  }
}
```
With your suggestion it still does not work for me; maybe I missed something here?

**Comment by SiliconExarch** [comment]
Hmm, maybe try this? 

```
class GoogleTTSItem implements TTSItem {
  readonly text: string;
  readonly lang: string;
  private item: HTMLAudioElement | null = null;

  constructor(text: string, lang: string) {
    this.text = text;
    this.lang = lang;
    const audio = document.createElement('audio');
    audio.src = `https://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&tl=${lang}&q=${encodeURIComponent(text)}`;
    document.body.appendChild(audio);
    **this.item = audio;**
  }

  play() {
    void this.item?.play();
  }
}
```

**Comment by panicstevenson** [comment]
> Hmm, maybe try this?

Sorry, that's my mistake on my most recent attempt to revert, apply the browser TTS changes, and reply. I had originally had that in my first pass at testing this. Including the assignment, it still does not work for me. For verbosity, I am adding `<meta name="referrer" content="no-referrer" />` underneath the existing meta line within `raidboss.html` and replacing `this.options.BrowserTTS` in `popup-text.js` with `true`.

**Comment by SiliconExarch** [comment]
Here's what I've got https://github.com/SiliconExarch/cactbot/commits/browser_tts 

The only other thing I did myself after adding the meta line is clear the OverlayPluginCache folder and it seems to be working consistently now.

**Comment by panicstevenson** [comment]
Yep, that should be identical to what I have, as far as outcomes go. `browser_tts_engine.ts` is literally identical. I am not building the plugin myself, but that shouldn't matter since nothing was changed on the plugin side. I'm overriding the option to always be true, and I get `net::ERR_BLOCKED_BY_RESPONSE` for each alert that pops up with your method (same for the old iframe code).

Were you ever actually broken by this change, or were you only affected by the feature being removed entirely? A good way to tell would be if the voice changed. See https://github.com/zlargon/google-tts issue 52 (purposely avoiding linking), but it looks like other users are noting that the new changes have a slightly different voice, as I mentioned above.

**Comment by SiliconExarch** [comment]
It had been working perfectly up until a couple of days before the feature was removed. I noticed it started missing the odd word, then after I initially patched the iframe code back in I was getting `net::ERR_BLOCKED_BY_RESPONSE` every time, until I experimented with adding a random value to the end of the URL, which also seemed to fix the issue but I decided I'd rather ditch the iframes if possible.

**Comment by panicstevenson** [comment]
Just to follow up here, I added your fork as a remote to my local repository, swapped to your browser_tts branch and followed the steps you provided. However, I still only see `net::ERR_BLOCKED_BY_RESPONSE`. I even went further to add a random field to the audio url params, still no luck. I went back and reverted to the iframe implementation with a random value at the end of the url there as well, no luck. Lastly, I went back again and did all the steps again without the meta tag; still no luck, but 404s instead off the blocked by response error for the audio implementation.

My user-agent is: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36`, so I'm unsure if maybe there's potentially a difference there. Otherwise, I'm not sure what (if anything) I am doing wrong to be getting different results.

**Comment by SiliconExarch** [comment]
The old implementation finally broke completely for me a couple of days ago so I made a new one using the node package panicstevenson referred to above with the caveat that I have to build my own OverlayPlugin with web security disabled. I don't recommend this for obvious reasons, but it does work reliably and I'm happy to take the risk personally as cactbot is the only overlay I use. I already linked the branch above if anyone is interested but I won't provide instructions on disabling web security in OverlayPlugin, you'll have to evaluate the risks and figure that out for yourself.
