### ISSUE TITLE
e9s some triggers are not working after recent update

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [quisquous/cactbot#2995]
## Description

Those triggers alerted after these triggers below are not working.
E9S The Second Art Of Darkness Right
E9S The Second Art Of Darkness Left
E9S The Third Art Of Darkness Right
E9S The Third Art Of Darkness Left

I guess these trigger `E9S The Second / Third Art Of Darkness Charge Solver` and `E9S The Second / Third Art Of Darkness Callout` are not working.

Don't know if this happens on KR server only. I heard other person also had this problem.

I've checked tuesday working well. This happened after the recent update.

**Comment by panicstevenson** [comment]
> I've checked tuesday working well. This happened after the recent update.

This is "Final Fantasy XIV update," correct? Not "cactbot update"? Not that the recent swaths of refactoring are infallible, but I don't see anything substantial that changed in the cactbot code with respect to those triggers; however, the code for those triggers hinges upon [some assumptions](https://github.com/quisquous/cactbot/blob/main/ui/raidboss/data/05-shb/raid/e9s.js#L476-L505) about the flow of the fight. What's interesting here is I feel like I wrote this code to be fairly generic; we know the first sweep based off abilityId and we simply increment from there. My fear here would be that each headMarker has been randomized individually instead of having a randomized offset. The flip side is maybe headMarkers were silently patched in one of the downstream dependencies to take account of the offset? That feels unlikely though, and I would expect this code to still work in the event that all the headMarkers were shifted by the same number.

Do you have a network log you would be able to share? I also am worried about TEA if the offset is [no longer one value per instance](https://github.com/quisquous/cactbot/blob/main/ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.js#L33-L47).

**Comment by Jaehyuk-Lee** [comment]
ah, there wasn't game client update this week on Korean server. You might confused it because SQEX server was updated.

**Comment by panicstevenson** [comment]
Nevermind, looks like @valarnin found it: https://github.com/quisquous/cactbot/issues/2995
I didn't realize that https://github.com/quisquous/cactbot/commit/ae3c263feac53003698504356be6ce8821d4a833 had only just been committed this last patch

**Comment by valarnin** [comment]
Was about to link that PR when I noticed this issue but panic beat me to it :)

**Comment by valarnin** [comment]
Please test all the listed triggers though, I'm not sure if my PR fixes everything, I just noticed the debug output in console when testing raidemulator changes.

**Comment by Jaehyuk-Lee** [comment]
umm I had only `Second Art Of Darkness` and `Third Art Of Darkness` problem.
I don't know the other zone, I only tested on e9s.

**Comment by valarnin** [comment]
Both Second and Third art triggers use a collector -> callout pattern, so they were probably both impacted by the same issue, but the only e9s log I have handy is in chinese which I can't speak/read so I can't actually verify that this fixes everything.

**Comment by Jaehyuk-Lee** [comment]
I didn't have any other reports on Korean community, so I guess that's all.

**Comment by panicstevenson** [comment]
I think the question would be if the [Phaser](https://www.youtube.com/watch?v=mkJrBNeu-PU) callouts worked, but I think they do. I remember when that PR was first opened that I went to confirm the ordering of array shifting returning and making sure nothing broke there. But, I apparently missed the missing `const` in my review.

**Comment by Jaehyuk-Lee** [comment]
Phaser worked.
