### ISSUE TITLE
function as `trigger.enabled`

### ISSUE THREAD

**Issue by Trim21** [quisquous/cactbot#3103]
many triggers' condition (like `care about magic`) are consistent in the whole battle, so there is no need to match regex then check if it fit the condition.

When we are loading a trigger, check it it's enabled with basic data properties like job, role.

then we could have something like this:
 
```diff
--- a/ui/raidboss/data/05-shb/eureka/delubrum_reginae.js
+++ b/ui/raidboss/data/05-shb/eureka/delubrum_reginae.js
@@ -33,7 +33,7 @@ export default {
       netRegexCn: NetRegexes.startsUsing({ source: '求道之三位一体', id: '5AB6', capture: false }),
-      condition: Conditions.caresAboutAOE(),
+      enabled: Conditions.caresAboutAOE(),
       response: Responses.aoe(),
     },
     {
@@ -658,7 +658,7 @@ export default {
       netRegexCn: NetRegexes.startsUsing({ source: '女王战士', id: '5800', capture: false }),
-      condition: Conditions.caresAboutAOE(),
+      enabled: Conditions.caresAboutAOE(),
       response: Responses.aoe(),
     },
     {

```

**Comment by Trim21** [comment]
a litter bit more discussion:

- But doesn't it cause performance issues? Since you have to iterate the huge trigger set array on every time you changed your job.

save references of triggers with function as `enabled` in a new container.
Triggers that could know if itself is enabled isn't that much I think.  We only need to check them on job change.

**Comment by quisquous** [comment]
I think I'd be interested in understanding if there were reports of performance problems and if there were, then some measurements of what's slow so we could direct what the fix was.

I agree with you that this could be more efficient, but my priority is simplicity >>> efficiency.  In other words, only make things more complicated if it's solving a problem directly and don't add complexity to solve theoretical problems.

**Comment by panicstevenson** [comment]
I'll say that I like this idea a lot; I think that performance, in general, is probably not the biggest concern here and that there's probably easier wins in other areas of the code, BUT I really like this concept.

I wonder if we could find a way to pre-process all of the triggers on TimelineReload to see if they have simple conditions that can already be met (such as no calls to `matches` and everything within the `data` they expect exists). This would help the runtime in the same way I think you've listed here, although it might add some complexity in timeline/popup-text, which I think people generally consider to be inaccessible? Or, at least, I see far fewer pull requests in that area of the code. What do you think about tackling this in another way that leaves the end-user's interface unchanged?

**Comment by Trim21** [comment]
This just extend `enabled` property , user didn't need to change their code for this change.

**Comment by valarnin** [comment]
I'd be more for implementing this as a new trigger property than trying to extend an existing property to fit this as well.

Something like:

```typescript
type PreConditionFunc = (data) => boolean;
// On BaseTrigger...
  preCondition?: PreConditionFunc;
// On a trigger...
{
  id: 'something',
  preCondition: Conditions.caresAboutAOE(),
}
```

Order of operations would be:

1. Check `disabled`
2. Check `preCondition`
3. do `preRun`
4. As normal from here on out

This can be implemented in `PopupText`'s `OnLog` and `OnNetLog` via something like:

```typescript
  OnNetLog(e: EventResponses['LogLine']): void {
    const log = e.rawLine;
    // This could conceivably be determined based on `new Date(e.line[1])` as well, but
    // not sure if that's worth the effort
    const currentTime = +new Date();
    for (const trigger of this.netTriggers) {
      if (trigger.preCondition && !trigger.preCondition(this.data))
        continue;
      const r = trigger.localNetRegex?.exec(log);
      if (r)
        this.OnTrigger(trigger, r, currentTime);
    }
  }
```

**Comment by quisquous** [comment]
> For user interface, this just extend `enabled` property , user or we didn't need to change existed code for this change.

I think there is also complexity in `popup-text.js`.  Having to handle an additional property and think about cases where we need to reload where previously we didn't need to reload is just extra complexity.  If nobody will ever notice the performance improvement, then I think it's better to have the code be as simple as possible (to prevent bugs in the future, reduce the amount of features we have to support, reduce the cognitive load to understand the entire system).

If you're interested in raidboss performance, I would be interested in performance numbers to motivate making changes.  Personally, I don't see performance issues myself and haven't heard of people complaining about cactbot being slow.  On the other hand, I do feel like cactbot is pretty complicated (especially raidboss!) and so I am much more interested in making it simpler (or keeping it simpler).

If regexes are the problem, then numbers that would be help convince me are:
* how many log lines per second does cactbot handle (mean/median/percentiles) in practice
* pick 2-3 fights that have a lot of triggers (zadnor? an ultimate? e12s?) and run some tests to say "how long does it take to regex match an entire fight"

Once we have those two numbers, we can ask "is it worth doing some performance improvements" and "if it is worth it, how much do things improve when we make some specific change"? It might not even be the case that regexes are the biggest issue.  It's possible that time spent in regexes is small compared to time spent in Chrome internals and so the best performance win is to fix up CSS to reduce rendering time.  Or maybe OverlayPlugin's time spent generating DPS information is much huger than any time spent in raidboss and so that would be a much better thing to fix.  It's not clear to me at all where time is being spent and what proportion of time is being spent in various parts of the system.

Sorry to be negative here, but what I'm trying to get is that I would like to avoid optimizations where we assume we know what the problem is and add performance fixes without measuring and end up adding complexity with no benefit.

**Comment by quisquous** [comment]
I still am iffy about this feature without any additional numbers to show if it's worth it or not.  Feel free to reopen if you have some examples of performance problems where adding this feature would help.
