### ISSUE TITLE
Skin doesn't show .alarm-text on top

### ISSUE THREAD

**Issue by PickleTicklewithnospace** [quisquous/cactbot#318]
I noticed the Death to ____ trigger with the test timeline shows the "DEATH" text under the timeline boxes. Works fine without the skin though.

**Comment by quisquous** [comment]
Thanks for this.  I'll take a look when I get a chance.

**Comment by DrLippe** [comment]
I was not able to reproduce this bug.
Does this bug apply to all alarm text messages or is it exclusive to the test triggers?

Copying the original `raidboss.css` shouldn't have any effect since `raidboss.css` is always loaded no matter what skin is in use. `lippe.css` does extend/override parts of `raidboss.css`. 🤔

**Comment by DrLippe** [comment]
So the actual problem is popup-text having a smaller z-index than the timeline-text?
In my understanding this is working as intended and nothing unique to this skin? 😕
