### ISSUE TITLE
Bot used to speak but doesn’t since 0.9.0

### ISSUE THREAD

**Issue by Enyalios121** [quisquous/cactbot#321]
As the title suggests, after patch 0.9.0 the TTS stopped working. The mechanics are still coming up in text and I’m getting a ping when they’re happening but no longer does it speak. Any tips?

**Comment by DamienRamirez** [comment]
Have you tried: https://github.com/quisquous/cactbot/blob/master/AdvancedCactbot.md#configuring-ui-modules Text To Speech section? 
This said i have noticed a few that are not working with it enabled Specificly: The Ridorana Lighthouse

**Comment by torchick11** [comment]
I'm noticing this as well, most things in o12s were voiced and now they're all just pings

**Comment by Enyalios121** [comment]
I have tried that yes, no joy

**Comment by quisquous** [comment]
Do you have any errors in your plugin log?

(Sorry for being slow to respond here.  I'm trying to finish off Seiryu and Orbonne stuff, so haven't had a chance to investigate bugs.)

**Comment by Enyalios121** [comment]
That’s no problem, that 24 man is painful at times. Casual hell lol.

I’ve done a full reinstall and my raid is tonight. I shall test and see if that fixed it. I’ll keep you updated

**Comment by DamienRamirez** [comment]
Only error i've seenso far i'm certain is due to being on Blue Mage (unknown job role - ) but i'll update if anything pops up.
Info: Ratholos EX: BrowserConsole: Unknown job role (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 164)

**Comment by DamienRamirez** [comment]
Just to update At least for my issue, I had unticked (or it wasnt ticked when i reinstalled cactbot/overlay) "Send Log Updates" ticked that & its working again, Also updated to new one, tested & thats working.

**Comment by Enyalios121** [comment]
Mine did not work after reinstall. So I’m currently lost as how to fix it

**Comment by Enyalios121** [comment]
So my act now says there’s a newer version of cactbot available. I have downloaded the new version several times

**Comment by DamienRamirez** [comment]
I want to help you Enyalios but i feel like your issue is something obvious like not running as Admin or the same thing i has "send log updates" was unchecked.
But if you're lost best place is to start fresh, you know ACT + FFXIV plug in works so leave that alone & just delete the overlayplug-in folder that has both overlay+cactbot. Then: https://github.com/quisquous/cactbot Follow this, get overlay + cactbot again, unblock when downloaded (Very Important!) merge folders, e.t.c. as it says to do. Then when all is said & done check the boxes in the overlayplugin tab that need to be checked, set dps invertal to 0, set bossraid .html  e.t.c. & see if it works.

**Comment by Enyalios121** [comment]
All of this I have done. I’ve always ran as admin, the parsing itself works too. Everything is working as intended just not the spoken part it’s so bizarre. Like you suggest I think I’ll delete the whole thing and start from scratch.

**Comment by Enyalios121** [comment]
I appreciate the responses btw. I’ll clean my hard drive of act and start fresh. See if it fixes the problem

**Comment by Enyalios121** [comment]
To keep you informed, I don’t understand how or why. I uninstalled the whole lot. A friend sent me their act file zipped. I simply unblocked, unzipped, replaced the cactbot with the new 0.9.1. Changed the text file to “true” and bam. Working. I’m baffled because it’s bordeline a direct copy of what I had before. Sooo yeah, how and why it’s fixed is beyond me but it’s fixed so thank you for your time

**Comment by quisquous** [comment]
Glad you got it sorted out.  My guess is that something went awry with your **cactbot/user/raidboss.js** file, and the option to turn on tts wasn't happening.  If everything else is working, then your install of cactbot was probably fine.  If just tts isn't working, then it's probably something in the user overrides.  Thanks for the update that you got it working!
