### ISSUE TITLE
Improve make_timeline.py

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#322]
util/make_timeline.py is super useful for making timelines, but a few things that could be improved.

(1) delete abilities with the same name at the same time (or within <0.25 or some tolerance) to avoid spamming.
(2) if an ability has no name, label it --sync-- instead of blank
(3) handle overlapping syncs.  By default, everything without a window looks 2.5 seconds behind and 2.5 seconds ahead.  If there's an ability that triggers every second repeatedly (multiple explosions, etc), then the timeline will have multiple lines whose syncs overlap with each other.  I think in these cases, the syncs should be commented out and maybe a `#collision` comment added.

If anybody wants to contribute some small fixes, these sorts of things would be super appreciated! <3

**Comment by quisquous** [comment]
* look up unknown abilities from xivapi
* have test_timeline.py find and auto-test against N fflogs fights so you don't have to specify them all individually
* have test_timeline.py auto-test against N fights and be able to print out average deviation of when things happen (and then be able to adjust the timeline to match them?)

**Comment by quisquous** [comment]
* if a parameter is valid for make_timeline but not test_timeline (or vice versa) allow those parameters to silently (or with a warning?) be ignored, rather than not running at all (so that you can switch from make to test and vice versa without having to edit the command line)

**Comment by JLGarber** [comment]
Any chance you would be willing to turn all this into a checklist? (Or, if you like, I guess I could open a new and more generic issue to cover all the timeline stuff.) I'll probably look at more of this in a month or so after I finish Heavensward's dungeons out. 

I think it might also be worth folding some of `check_translation`'s functionality into `translate_fight`, maybe expanding that a little in some way, and writing up some documentation on it (maybe similar to what I did for documenting trigger construction?) I know for me right now the translations are a bit of a pain because there's no built-in functionality to arrange/format them as I prefer, so there's a decent bit of (admittedly *technically* unnecessary) effort there.

And then I guess maybe a first-pass naive auto-generation of Oopsy files via a scan through the log for `E0000000::`?

**Comment by quisquous** [comment]
- [ ] delete abilities with the same name at the same time (or within <0.25 or some tolerance) to avoid spamming.
- [ ] handle overlapping syncs. By default, everything without a window looks 2.5 seconds behind and 2.5 seconds ahead. If there's an ability that triggers every second repeatedly (multiple explosions, etc), then the timeline will have multiple lines whose syncs overlap with each other. I think in these cases, the syncs should be commented out and maybe a #collision comment added.
- [ ] look up unknown abilities from xivapi
- [ ] if a parameter is valid for make_timeline but not test_timeline (or vice versa) allow those parameters to silently (or with a warning?) be ignored, rather than not running at all (so that you can switch from make to test and vice versa without having to edit the command line)
- [ ] `-lf` should be able to autopick the zone and find the timeline without passing `-t` when using test_timeline
- [ ] have test_timeline.py find and auto-test against N fflogs fights so you don't have to specify them all individually
- [ ] have test_timeline.py auto-test against N fights and be able to print out average deviation of when things happen (and then be able to adjust the timeline to match them?)

**Comment by JLGarber** [comment]
Ooh, thanks. I'd forgotten about "unknown lookup from XIVAPI", that might affect what I'm doing with the translation tools right now, so definitely something to think about.

On auto-selecting the timeline for `test_timeline`, that's probably doable but would require a bit of restructuring. Currently, the script has no way of "knowing" which instance an encounter takes place in at any given pair of timestamps. Further, because `-lf` is simply looking for any ability to start the encounter, there's no good way to say "this line tells you which timeline to use". Off the top of my head, I'm seeing the algorithm working sort of like this:

```
encounter_start = zone_seal_or_attack_line
if encounter_start is zone_seal:
    search_timelines_for_zone_seal(zone_seal)
else search_timelines_for_attacker_NPC(attack_line)
```

That's probably not the best way to go about it, but given that there is no standard convention on how to name timeline/trigger files, I don't see a way to avoid reading through the `raidboss` directory to find the start line if we do something like this.

The other option is to build a map of instance/filename pairings and keep it updated. Then we could just have `-lf` silently include the instance name when an encounter is specified, look it up from the map, and select the timeline file from there. It would be more manual work to update this every patch, but it would save time iterating through the `raidboss` folder to find the appropriate timeline every time the script is called. (The other other option here would be to save state across calls, but that's well beyond what I'm able to do.)

**Comment by quisquous** [comment]
I think many of these have been done at this point, so I'm going to close this issue.
