### ISSUE TITLE
Emulator worker.js is named as `379.bundle.js` in gh-pages branch

### ISSUE THREAD

**Issue by trim21** [quisquous/cactbot#3247]
## Description

I happen to find there is  a new file in gh-pages branch.

I checked the commit log, it's the original service worker js

NetworkLogConverter.worker.bundle.worker.js → 379.bundle.js

We should keep it's old filename I think.

Or some filename to tell what it's doing. Current filename is confusing

**Comment by valarnin** [comment]
I'm really not sure why it's named like that in the gh-pages branch. When running with webpack dev server, the name is a bit ugly but at least it's obvious what it is:

![image](https://user-images.githubusercontent.com/6119598/124676324-4dfac580-de8c-11eb-8627-351e3e3a802d.png)

Maybe it's a dev vs prod build difference?

(this was caused by #3230, for reference. Since it doesn't need to bundle the js file for inlineing, it doesn't get a manually assigned bundle name I think)

**Comment by trim21** [comment]
it's named by chunk name rule `[id].js`, and its id was 379, and curretnly 378.

So there are 2 solution for this:

1. add webpack config `{ optimization: { chunkIds: 'named' } }`
2. set a chunk name when importing service worker `new Worker(/* webpackChunkName: emulator.worker" */ ... )`
