### ISSUE TITLE
Suggestion: Switch package manager to Yarn 2

### ISSUE THREAD

**Issue by MaikoTan** [quisquous/cactbot#3292]
[Yarn 2 (Berry)](https://yarnpkg.com/) brings many features:

- 🔌 [Plug'n'Play](https://yarnpkg.com/features/pnp). To get rid of the extremely biggest `node_modules`, it also make node scripts run faster. _moon, earth, sun, black hole, node_modules._

- 🏎️ Faster installation. Not only because of the [Zero-installs](https://yarnpkg.com/features/zero-installs) feature, but Yarn installs packages in parallel, however npm does this one by one, usually Yarn is faster than npm several times.

- 🔩 Cross-platform scripts. Yarn includes a simple shell interpreter, make scripts runs consistently across platforms, no matter which OS/Shell you're running from. _It is time to get rid of `node_modules/.bin/blahblah` prefixes!_

There are also disadvantages:

- 🔧 The first one is obvious: you should install Yarn manually and globally, it is not bundled like npm.

- 🐛 The [Plug'n'Play feature is not compatible with all tools](https://yarnpkg.com/features/pnp#compatibility-table), or only be supported by the new version, so it might be painful to make a bunch of tools work.

- 😫 Many IDE/Editor would assume that you are running npm by default, although you can configure it manually, for example in [VSCode ESLint plugin](https://github.com/Microsoft/vscode-eslint#settings-options).

------

Feel free to comment your thoughts! (づ｡◕‿‿◕｡)づ

**Comment by quisquous** [comment]
I don't know much about yarn, but I know it's widely used.  I think really my hesitation is that this creates more friction because it's another dependency to install.  Faster sounds nice, though.  :)

**Comment by MaikoTan** [comment]
Yeah, Yarn is widely used. Mostly I like its modern and fashion CLI. It is also bundled in `setup-node` action in Github Actions, so I think the most important thing is that how many cactbot developers supports it?

**Comment by JLGarber** [comment]
From a "developer-user" standpoint, my primary concern is "how much work will it take to make our existing tools work with Yarn?" I'm completely unfamiliar with Yarn, so anything that needs to be modified will block me completely until Someone Else is able to convert tools. This isn't necessarily a problem, since I would assume part of the process of moving to Yarn would be that conversion step, but it is something to be aware of. 

It's also important that we consider the novice contributor. When I started contributing here, I knew next to nothing about package managers and build tools. Those were things for Experienced And Serious Software Engineers, while I just wanted to write a few lines of Javascript. Installing NPM is already a bit of a barrier for newer contributors, and we really want to do our best to ensure that we do not make things more difficult for them, if possible.

Laying that aside, I think moving to Yarn is worth serious consideration just on the basis of improved speed and reduced disk churn. With the next expansion coming up, and all the new content that we will have to add, cutting off 10-15% of the time spent waiting for our tools to work would really add up.

How much effort would it take to set up a "prototype" Yarn environment or sandbox that we could try? I am happy to provide feedback on something like that, but I would have very little to contribute as far as putting it together.

**Comment by MaikoTan** [comment]
AFAIK, the migration should be done as follows:

1. `npm i -g yarn` (install yarn globally)
1. `yarn set version berry` (use yarn 2)
1. change `scripts` in `package.json` to be suitable with yarn
1. add `.yarnrc.yml` (configuration file of yarn)
1. generate lock file (`yarn.lock`) with `yarn install` and remove `package-lock.json`
1. modify `.gitignore` and `.gitattributes`
1. commit changes

------

For novices, I think, after installed `nodejs`, and then just run `npm i -g yarn` and `yarn install`. There you go!

(If we enable `Plug'n'Play` feature that I mentioned before, the `yarn install` part is also ignorable, but I didn't enable the VSCode support of PnP on my machine as far, maybe need some tweaks, I don't know. I would google and try something else later.)

**Comment by MaikoTan** [comment]
After trying several times, sadly I found that Yarn's PnP feature [doesn't support ESM currently](https://github.com/yarnpkg/berry/issues/638). So it seems redundant to migrate to Yarn 2 if we don't enable PnP/Zero-Install feature since it does the same work as NPM basically.

**Comment by quisquous** [comment]
It is so surprising to me how few things support ESM.  :C

**Comment by quisquous** [comment]
It looks like that issue got closed without any fixes? So maybe Yarn isn't going to support PnP+ESM?

**Comment by MaikoTan** [comment]
Well, no?
I remember Yarn has already ability to generate the ESM version of PnP bootstrap script, but I didn't try it in cactbot ever.
I'll try it when I have time. Sorry but I got being busying so long...

**Comment by MaikoTan** [comment]
As NPM now has part of Yarn Berry's features now, it would be better to just upgrade our npm version.
