### ISSUE TITLE
On Cactbot Job, is there a way to seperate cooldowns from the rest and give them an icon?

### ISSUE THREAD

**Issue by ExtraThicc1993** [quisquous/cactbot#3328]
## Question

What would you like to ask?

Title. Love the program but I have no need of the healthbar/pullbar and just want the cds (preferably with pictures). When it comes to DNC, devilment and the TS buff do have an icon, the rest are "just" colored boxes. I have tried to recode that but it didnt work, my programming skill are too bad for that.

Is there any way to customize the plugin or are we "stuck" with the layout we have?

Thanks in advance. :)

**Comment by MaikoTan** [comment]
For now, it is impossible to customize boxes of jobs module because they are hardcoded, but I am working on a patch (#3293) which extract and refactor every job components into `class`es to have clearer and easier interfaces. These are large changes so I can't tell when it is done, but once I have it done, it is easier to add a entry in `Options` variables in [user/ directory](https://github.com/quisquous/cactbot/tree/main/user), provide a way to implement your own component.

If you know JS and front-end development, You may find that cactbot was built up by [webpack](https://webpack.js.org/). I think what you said "didn't work" is because you didn't run "npm run build" before loaded in ACT?

**Comment by ExtraThicc1993** [comment]
Thanks for the swift response! 

Glad to hear you're working on a patch, really looking forward to that. Sadly I have no experience whatsoever in JS, just did a bit of CSS and HTML back in the day (both of which you can barely see as "coding"), tho I understand that it's quite a body of work to re-write an existing code. 

Keep up the good work!

**Comment by Iaotle** [comment]
I rewrote a bit of code to add my own icons, but I found that for SMN the UI does not show me nearly enough info even with icons. Additionally, the icons disappear when the CD starts, which makes it harder for me to use over in-game bars.

**Comment by quisquous** [comment]
I think #3714 is the right place to follow up on this issue.
