### ISSUE TITLE
plugin: use process id from FFXIV ACT Plugin

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#3353]
FFXIVProcess.cs `FindProcess` attempts to find the DX11 version of FFXIV that is running.  For folks running multiple copies of FFXIV at once, this will only ever find the first one.  Fix this code to prioritize using the process id that the FFXIV ACT Plugin is using.  It should still reject dx9 versions and handle processes exiting / restarting etc, but prefer using the FFXIV ACT Plugin version over the `FirstOrDefault`.

**Comment by MaikoTan** [comment]
I found that OverlayPlugin has a [`OnProcessChanged` event in `FFXIVMemory` class](https://github.com/ngld/OverlayPlugin/blob/master/OverlayPlugin.Core/MemoryProcessors/FFXIVMemory.cs), I don't know if it can be used in this cases tho 😂

**Comment by valarnin** [comment]
OverlayPlugin's `OverlayHider` hooks an FFXIV plugin handler which I think is a better target?

https://github.com/ngld/OverlayPlugin/blob/45d61da6ec12348c7c90247bf0b012078a7c8f71/OverlayPlugin.Core/OverlayHider.cs#L33

**Comment by MaikoTan** [comment]
Found that `triggernometry` hooks FFXIV_ACT_Plugin and invokes the `GetCurrentFFXIVProcess` method via "Reflection"(if I spell right?), which seems better 'cause you don't need to wait for a event?

https://github.com/paissaheavyindustries/Triggernometry/blob/beaa2695e104cf0e627c9604b9ec044775c839d2/Source/Triggernometry/PluginBridges/BridgeFFXIV.cs#L691

**Comment by ngld** [comment]
You should use the event handler since that's the only way to notice a changed process ID (the user can restart the game or select a different process at any time which you won't notice if you call `GetCurrentFFXIVProcess()` directly).

From what I've seen, the FFXIV plugin triggers the event handler during startup so you don't have to call `GetCurrentFFXIVProcess()` at all.

Both `OverlayHider` and `FFXIVMemory` use the event (through [`repository.RegisterProcessChangedHandler`](https://github.com/ngld/OverlayPlugin/blob/45d61da6ec12348c7c90247bf0b012078a7c8f71/OverlayPlugin.Core/Integration/FFXIVRepository.cs#L297) which just registers a new event handler on `DataSubscription.ProcessChanged`).

**Comment by quisquous** [comment]
> From what I've seen, the FFXIV plugin triggers the event handler during startup so you don't have to call GetCurrentFFXIVProcess() at all.

@ngld I think this is incorrect.  It appears that this is a race, and you should always initialize with the current process.  

[Ravahn says](https://discord.com/channels/551474815727304704/551892582855344128/937821033908543548) "ProcessChanged is an event my plugin raises when it first detects the game, and when the game process id changes."
