### ISSUE TITLE
question about Seiryu EX triggers

### ISSUE THREAD

**Issue by Amenne-ennemA** [quisquous/cactbot#337]
From the runs i've seen, the AoE markers during the SeiryuEx Ascending Marker Tracking' portion of the fight seem to be on Tanks and healers or DPS. so far every time. Is there a way to change the call or trigger to make the 
"condition: function(data, matches)" 
return data.blazing && matches[1] == data.me; 

also return a "return data.role == 'tank'" or healer or DPS?

to make the raid call say tank/healer in tower else spread or DPS in tower else spread?

I was looking myself but i really don't understand the condition context.

**Comment by DrLippe** [comment]
From what I read in the triggers, you get a popup text that tells you what to do. So everything fine.

If you want an non-personalized call out, this would be possible:
```
alarmText: function(data, matches) {
  if (matches[1] == data.me && (data.role == 'tank' || data.role == 'healer'))
    return 'tanks/healers spread (no tower)';
  if (matches[1] == data.me && (data.role != 'tank' && data.role != 'healer))
    return 'dps spread (no tower)';
  if (matches[1] != data.me && (data.role == 'tank' || data.role == 'healer'))
    return 'tanks/healers go tower';
  if (matches[1] != data.me && (data.role != 'tank' && data.role != 'healer))
    return 'dps go tower';
},
```
But this is a step back in my opinion.

**Comment by quisquous** [comment]
I think my only worry is what happens when not everybody is alive.  I guess in that case the spread vs get tower calls are already wrong since somebody with a marker might need to sac in a tower.

Ok, I'll update the trigger to say something like "Get Tower (tanks/healers)" or "Spread (dps get towers)".  I think it's important to tell the player what to do directly vs having them have to do an extra step to go "ok tanks/healers get towers, I'm a dps, so I go spread" vs just saying "spread".

**Comment by quisquous** [comment]
Thanks for the suggestion! :+1:
