### ISSUE TITLE
Ucob raid alert wrong info

### ISSUE THREAD

**Issue by Lotax** [quisquous/cactbot#3376]
I think found out the raid alert calling out wrong info on ucob p2 Nael dive bombs mechanic. It tells 3 corners to bait them but they seems kinda wrong out what the dragons spawn  it just  tell wrong order to bait in even clock or counter clockwise

**Comment by MrTefty** [comment]
It's the phase 2 Nael announcements that are not working.
His phrases are not being called at all however fire and ice are.

**Comment by nyxalteria** [comment]
Can confirm, its saying things like NE SE NE, cant place 2 dive bombs in the same spot

**Comment by quisquous** [comment]
Can you upload a zipped network log, here or somewhere else?

**Comment by nyxalteria** [comment]
sent

**Comment by MrTefty** [comment]
Yes the dive announcements are wrong but I was also unable to have the Nael RP quotes calling as well. Gave up in the end...

Regards,

Andy Smith
________________________________

**Comment by quisquous** [comment]
@nyxalteria Thanks, I'll take a look.

@MrTefty Nael RP quotes sound like a separate issue than this.  The most likely problem for you is that you have "Hide chat log for privacy" clicked or you have not enabled NPC dialog to show up in game (and thus it won't make it to the log).  You could verify this is the problem by looking in your log and seeing if you see the nael dialog lines.  You should also take a look at #2727, #2830, and #3358 for people who have had similar problems because of settings.  Finally, you filed but closed #3417, which made me think that you had fixed it.  Is that not true?  Do you want to move this conversation there if these suggestions don't work?

**Comment by quisquous** [comment]
I think all of the issues are addressed here.
