### ISSUE TITLE
raidboss: user trigger on a skill that starts a fight does not get executed

### ISSUE THREAD

**Issue by Akurosia** [quisquous/cactbot#3404]
Based on https://discord.com/channels/551474815727304704/551476873717088279/878297392053637150

When a skill starts a fight (in the following example Assize) the trigger does not get executed.
Doing the action a second time while in fight (or completly out of fight) will work as expected

example trigger:
```
Options.Triggers.push(
    {
      zoneRegex: /^.*$/,
      triggers: [
        {
            id: 'General Assize',
            type: 'Ability',
            regex: Regexes.ability({ id: 'DF3' }),
            condition: function (data, matches) {
                return (matches.source === data.me && matches.target === matches.source);
            },
            delaySeconds: 3,
            infoText: 'Assize used',
        },
      ],
    },
);
```

I could verify this on striking dummies as well as ifrit hard mode

**Comment by marzent** [comment]
Weaving a Dia+Assize on the first gcd with delayed triggers also results in both triggers not registering, although it works as expected from the 2nd gcd onwards

**Comment by marzent** [comment]
Interestingly using a Promise instead of delaySeconds works just fine and is a pretty good workaround atm.

 ```
 Options.Triggers.push(
     {
       zoneRegex: /^.*$/,
       triggers: [
         {
             id: 'General Assize',
             type: 'Ability',
             regex: Regexes.ability({ id: 'DF3' }),
             condition: function (data, matches) {
                 return (matches.source === data.me && matches.target === matches.source);
             },
             promise: async () => {
                await new Promise(r => setTimeout(r, 3000));
            },
             infoText: 'Assize used',
         },
       ],
     },
 );
 ```

**Comment by quisquous** [comment]
The issue is that anything that has a delay is cancelled when the fight starts.  The ability goes off, then the fight starts, and the delay from that ability is cancelled.  It used to be the case that delayed triggers were cancelled when the fight ended, but sometimes an ability would come in right after the fight "ended" and start a trigger, and so I moved all of the resetting logic to when the fight starts.  I'm not sure how to differentiate "trigger from the previous fight" and "trigger that just started this fight", and so I'm kind of inclined to say "sorry this is an edge case that doesn't work".

**Comment by Akurosia** [comment]
I am fine with closing this, as it was just posted on behalf of a discord user to have it noted down somewhere.
