### ISSUE TITLE
Fishing overlay doesn't handle undiscovered fishing hole

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#346]
Once it figures out which fishing hole you're on, even if it's `undiscovered fishing hole`, then it gets stuck on that.  Maybe it should ignore fishing holes it doesn't know about? Or handle that one specifically?

Log lines in English:
`You cast your line at the undiscovered fishing hole.`
`Data on the unfrozen pond is added to your fishing log.`

**Comment by xephero** [comment]
This probably happens because it detects the spot name as `undiscovered fishing hole`, then tries to look up `undiscovered fishing hole` in `gFisherData['places']['en']`, which doesn't exist, so it doesn't fill in any fish. You mentioned it gets stuck; on the next cast, the expected behavior is that it would now include the cast place in the log line and pick up from there. You're saying it just becomes outright unresponsive after that?

**Comment by quisquous** [comment]
Re: getting stuck.  Once the fishing hole is discovered, the overlay doesn't update and it continues thinking you're on `undiscovered fishing hole`.

**Comment by someONEgood** [comment]
![wut](https://user-images.githubusercontent.com/46905309/52908833-18b19680-3243-11e9-901a-55ea9280f9f8.PNG)
Any idea why the column beneath Cast Time isn't displaying properly?
I Unblocked the .zip and properly installed AFAIK.

Also the Rhotano Privateer doesn't seem to be triggering the overlay.
But that could just be whatever quirk is preventing it from running properly.
