### ISSUE TITLE
raidboss overlay shows default data

### ISSUE THREAD

**Issue by ezsoftware** [quisquous/cactbot#35]
I'm trying to get this set up for the first time and I used raidboss last night, but the overlay shows a bunch of default data that I doesn't go away.
![image](https://user-images.githubusercontent.com/8754420/35769378-24672b80-08c7-11e8-870f-a0f1a563e48a.png)

The test bar 1 through test bar 6 are staying, to use it I had to open the console and remove them manually.

The Action texts push down the placeholder texts in the image, but the "Alarm text" "Alert text" "info text" always stays up.

**Comment by quisquous** [comment]
Take a look at https://github.com/quisquous/cactbot#adding-overlay-modules

You need to do steps #7 and #8, in particular resize the overlay (which has the blue background) both taller and wider so that the triggers and timelines are not on top of each other.  Then once it's resized, lock the overlay so that all the default placeholder text disappears.

I'm sorry for the confusion about this.  You're not the first person to have asked this.  I probably need to just make the overlays larger by default, but I'm not quite sure how to communicate the "please lock the overlay to make the default text go away" more clearly.

(Also also, thanks for include cactbot in the bundle! I'm super excited about that!)

**Comment by ezsoftware** [comment]
no problem! ok, thanks!

**Comment by quisquous** [comment]
It's good to know that this is still not clear, though.  I really like having default text to make resizing and placing the overlays easier (without having to go do something in game to manually trigger the overlay), but it's also not something that other overlays really do.  I'll think about changing the default timeline lines that just say Test Bar to say something about locking the plugin for clarity.

**Comment by ezsoftware** [comment]
Or bake some instructions or steps right into the settings panel, Step 1 > Select your overlay, then have the selection options, step 2 > move your overlay and resize it to look similar to this image (provide an image with how a nice overlay is, step 3 > lock your overlay in position for great power!

**Comment by ezsoftware** [comment]
Or adding instructions to the unlocked bars, I like that idea too, then its obvious when someone is looking at it what they need to do.

**Comment by danakj** [comment]
I was thinking a "Lock to make this go away" would be good, but if its in the middle of 100 bars it won't be too visible.
