### ISSUE TITLE
raidboss: convert timelines to use netregexes

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#3547]
Currently, timelines are using bare regexes against parsed log lines.  Given that the format of these will break in 6.0 and that literally everything else is using network log lines, we should switch these to using netregexes.

Proposing something like this, with the code (at least logically) being eval'd:
```diff
-11.5 "Screams Of The Damned" sync /:Suzaku:32D2:/ window 12,20
+11.5 "Screams Of The Damned" sync ability({ name: 'Suzaku', id: '32D2'}) window 12,20
```

It's probably worth breaking timeline backwards compatibility for this, as it seems unlikely that users will have extensive syncs in their own personal timelines (additional entries: yes, additional syncs: maybe no?).  It is possible that users will have replaced entire timelines, which is probably the worst case scenario for breakage.  We could consider being backwards compatible to parsed log line syncing as well if we had to, but it might be nice if cactbot only dealt in network log lines everywhere, for efficiency / consistency / network bandwidth when using cactbot remotely.

The blocker here to doing this is that make_timeline.py and test_timeline.py need to be converted to TypeScript first so that they can parse this new timeline format.  Although it'd be simple to have make_timeline.py emit this, as `NetRegexes.ts` is TypeScript, there'd be no (easy) way for test_timeline.py to eval these expressions.

**Comment by xpdota** [comment]
My 2c is that one very nice thing you'd get by using something like either of those options, is that it would be possible to support things that aren't directly in the log line, like NPC IDs. It could also open the door to future customization via user-added fields. 

Something like:
```kdl
entry time=100 window=[2, 5] sync={type: ability, source: {npcID: 123}, id: 456} text="Something"
```

This would significantly reduce the need for multilingual timeline replacements, because most things could be done without any name whatever (realistically, that goes for Cactbot triggers as well - most of the multilingual versions are differentiated only in the NPC name).
