### ISSUE TITLE
timeline overlay lag 

### ISSUE THREAD

**Issue by jenkshi** [quisquous/cactbot#356]
hi I noticed that the timeline overlay is laging a lot lately all though it was enough before please I need help  because it become unusable.

**Comment by quisquous** [comment]
When did this start happening? Is this related to issue #71? Does it lag when it's the only plugin?

**Comment by jenkshi** [comment]
1- I don’t know but it started recently 
2- I think it is similar maybe not sure
3- I didn’t test it yet

**Comment by jenkshi** [comment]
can you tell me how you fixed #71 issue and see if it is the same

**Comment by jenkshi** [comment]
-Btw I noticed that it is using a lot of CPU power like case #71  around  20%+
-it dose not matter if it is the only overlay working
-I am using the a similar monitor to case #71  1440p , 100hz : https://www.asus.com/me-en/ROG-Republic-Of-Gamers/ROG-SWIFT-PG348Q/


Sent from Mail for Windows 10

**Comment by quisquous** [comment]
If you have a similar monitor, just for debugging, can you try turning off your second monitor? Or setting all of your monitors to run at 60hz?

**Comment by shastaxc** [comment]
I just wanted to comment that I have had similar issues with ACT Overlay Plugin (Kagerou). I have not used Cactbot yet, but I have experienced this "lag" with the other plugin. This problem is difficult to replicate. I have only experienced it twice in about a month while running these programs 6+ hours per day. I am only commenting here because I realize I also have a 144hz 1440p monitor, similar to OP.

Relevant PC specs:
- Main monitor 144hz 1440p (where I run FFXIV)
- 2nd monitor 60hz 1080p (where I run ACT)
- Neither monitor has Freesync or Gsync
- Game FPS settings capped at 144hz
- Nvidia GeForce GTX 1080 TI
- Windows 10

These facts made me think to Google the problem to see if it is unrelated to FFXIV and ACT. I managed to find these posts:

- https://www.reddit.com/r/pcmasterrace/comments/5o32vs/psa_for_people_with_144hz_60hz_dual_monitor_with/
- https://www.reddit.com/r/pcmasterrace/comments/7h9bnu/psafor_people_with_dual_monitors_with_different/

I have only recently noticed this issue because I took a break from FFXIV for over a year and just started playing again. In the meantime, I upgraded to this new 144hz monitor.

In my opinion, this is probably a result of running ACT on a 60hz 2nd monitor while having the overlays displaying on another monitor with higher refresh rate (which is neither 60hz or 120hz) but ACT still trying to render the overlay at 60hz, causing applications on the main monitor to occasionally drop FPS to compensate.

The overlay should be forced to run at the framerate of the monitor where the overlays are being displayed. This may be something ACT itself would need to fix, not sure if it is in the scope of a plugin.

In the meantime, I recommend applying some of the "fixes" in the links I posted.

**Comment by shastaxc** [comment]
Side note: this might also occur in overlays using transparency. In which case, a temporary fix might be to disable transparency, or give the user an option to disable transparency.

**Comment by jenkshi** [comment]
hi I turned to the screen to 60Hz and everything is fine now but I still wish if it would have worked normally on 100Hz

**Comment by quisquous** [comment]
Unfortunately, there's really no control that the overlay has.  Chromium Embedded Framework has a maximum of 60 fps, and so any OverlayPlugin overlay that uses this will run into this issue.

If you look at #71, you can see that all the extra cpu time is being spent in graphics drivers themselves, and so my belief is that this is a Windows issue.

I also wish that it would work normally at high framerates, but I don't know that there's anything cactbot can do, sorry.
