### ISSUE TITLE
Jobs: GCD calculation can not work properly

### ISSUE THREAD

**Issue by Echoring** [quisquous/cactbot#3788]
When you change to job above level 80, console will output an error: `Error: This code shouldn't be reached`
If this job module contains something using GCD calculation, it will continously output this error when using it. 
Job below level 80 won't recive this error, but GCD calculation also works not properly.
Seems this error happens because kLevelMod have not updated yet.

**Comment by MaikoTan** [comment]
This is caused by

https://github.com/quisquous/cactbot/blob/54303910154b6ae5847780f1dbac616ce629a381/ui/jobs/utils.ts#L139-L141

the `kLevelMod` has only data below level 80, so when your level is higher than it, then cause the error.

As we now still don't know what is the parameters mod in Endwalker, I think we can change the code temporarily to avoid the error.

## Possible solutions

1. add `[0, 0]` items in `kLevelMod` up to level 90, so that the function would run with no errors.

1. delete the `UnreachableCode` error here, but add logic that when we cannot fetch the current data, then treat it as 0.

**Comment by quisquous** [comment]
I kind of like (1) because then when we get to level 100 we'll remember this has to be updated too.
