### ISSUE TITLE
High CPU usage in Eureka and game lagging

### ISSUE THREAD

**Issue by lyra133** [quisquous/cactbot#386]
Hello,

I noticed that in the latest version my CPU usage gets really high when I'm in Eureka. In this case it was in Pyros. It happens mostly when I run from fate to fate in a full instance(bunch of people walking/riding and pulling a bunch of mobs on the way, people syncing to a fate etc.) - not so much when actually fighting a fate-mob. 

My task manager showed that ACT used around 40-50% of my CPU, witch made the game laggy after a while(low fps, bad frametimes and input lag)- basically unplayable. It stops when I close act. If I restart it, it works okay for a while but then starts again.

Here are my act settings(multiple pictures): https://imgur.com/a/ViB6LG9

**Comment by quisquous** [comment]
Thanks for the report.  Sorry to take a bit to get back to you on this.  I have two experiments for you to try and report back to me about:

(1) try removing the dps overlay temporarily, and see if that makes a difference.  (Theorizing that it's probably dps even if it's not during a fight, like maybe garbage collection or something in C#.)
(2) if that does make a difference, add a "Mini Parse" (instead of cactbot) and use the same rdmty overlay (it should work), and see how your cpu is then.  (Theorizing that maybe cactbot is less efficient in how it sends out dps updates?)
(3) If none of that works, try removing other plugins and overlays in ACT??

**Comment by quisquous** [comment]
Also, is this related to issue #71, in terms of monitor refresh rate?

**Comment by quisquous** [comment]
If this is still happening and you have the answers to the questions I asked above, let me know.  Otherwise, I'm going to close this for now.

**Comment by xobs** [comment]
I've also been experiencing low fps when using ACT and cactbot. Frequently ACT uses just as much CPU as ffxiv itself.

I suspect it has to do with the javascript engine, or maybe there's a multithreading issue on my system, which is a virtual machine running qemu.  In any case, I'll try running a profiler next time I'm in a large battle to figure out exactly where the bottleneck lies.

One difference I tried was to lower the framerate of CEF:

```patch
diff --git a/CactbotOverlay/OverlayAddonMain.cs b/CactbotOverlay/OverlayAddonMain.cs
index d128263..a7b73dc 100644
--- a/CactbotOverlay/OverlayAddonMain.cs
+++ b/CactbotOverlay/OverlayAddonMain.cs
@@ -28,7 +28,7 @@ namespace Cactbot {
     }

     public IOverlay CreateOverlayInstance(IOverlayConfig config) {
-      config.MaxFrameRate = 60;  // The maximum allowed by CEF, sadly: http://cefsharp.github.io/api/51.0.0/html/P_CefSharp_BrowserSettings_WindowlessFrameRate.htm
+      config.MaxFrameRate = 10;  // The maximum allowed by CEF, sadly: http://cefsharp.github.io/api/51.0.0/html/P_CefSharp_BrowserSettings_WindowlessFrameRate.htm
       return new CactbotOverlay((CactbotOverlayConfig)config);
     }

```

Under the theory that having a web browser render 1/6 as fast would improve performance, especially for something that doesn't need 60fps.  It's unclear whether this made a difference.
