### ISSUE TITLE
Alerts and timer don't work for Dead Ends

### ISSUE THREAD

**Issue by coyfish1** [quisquous/cactbot#3903]
## Description

A total of 0 timeline events show and a total of 0 alerts display during The Dead Ends. 

I see it has a trigger file and it was marked on the sheet of supported dungeons as complete, but there must be an issue somewhere.

Also, Zodiark (normal and EX) are nowhere near complete. I think marking them with the green check mark on the completion sheet makes people think it's 100% complete and thus less users contribute to completing it.

**Comment by quisquous** [comment]
> I see it has a trigger file and it was marked on the sheet of supported dungeons as complete, but there must be an issue somewhere.

Are you using the github.io link or a local version of overlays? If you're using the local version, The Dead Ends has not been released yet.  The 📢 note at the top of the page tries to describe that.  Let me know if there's some better way to word that.

> Also, Zodiark (normal and EX) are nowhere near complete. I think marking them with the green check mark on the completion sheet makes people think it's 100% complete and thus less users contribute to completing it.

I don't think number of contributors is really the problem here.  It's being worked on #3798 but it's complicated.

Agreed that the checkmark is deceiving, but at the moment there's not a "there's something here but it's not complete mark".  I'm happy to review a PR if you wanted to add this.

**Comment by quisquous** [comment]
Did the new release work for you in the Dead Ends?

**Comment by Enzemo** [comment]
Not sure if this helps or not, but I found that none of the Endwalker content was working at all despite updating the plugin through ACT and the plugin listing showing me on the latest version. After manually removing and updating it, it works.

**Comment by quisquous** [comment]
@Enzemo that sounds like you had a failed update, then.  Reinstalling is the right thing to do.

**Comment by quisquous** [comment]
If this is still an issue, let me know.
