### ISSUE TITLE
missing Timelines in older encounters

### ISSUE THREAD

**Issue by Cropz** [quisquous/cactbot#391]
Cactbot timelines work just fine for newer encounters (Sigma/Alphascape and SB Trials), but they're completely missing for older content (all of Deltascape and Alexander/HW Trials), eventhough I still get some trigger warnings, the timelines themselves don't show up on screen.

I feel like I'm missing something here, if I could get some insight would be very much appreciated, thanks.

**Comment by quisquous** [comment]
The things that cactbot works for is listed here: https://github.com/quisquous/cactbot/tree/master/ui/raidboss/data/triggers

Deltascape Savage should have triggers and timelines.  Alexander Savage should have timelines.  Some of the HW trials exist, like ravana, seph, and sophia.  None of the Alex or Deltascape normal modes have any timelines or triggers because nobody's ever written them, sorry.

Are there specific things in particular you do regularly that you feel like you want triggers or timelines for?

**Comment by Cropz** [comment]
Sorry I wasn't very clear, I'm talking about the Savage/Extreme versions that do have timelines, but are not showing up.
So I'm wondering for example what would make the Sigma/Alpha Savage timelines work just fine, when the Delta Savage timelines don't.

**Comment by quisquous** [comment]
Do you know what the zone names are for zones where it isn't working for you? Maybe ACT has changed the zone names?

Do you get any errors in your console log when doing those?

For what it's worth, I did o2s a few times just a week ago, and it worked just fine.

**Comment by Cropz** [comment]
the console log is the one at the bottom under Plugins > OverlayPlugin.dll right?
there are no error messages that show there.
so I just went through all of Alexander, and half of it had working timelines, while the other half didn't show anything at all, coincidentally (or not?) the first and last fight of each wing didn't work (so 1/4/5/8/9/12).
as far as Deltascape goes, I have only done o4s recently, and that one didn't work.
of the HW trials, only Ravana's timeline seem to be working as well.

**Comment by quisquous** [comment]
I couldn't test a1s/a5s/a9s solo because of fausts.  However, there aren't any faust timelines, if that's what you were missing.

a4s was broken and I'll update that shortly.  a8s, a12s, seph, and soph all worked fine for me.

Do you have Network logs from when you were doing these?

**Comment by Cropz** [comment]
I did a quick one on those four, here's the log:

[Network_20190324.log](https://github.com/quisquous/cactbot/files/3000844/Network_20190324.log)

**Comment by quisquous** [comment]
Ah, thanks.  I see the problem.

a4s doesn't count until I push the changes I made, but in the other logs it's clear that you don't have some of the battle messages turned on in logs.

a12s in particular uses the phrase "uses Divine Spear" to start the timeline.  It looks like you don't have any of the battle logs turned on that include that.  I think this is Character Configuration -> Log Windows Settings -> Log Filters -> (click on a log type, probably Battle) -> Battle Tab -> Subject: Engaged Enemy -> Check All.

Newer timelines tend to use ACT-parsed network log lines and so don't depend on the battle log from in game.  However, older timelines don't and so you need to have those log filters checked so that the game sends you those messages.

**Comment by Cropz** [comment]
yeah, that literally just dawned on me as well, I went ahead and enabled everything back up and it's working fine now.
I couldn't personally check Deltascape yet because of the whole "can't undersize" thing, but that was probably the case in there as well?

**Comment by quisquous** [comment]
re: deltascape.  Reading the timelines, it definitely is in o4s, but isn't in 1, 2 or 3.

**Comment by Cropz** [comment]
I'll write back when I get the chance to do those then, thanks for taking the time o/

**Comment by Cropz** [comment]
ok so I've had a chance to go through Deltascape, o2s and o4s had working timelines, while o1s and o3s didn't, here's a log:

[Network_20190327.2019.03.27.log](https://github.com/quisquous/cactbot/files/3016046/Network_20190327.2019.03.27.log)

I've cropped it to remove clutter from outside the instance, since this one was bigger

**Comment by quisquous** [comment]
Because you cropped it, I'm not sure if this is the issue, but did nobody use a countdown when pulling those?

**Comment by Cropz** [comment]
we did not do countdowns for those, that's true, I've not cropped anything from inside the instances.

**Comment by quisquous** [comment]
Yeah, if there's no countdown, then timelines don't start until the first ability like 10 seconds in.

It sounds like this is likely fixed then.  Let me know if you see anything else not working.  Sorry about these old encounters; I apparently had a countdown every time I did them.
