### ISSUE TITLE
RAIDBOSS : Some timelines doesn't pop up in the KR server.

### ISSUE THREAD

**Issue by duvwlqdjssl1222** [quisquous/cactbot#3949]
## Description

Some timelines doesn't pop up in the KR server. But TTS still works. Only the timeline is not displayed. The dungeons with the problem are "漆黑決戰 ノルヴラント(노르브란트)" and "希望ノ砲台：「塔」(희망의 포대: 탑)" I couldn't check anywhere else.

## Additional information

If available, please include any logs or screenshots depicting the issue you're experiencing.

**Comment by quisquous** [comment]
I don't know what the first one is, but the second one looks like The Tower at Paradigm's Breach.  That one should work, based on theh translations I see in the file.  If it doesn't, then I would recommend reinstalling cactbot in case you have an update that failed partially.

Maybe @Bing-su can confirm if this is working or not?

**Comment by MaikoTan** [comment]
I am sure the first one is heroes gauntlet in shb according to the japanese name.

**Comment by Bing-su** [comment]
Yes. the first is `heroes_gauntlet` and second is `the_tower_at_paradigms_breach`.

#### Heroes gauntlet first boss
![캑트봇 이슈 2](https://user-images.githubusercontent.com/37621276/147848077-29d7377d-3dbc-4673-9d21-9489ebf37587.png)

It seems to work in my environment.

FFXIV ACT plugin: 2.1.2.9 (kr)
overlay plugin: 0.18.0.0
cactbot = 0.24.9

**Comment by Bing-su** [comment]
I think the root cause is the regular expression changed in 6.0.

In `heroes_gauntlet.txt`:
```
0 "Start" sync / 00:0839::The Mount Argai Mines will be sealed off/ window 0,1
9.8 "Spectral Dream" sync / 1[56]:[^:]*:Spectral Thief:4FCB:/ window 9.8,5
```

In my act log:
```
00:0839:15초 후에 아르게 광산이 봉쇄됩니다.
16:400017BA:환상빛의 도적:4FCB:
```

korean server is still `00:0839:` but timeline is `00:0839::` so doesn't match.
but, next skill `Spectral Dream` matches and the timeline popped up.


In `the_tower_at_paradigms_breach.txt`
```
1000.0 "--sync--" sync / 00:0839::Closed Area A will be sealed off/ window 10000,0
1012.0 "Roar" sync / 1[56]:[^:]*:Knave Of Hearts:5EB5:/ window 10,10
```
Unlike dungeons, timeline second starts from 1000.

```
00:0839:15초 후에 봉쇄 구획 A가 봉쇄됩니다.
16:40000057:잭:5EB5:
```

therefore, even though "Roar" matched, the timeline did not start because the time condition was not met.

I think my issue #3928 has the same cause.

**Comment by quisquous** [comment]
If I run `npm run util`, pick translate timelines, pick tower at paradigms breach, and then pick Korean, I see this translation:

`1000.0 "--동기화--" sync / 00:0839:15초 후에 :봉쇄 구획 A(?:이|가) 봉쇄됩니다/ window 10000,0`

...because of the `00:0839::?` in `common_replacements.ts`.  So, I am not sure why this is not working specifically.

I do know that the starts casting lines are wrong, but that zone seal in particular should work.

**Comment by Bing-su** [comment]
I didn't know it worked that way... I got it wrong.
```
1000.0 "--동기화--" sync / 00:0839:15초 후에 :봉쇄 구획 A(?:이|가) 봉쇄됩니다/ window 10000,0
1012.0 "포효" sync / 1[56]:[^:]*:잭:5EB5:/ window 10,10
```

I see the same translated timeline.

**Comment by quisquous** [comment]
Is this working now?

**Comment by duvwlqdjssl1222** [comment]
I was using 0.23.12 and there was no error.
After the update, I will test it.
...
Updated to 0.24.24. The error does not occur.
You are the best.

2022년 4월 10일 (일) 오전 4:37, Adrienne Walker ***@***.***>님이 작성:
