### ISSUE TITLE
Setting a breakpoint causes devtools to hang

### ISSUE THREAD

**Issue by amki** [quisquous/cactbot#405]
Setting and triggering a breakpoint in cactbot's devtools causes them to hang.

To reproduce:
Set a breakpoint in ui/dps/rdmty/dps.js ( I used line 9) and trigger it ingame (get in combat, heal someone)

Expected behavior:
I should be able to click around and debug in the devtools. :)

**Comment by quisquous** [comment]
Hmm, I can reproduce this too.  I feel like this used to work.  Let me debug further and see what the C# plugin is hung up on while this happens.

**Comment by quisquous** [comment]
Hmm.  I tried a number of things, but I was unable to figure out what's going on here.  It seems like you can step/pause the debugger, but devtools itself is impossible to interact with when paused.

I suspect that there's something weird going on on the C# side, where it's blocked on something and isn't yielding to the event loop, but it's also not clear from the debugger.

I don't know that I'm going to have any time to investigate this further, as there's some other cactbot issues (like startup, or even fixing oopsy since 4.5) that are a bit more pressing.

If you have any thoughts or anybody else is able to figure this out, I'd love any assistance.

**Comment by quisquous** [comment]
This was fixed when switching to the ngld overlayplugin (hooray).
