### ISSUE TITLE
PIDDEBUG: it's normal ?

### ISSUE THREAD

**Issue by VanSlanzar** [quisquous/cactbot#4096]
- Is it normal to have this? PIDDEBUG and Oopsy request.
![Screenshot_8](https://user-images.githubusercontent.com/61565834/152064331-766fc6c6-f62f-4564-b609-3ecfd0142744.png)

- The timeline does not appear on all content. Is something wrong or is it me?

**Comment by quisquous** [comment]
PIDDEBUG is just temporary debugging.  I'll remove it when I think that issue is fixed.

Oopsy request prints because you have Debug clicked.

I am not sure why the timeline is not appearing.  I think you'd have to be more specific about which content it's not appearing in or when.  I don't know of any issues in this area.

**Comment by VanSlanzar** [comment]
- Oopsy request
It appears, as soon as the program is launched, without me being in any content.

**Comment by VanSlanzar** [comment]
Ok thank you.
