### ISSUE TITLE
Not sure how to correctly add custom triggers

### ISSUE THREAD

**Issue by Macapple96** [quisquous/cactbot#410]
I was looking at the O12S.js file and noticed most triggers have more stuff than I expected in regexes: 
`regex: / 14:(?:334B|334C):(?:Omega|Omega-M) starts using (?:Unknown_334B|Unknown_334C|Optimized Blade Dance) on (\y{Name})/,`

For example, what does the `14:(?:334B|334C):` or `1A:Omega gains the effect of`do there? Could it be the boss "miniphases"?

Also, why do the regexes (and fflogs) match and show "starts using <skill>", but this line is nowhere to be found in my output network logs? Raidboss still works, so I guess the line IS there, but I can't find it.

I'd like to know more about how to correctly set up custom triggers from the ground up.

**Comment by quisquous** [comment]
Any message that starts with `00` is a combat log message from the game itself.  Other message types are ones that the ffxiv act plugin has synthetically created and output.  Sometimes these are formatted (e.g. `14` starts using messages) and other times these are pretty raw data (e.g. `1B` headmarker data).  I deliberately write all of my triggers with non-combat log messages (i.e. try not to use any `00` lines) because these show up first in the log, sometimes by about a half a second, so it's better for triggers.

You should be able to see these messages in the battle log in ACT, if you right click on an encounter and go to View Logs.  (You may need to set an option to retain these.)  The network log files themselves contain the raw values that ravahn's plugin synthesizes.  Importing network logs and then viewing the logs inside of act is how I usually write triggers.

Here's a raw network log for what would turn into a log message of: `14:2BBA:Tsukuyomi starts using Reprimand on Tsukuyomi`: (0x14 in hex = 20 in decimal)

`20|2019-05-17T18:56:36.9400000-07:00|40002654|Tsukuyomi|2BBA|Reprimand|40002654|Tsukuyomi||e82b7a6b9af39de75c7c589d6d625ee0`

Here's a list of ability ids that I've written down for convenience:
https://github.com/quisquous/cactbot/blob/master/ui/oopsyraidsy/oopsyraidsy.js#L127

If you wanted to write short triggers, probably something like `:2BBA:Tsukuyomi` (for starts casting) and `:Tsukyomi:2BBA:` (for actually uses) would be sufficient.  You can see that most of the timeline syncs use this style of regex.  I tend to write triggers a little bit more wordily in case I ever have to go back and change them so that I have more context, but that's just personal preference.

Hope that helps! Let me know if you have any other questions.

**Comment by Macapple96** [comment]
I see now! Thank you SO much! This is very useful information! 👍 

Consider adding this info in the raidboss page, or in the raidboss-example.js file! :)

**Comment by quisquous** [comment]
Happy to help!  You're right that I should probably put this into some documentation that I can just point at.

**Comment by quisquous** [comment]
Documentation: https://github.com/quisquous/cactbot/blob/master/docs/LogGuide.md
