### ISSUE TITLE
raidboss: issues with v0.24.20

### ISSUE THREAD

**Issue by PreThousandFlower** [quisquous/cactbot#4165]
Always thank you for maintaining project. Again, here are some problem reports which were only tested in KR client. (It has had no file change since Jan 11th, 2022(v5.58), and would not be changed before v6.0 - May 10th.)

## Description
After updating to v0.24.20, I found some SB ultimates triggers did not work. It looks similar to #3415 but I'm not sure that they are KR specific problems. I saw **UWU Titan Gaols** and so UWU Titan Bomb Failure triggers do not work. Also, many community members said that in UCoB, **UCU Nael Fireball 2** trigger outputs only fireOutBeInIt no matter what ice debuff count is. Another debuff triggers, like **UCU Nael Thunderstruck** and doom counts also seem not to work. I remeber that they had no problems on Feb 15th when I was in UCoB, so I guess it has occured after v0.24.20. May you examine whether they are global cactbot issue or because of parser version as before, or something else?

## Additional information
https://drive.google.com/file/d/1sm-BEdCRNB-5tR7Miukq_ZON6int_1O0/view?usp=sharing
The UCoB log is provided by my friend.

+Minor problem: Encounters in my previous UCoB log(on Feb 15th) and UCoB log in the link above cannot be loaded in raidemulator.

**Comment by quisquous** [comment]
Thanks for the bug report! My initial suspicion is that this is a global cactbot issue.

Extremely surprisingly, some initial testing makes it seem like #4143 might be causing this? If I load an UWU log in the emulator at 0.24.20 it is missing `UWU Titan Gaols` and console logs in the `preRun` of that trigger do not get emitted.  If I revert that commit, then they appear.  (cc @valarnin FYI).  Additionally, a number of other triggers like provoke and shirk (and other ability triggers?) don't seem to show up in the emulator with this commit.

I'll take a closer look later today when I have more time as this seems really bad.

**Comment by quisquous** [comment]
Ohhhhhhh I know.  It's the addition of `targetCount` at the end of the lines which doesn't exist in Korean logs and doesn't exist in older English logs from pre-6.x.  Previously, `ability` would have matched (but not `abilityFull`) because it only matched some of the fields.

Ugh, bitten again by another difference between versions.  I guess we need to make `targetCount` optional somehow?  And also think about what backwards compat for log files could look like.

**Comment by valarnin** [comment]
Would it make sense to lang key the definitions, with a default of en, like others?

**Comment by quisquous** [comment]
> Would it make sense to lang key the definitions, with a default of en, like others?

I have mixed feelings here.  It's certainly technically possible, but then we would either need to pass the language into the calls to NetRegexes, either explicitly as an argument or implicitly as some language global set before importing the trigger files.  Both of these are a little bit awkward.

Furthermore, another consideration is that this will be "fixed" in May when the Korean 6.x version is released and Ravahn updates the plugin to include the changes.  I have mentioned this to Ravahn in the past, and will bring it up again re: releasing structural changes to all languages at the same time.  If in the future this won't happen again, I'm inclined to just remove targetCount in the short term and add it back in a few months.

Other options could be somehow making targetCount optional without setting a language, although that seems tricky to do right, especially with net -> parsed log conversion.

I'm also not sure what the right long term solution is here, as it'd be nice to be able to load old logs into the emulator and have them still work.  So, maybe we need netlogdefs, but with various versions or diffs applied?  This sounds complicated too, but at the very least would only need to be done on the emulator end of things so maybe would be more narrowly scoped than "all regexes".

**Comment by quisquous** [comment]
Hmm.  Ravahn says likely yes in the future the Korean version can be in sync, but the Chinese version is done separately off of older ffxiv plugins and so will still be an issue.

I think in that case, I'd almost rather have versioned netlog_defs (by ffxiv plugin version?) and then we can assign them to languages.  Maybe in a diff format, where we have the most current version, and then we have some older version struct that overrides some of it.  However, we would then need some way of handling the mismatch, e.g. providing an empty string for `targetCount` (or some other sensible default?) when matching so that the `matches` types were the same.  Maybe we'd need to add this in the exec function?  Just thinking out loud.

In the short term, I think removing the `targetCount` patch is still the best approach, and we can add it back in when there's a more full solution.

**Comment by valarnin** [comment]
I agree that reverting the `targetCount` patch is the best idea for now.

Versioning netlog_defs and therefore raidemulator code will probably work fine as well, but we may want to store the version in the encounter info for emulator and possibly detect it somehow? Regardless, that's not really a question for this issue.
