### ISSUE TITLE
Personal trigger doesnt work for my character that has special character like "-"

### ISSUE THREAD

**Issue by PengBooz** [quisquous/cactbot#4176]
Triggers that need personal name to work (ex: p3s headmark, p3s bird, p2s headmark) arent working when I use my character that has "-" on name. It works as intended when I use my other character.

Any ideas why its doing that?

**Comment by wexxlee** [comment]
@PengBooz I reported this in #4117 and it was fixed by quisquous in #4175 earlier today.  You can download the artifacts link at the bottom of [https://github.com/quisquous/cactbot/actions/runs/1940492343#artifacts](https://github.com/quisquous/cactbot/actions/runs/1940492343#artifacts) and replace your cactbot dlls with the two dlls in that zip file.  I tested with those a few hours ago and it worked for me.

**Comment by PengBooz** [comment]
It works for me as well. Thanks!
