### ISSUE TITLE
Adelphel second dash incorrect sometimes

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#4390]
See: https://www.twitch.tv/videos/1475385585?t=2h12m5s

(cc @valarnin)

**Comment by valarnin** [comment]
> Additionally, this adds a trigger for left/right movement depending on boss movement ***(the logic on this could use a double-check)***.

Emphasis added. Probably I got left vs right backwards on some cases, since I didn't have all 8 possible mechanic combinations handy. I don't think I even had a pull for each of N/E/S/W starting positions, it was almost always two of the four (west KB and south KB) for my groups.

Should be as simple as inverting the heading comparison on whichever ones aren't calling out properly, but I don't go back in again to get more logs for a bit.

```ts
          case 1: // East
            if (heading < -1.57)
              return output.left!();
            return output.right!();
```

**Comment by quisquous** [comment]
Yeah, I think the logic on West is backwards.  However, I'm not sure that heading is reliable here.

62E9 is the Grinnaux jump to the middle, so this finds the first 62CE line after a 62E9 and gets its x, y, heading.  I did confirm that 100.00|122.00|3.14 exists in a log as the first heading in a set of dashes, so I think this needs to be converted to getCombatants, perhaps?

```
$ grep "|\(62CE\|62E9\)|" *.log | grep 62E9 -A 1 | grep 62CE | cut -d'|' -f 41,42,44 | sort | uniq

100.00|122.00|2.36
100.00|122.00|-2.36
100.00|122.00|3.14
100.00|78.00|0.00
100.00|78.00|0.79
100.00|78.00|-0.79
122.00|100.00|-0.79
122.00|100.00|-1.57
122.00|100.00|-2.36
78.00|100.00|0.79
78.00|100.00|1.57
78.00|100.00|2.36
```

**Comment by quisquous** [comment]
As this trigger got removed, this isn't an issue anymore. I don't think I'm going to get around to adding this, and so I'm going to close this issue for now.  (If anybody wanted to add this, it would be welcome, but I'm unlikely to be in DSR again any time soon.)
