### ISSUE TITLE
O7S Timeline Sync Paste Ultros / Ink

### ISSUE THREAD

**Issue by xDemonessx** [quisquous/cactbot#44]
428 "Paste Ultros" sync /:Guardian:2776:/
429 "Ink" sync /:Guardian:277D:/

I'm not sure whats up but it ever so slightly desyncs around this part. I was seeing the timer with 10 seconds left, but ink would go off. This is post Virus phase.

It would pick up and sync up again later, but heres the skill IDs fro the log:

[21:51:06.219] 14:2776:Guardian starts using Paste Program on Guardian.
[21:51:11.000] 00:282b:The Guardian uses Paste Program.

I think just adjusting the duration here to be 5 seconds instead of 10 will fix it, if possible.

**Comment by quisquous** [comment]
Do you have a video of this?

cc @xephero

**Comment by xDemonessx** [comment]
I don't unfortunately, I'm also unsure if its related to latency at all, but it was definitely at least 5 seconds off (it got me killed the first time i noticed it- I was dead with a timer of 4 seconds left).

I'm unfamiliar with how logs are supposed to look, but the timing seems out of order:

![image](https://user-images.githubusercontent.com/3487603/36014946-e6e116da-0d31-11e8-8514-0412c4216a49.png)

Shouldn't [21:51:06.219] 14:2776:Guardian starts using Paste Program on Guardian. 
Happen after [21:51:05.000] 00:282b:The Guardian readies Paste Program. ?

It also happened at this time in another log:
[22:16:17.286] 14:2776:Guardian starts using Paste Program on Guardian.
[22:16:16.000] 00:282b:The Guardian readies Paste Program.
[22:16:22.290] 15:4001C043:Guardian:2776:Paste Program:4001C043:Guardian:3A:0:1C:27768000:0:0:0:0:0:0:0:0:0:0:0:0:9324782:18731055:12000:12000:1000:1000:3.494263:-3.494385:0:9324782:18731055:12000:12000:1000:1000:3.494263:-3.494385:0:
[22:16:22.000] 00:282b:The Guardian uses Paste Program.
[22:16:23.171] 16:4001C04A:Guardian:277D:Ink:1067F425:Character Name:750003:5D5A0000:1C:277D8000:0:0:0:0:0:0:0:0:0:0:0:0:33609:39384:20352:18679:1000:1000:0.1278049:-18.94219:0:57250:57250:0:0:1000:1000:-5:-5:0:

**Comment by xephero** [comment]
I see the problem. 

`374 "Magitek Ray" sync /:Guardian:2788:/
377 "--untargetable--" sync /:Guardian:2937:/
384 "Chain Cannon" duration 2
400 "Main Cannon" sync /:Guardian:2790:/
401 "Radar" duration 2
403 "--targetable--" sync /:Guardian:2938:/
412 "Arm And Hammer" sync /:Guardian:2789:/
420 "Diffractive Plasma" sync /:Guardian:278B:/`

The time from Untargetable to Main Cannon should be 13 seconds instead of 23, going from random fflogs browsing. Probably just a math error when I was making it from logs.

In fact, every flight window shares that timing, so there's a few other instances that should be nudged a bit too. (486 has it at 11, 1375 has it at 12). Luckily, this probably won't be a thing in the future since a script is doing the math for me now, but I can fix those tonight and PR it.

**Comment by danakj** [comment]
> Shouldn't [21:51:06.219] 14:2776:Guardian starts using Paste Program on Guardian.
> Happen after [21:51:05.000] 00:282b:The Guardian readies Paste Program. ?

"starts using" comes from the xiv plugin reading network data
"readies" comes from the game logs

game logs have a latency of a few hundred ms to a second, compared to network logs which are fast.

**Comment by xDemonessx** [comment]
> game logs have a latency of a few hundred ms to a second, compared to network logs which are fast.


Thank you for the explanation!
And thank you for the fix!!
