### ISSUE TITLE
Timeline about BA (CN)

### ISSUE THREAD

**Issue by Bluefissure** [quisquous/cactbot#440]
I'm currently working on the timeline of eureka hydatos, more specifically, the Baldesion Arsenal and find something strange.
- First of all, the complex regex of starting the `Art` (which is `亚特` in Chinese) combat [here](https://github.com/quisquous/cactbot/blob/master/ui/raidboss/data/timelines/eureka_hydatos.txt#L19) cannot be matched in the game nor `test_timeline.py` (maybe the timeline translation regex replacement crashes it?), so I change it to a simple `/:Art:3956:/`. Since Art only uses action 3956 at the start, I think this will not cause anything incompatible. Idk whether Owain has the same problem, just change it too.
- Then there is the name of Ozma, I'm not sure whether it's caused by some wrong translations mapping, but "Ozma" is "奥兹玛" in Chinese, and "Proto Ozma" is "奥兹玛原型". When searching `:奥兹玛:`(`:Ozma:`) in the ACT log, I got nothing. and the actions used in the sync sentences from the [timeline file](https://github.com/quisquous/cactbot/blob/master/ui/raidboss/data/timelines/eureka_hydatos.txt#L251) can only be matched by `:奥兹玛原型:`(`:Proto Ozma:`).

So these two cause conflict between [Chinese BA timeline](https://github.com/Bluefissure/cactbot_cn/blob/master/ui/raidboss/data/timelines/eureka_hydatos.txt) and the original one, do you have any log file of global server (with the combat of BA) for me to check what's going on?

Thanks in advance😅

**Comment by quisquous** [comment]
Re: complex regex.  Unfortunately, you have to do it that way, or one of the pair's abilities will start the timeline on the other.  You can see Art doing stuff from Owain's room, but you can't see the people they are doing it on.  So, it's trying to find Art using an ability, but having an empty target, which is what happens when you are out of range of the target.

Re: Ozma.  I am not sure what you mean.  There's only `Proto Ozma` and `Ozmashade`.  There is no `Ozma` mob in Eureka Hydatos.

Here's a BA log: https://drive.google.com/open?id=1MiBSjo1aA4NkO4OTcLONj95iIOE7AfZi

**Comment by Bluefissure** [comment]
> Re: Ozma. I am not sure what you mean. There's only `Proto Ozma` and `Ozmashade`. There is no `Ozma` mob in Eureka Hydatos.

So this is exactly what I'm confusing, you use `Ozma` to sync the timeline:
https://github.com/quisquous/cactbot/blob/master/ui/raidboss/data/timelines/eureka_hydatos.txt#L251

**Comment by quisquous** [comment]
Sorry for my confusion.  It's been a while since I've looked at this.  You are right.  There are hidden mobs called Ozma that do those abilities, and that's what the syncs are on.

Try importing the BA log with the 1.7.2.5 plugin and see what lines are there.  I am really busy at the moment and am going out of town for a week, so I can't dig into this myself at the moment.

Let me know what you find, and I'll see if I can help.

**Comment by Bluefissure** [comment]
Okay, I'll take a look at this, thank you

**Comment by Bluefissure** [comment]
I think I found the problem, in the global log we have
```
21|2019-02-24T14:39:37.1920000-08:00|40001529|Ozma|37AB|Unknown_37Ab|10660901
21|2019-02-24T14:39:37.1920000-08:00|40001528|Ozma|37AB|Unknown_37Ab|106AA42A
21|2019-02-24T14:39:37.1920000-08:00|40001527|Ozma|37AB|Unknown_37Ab|106A82F0
```
when (Proto) Ozma attack, but in Chinese log, it becomes
```
21|2019-07-05T15:42:32.6520000+08:00|40001B38|奥兹玛原型|37AB|攻击|1013D659|
21|2019-07-05T15:42:32.6520000+08:00|40001B37|奥兹玛原型|37AB|攻击|102F42D3|
21|2019-07-05T15:42:32.6520000+08:00|40001B36|奥兹玛原型|37AB|攻击|101F9191|
```
so it's actually translated from `Proto Ozma`, so weird.

Maybe I should just map `Ozma` to `奥兹玛原型` in hydatos
