### ISSUE TITLE
[DSR] Titan Gaols-esque extended text popup for DSR Meteor Role Groups (Sanctity of the Ward)

### ISSUE THREAD

**Issue by SamosaWave** [quisquous/cactbot#4411]
Reference
https://github.com/quisquous/cactbot/blob/main/ui/raidboss/data/04-sb/ultimate/ultima_weapon_ultimate.ts#L296

## Summary

Have Cactbot print out sorted names for meteors head markers in Sanctity of the Ward simalar to Titan Gaols.
Ex. (DPS) Player 4 - Meteor, Player 1 - Meteor, Player 8, Player 3.
It's a pseudo Titan Gaol-esque text.

If all 8 players have cactbot they can agree on a priority of where Meteor Role group goes. The standard is North/South for marked players. So with the sorted text a group can agree on positions dependent on the text.
Ex North(Player 4 - Meteor), South(Player 1 - Meteor), West(Player 8), East(Player 3)

If all players don't have cactbot, proceed as normal but the extra information of who got which mechanic is helpful.

**Comment by quisquous** [comment]
That's a lot of information to print out for this one.  I think one thing that would be about the same amount of information would be to just say who the meteors were on, so that it could say "DPS Meteors (Player1, Player2)".  Then that would be enough information for the meteor role (both meteor markers and non-meteor markers) to figure out where to go based on a priority system.

If you really wanted a full text print here, I think that might be more suited to a user trigger (which could just tell everybody where to go directly.)

**Comment by SamosaWave** [comment]
Just the meteor players is fine as well.

> That's a lot of information to print out for this one. I think one thing that would be about the same amount of information would be to just say who the meteors were on, so that it could say "DPS Meteors (Player1, Player2)". Then that would be enough information for the meteor role (both meteor markers and non-meteor markers) to figure out where to go based on a priority system.
> 
> If you really wanted a full text print here, I think that might be more suited to a user trigger (which could just tell everybody where to go directly.)
