### ISSUE TITLE
Raid Emulator not working

### ISSUE THREAD

**Issue by Azruine** [quisquous/cactbot#4482]
## Description

Raid emulator freezes while loading long logs (over 10 min), 

## Additional information

Working properly for short logs like 2~3 min

it worked properly before 20 hours ago

**Comment by valarnin** [comment]
I'm not having any issues loading a TEA clear in raidemulator with the latest github.io build. Can you provide more details?

1. Importing the encounter from file, or loading the encounter from the bottom tab?
2. Language and version of the log file (e.g. `English`, `2.6.5.1`; from the `253` and `249` lines at the beginning of the log file)? Or if you can't pull the version line because you're loading an already imported encounter, what game version was it created against?
3. If importing. was `(DEBUG) Log all Network Packets` enabled?
4. Display language set in `Plugins > OverlayPlugin.dll > Cactbot Config > General > Display language`?

**Comment by Azruine** [comment]
seems like solved in 26.8, close this. thank you.
