### ISSUE TITLE
no EW cactbot folders

### ISSUE THREAD

**Issue by fgmoo** [quisquous/cactbot#4597]
Hello!
I wanted to manually edit a DSR trigger to not be role based so I have access to it as DPS, but my AppData\Roaming\Advanced Combat Tracker\Plugins\cactbot-0.19.8\cactbot\ui\raidboss\data does not have any folder with EW triggers. 
The folders are usually 00-misc, 01-arr etc up to 06-ew but mine ends on 05-shb, even though my ACT and cactbot are updated, with triggers working just fine on DSR. Any ideas where those triggers might be stored? 

Thanks!

**Comment by quisquous** [comment]
A long time ago, the files were loaded directly.  At some point, we switched to webpack and all the trigger files are bundled together now.  The old files are still there, which is why you only have old ones.  That said, you shouldn't edit the triggers directly, as they'll get overridden by the next update.  You can add a js file in your user directory to override a trigger.  Take a look at https://github.com/quisquous/cactbot/blob/main/docs/CactbotCustomization.md#overriding-raidboss-triggers

(Can I ask which trigger, out of curiosity?)

**Comment by fgmoo** [comment]
Thanks for the help!
I want to use the Phase 6's Hallowed wings and Plume trigger but looking at the source it looks like its role set to tank so I assume it only shows to tanks? So I wanted to see it as a dps aswell, to help me getting close or away from the dragon.

**Comment by fgmoo** [comment]
now thinking about it I'm not sure if the data.role=tank means its a trigger supposed to work if you're a tank only or its just the trigger setting up the dragon is aiming at the tank and getting that info to say close/far

**Comment by quisquous** [comment]
If the head is down (aka tanks near party out) then it will tell tanks to be near and non-tanks to be far.

**Comment by quisquous** [comment]
I think there is nothing more to be done here on my end.  If you need assistance setting up a custom trigger, I would recommend visiting the act ffxiv discord.
