### ISSUE TITLE
Innocence EX

### ISSUE THREAD

**Issue by quetzalsly** [quisquous/cactbot#466]
First of all I want to say thanks for making cactbot, its an awesome tool for raiding.

I was just wondering if the innocence extreme script was complete to your satisfaction?
To me it feels like its missing a lot of things.
The fast swords and instakill mechanics when the four orbs come up are some of them.

The titania extreme script is perfect, every single mechanic has a clear warning.
But it feels like the innocence one is lacking, I keep dying because there isn't enough warning.

I am kinda bad at the game so I rely on tts to give warnings. I don't see why this is a bad thing because I don't have that much hours a day to practise this encounter to get it perfect without any warnings.

**Comment by quisquous** [comment]
Thanks for the feedback about triggers!  I get very little feedback about them other than angry people on the internet saying that it's useless and too chatty.

I felt a little bit like the timeline covered the swords returning and so I didn't add a trigger for them.  How do you think that would best be conveyed?  It's the kind of thing where even if you have a warning, it's kind of too late because they appear so fast.  You have to just stay out of it the whole time.  Would you want a warning if you had a mechanic (orbs or tethers) while swords were in play?

I thought I added triggers for most of the orb-related mechanics.  Which other ones would you like?

**Comment by quetzalsly** [comment]
I don't think it's too chatty at all! In fact for titania its perfect, you get a reminder for each phase and the lightning tether things are counted too which is superb. I got my weapon thanks to cactbot reminding me all the stuff.

Ideally a reminder for each 'phase' or cast would be the best option I think.
eg: "Get ready to dodge"

For me looking at the timeline is too distracting as I am also doing an MCH rotation :)
I am thinking something like "swords incoming, remember position, prepare for second swords behind"
"prepare for someone aiming line" phase
Something along those lines, so each step is easy to prepare for, and there is no remembering required.

But I guess somehow shorten those speeches so its easy to tts, sorry I can't come up with specific text :D

**Comment by quisquous** [comment]
Hmm! I'll see if I can add a few more things.  I definitely watch the timeline a lot (but maybe that's because I'm tanking and want to pre-pop cooldowns) and so sometimes I put things in the timeline instead of in triggers.  The starbirths are all named there in terms of what they are, but maybe they could be triggers too.

Swords seem harder, because there's just very little time to dodge them.  I'll see if I can add some more.

**Comment by quetzalsly** [comment]
Maybe add like a "Swords again soon" so people remember there are two sets of swords, I always see people dying to that even in so called farm groups haha.

**Comment by quisquous** [comment]
Ok, I think this is probably good now.  Let me know if you think more callouts would be helpful.
