### ISSUE TITLE
choose TTS engine (Use ACT for TTS or "Use Cactbot for output regardless of ACT hook config")

### ISSUE THREAD

**Issue by FrUct1s** [quisquous/cactbot#4901]
Hi,
I know the "Use Browser TTS" checkbox has been removed last year around April and there were issues implementing other TTS solutions and I understand most people don't need to use this.

Would love a custom User File config option that is accessible for people like myself to just activate it anyway (disregarding iframes, RAM and so on)

My Problem:
Wanna use specific TTS in a Discord bot (Triggernometry has the option to funnel TTS through ACT->Discord or to use Triggernometry for audio output = private TTS for myself without Discord Bot)
But I still would want to use Cactbot TTS for myself as well.

Is there already a config I can set in the files to reenable BrowserTTS to circumvent DiscordBot to call out all my personal TTSes?

If not - is it possible to use Triggernometry's TTS instead of ACT's somehow? Or are you already working on bringing back a TTS solution other than ACT's?

![Screenshot 2022-10-01 170944](https://user-images.githubusercontent.com/58904408/193415928-66312a6e-62dc-48fc-a7c2-9d7adf2f70d0.jpg)
![Screenshot 2022-10-01 170912](https://user-images.githubusercontent.com/58904408/193415930-b0515799-e874-4be5-ae2e-eb153f93750f.jpg)

**Comment by quisquous** [comment]
There's sort of three paths here:
1) [removed by #2870] a hacky attempt to call Google's TTS service with undocumented parameters that stopped working due to some changes on Google's end; I don't want to support this but I suppose you could attempt to make this work locally
2) ACT TTS (currently what's used when cactbot is being used as an overlay)
3) `window.speechSynthesis` (currently what's being used when cactbot is being used directly in a browser that supports it).  I'm pretty sure this only works in a real browser, which provides the voices and not in CEF.

From cactbot, it means there's not a "browser tts" option when you're inside an overlay from ACT.

It looks like somebody has found a solution in #2860 (final comment there), but it requires building OverlayPlugin without web security on, which we're not going to do, for obvious reasons.  I think this is a "you might be able to get this to work, but you're going to have to make it work yourself" sort of problem.

In general, cactbot triggers have not been written as a "raid call for the entire team" sort of thing even if it sometimes works that way.  I'd recommend doing https://github.com/quisquous/cactbot/blob/main/docs/RemoteCactbot.md for anybody who needs callouts themselves and are on a console rather than piping through discord.

(cc @panicstevenson due to past expertise)

**Comment by FrUct1s** [comment]
Thank you very much!
I totally forgot about remote Cactbot!
That basically solves my issue anyway :)
Thanks again for this in depth explanation.
