### ISSUE TITLE
Question about timeline

### ISSUE THREAD

**Issue by quetzalsly** [quisquous/cactbot#494]
Is it possible to make the timeline scale better for 4k monitors? like a 200% increase?
Also is it possible to change the name's of the timeline to tts text? like:

For example during progress I keep hearing 'protean' but on the bar its something else. so now I have to correlate those names in my head. A simple config boolean could switch those texts?

On a sidenote, for e2s, is it possible to add the 'hand' callouts more in advance? I have been in pugs for last 8 hours and all the time someone always dying to that knockback, they probably don't even use cactbot, but at least it would help the people who do.

**Comment by JLGarber** [comment]
You can probably do something similar to what Quisquous described in [issue 420](https://github.com/quisquous/cactbot/issues/420). Basically, you create a file called "raidboss.css", drop it into the cactbot/user folder, and then add the following to that file:

```
body {
  transform: scale 2;
  transform-origin: 0 0;
}
```

Adjusting _transform: scale_ will change the size to whatever you want.

For the TTS callouts, do you have any other addons handling that alongside Cactbot? I'm not seeing any TTS options by default in the [latest Cactbot trigger file](https://github.com/quisquous/cactbot/blob/2fffe0f47597e9afe9d66af16da7c1b6cf15f83b/ui/raidboss/data/triggers/e2s.js#L93). That link takes you directly to the Protean callout, and there's not a default TTS option there. If you mean "change the text in the timeline", that's doable, but I don't believe there's currently a way to avoid having to do that manually each time Cactbot updates.

The [Hand of Erebus callouts](https://github.com/quisquous/cactbot/blob/2fffe0f47597e9afe9d66af16da7c1b6cf15f83b/ui/raidboss/data/triggers/e2s.js#L116) can't be faster, unfortunately, since they fire the moment the game starts using them. It would be possible for you to set up a timeline trigger to notify you "hey, be ready to watch for this", but until the moment Cactbot notifies you whether it's Rage or Hate, there's literally no way to know which it will be.

**Comment by quisquous** [comment]
You can replace the timeline text if you want if you add something like this to your **cactbot/user/raidboss.js** file:

```
Options.Triggers = Options.Triggers || [];
Options.Triggers.push({
  zoneRegex: /^Eden's Gate: Descent \(Savage\)$/,
  timelineReplace: [
    {
      locale: 'en',
      replaceText: {
        'Doomvoid Cleaver': 'Protean',
      },
    },
  ],
});
```

This should probably do the trick?

**Comment by JLGarber** [comment]
Ah, that makes sense. I didn't have time to go through the documentation, and I wasn't sure whether that construct would work. That is VERY good to know.

**Comment by quisquous** [comment]
Also, in general I try to make cactbot's knockback callouts only come 5 seconds in advance, so that if you see them, you can always hit your knockback ability and never get hit.  If it warned you earlier, I worry that people would have it wear off ahead of time.

Is there anything else that needs to get answered here, or is this all sorted?

**Comment by quetzalsly** [comment]
The snippet JPGarber posted does not work for me, I created that file in user directory but it did nothing.

**Comment by waydownthehole** [comment]
I mentioned this on another issue but I'll say it here too in case it's useful. 

This didn't seem to work for me like quetzalsly, but editing the html file in the UI folder and changing the body tag to 
`<body style="zoom: 130%;">` seemed to work for me in either jobs or raidboss.

**Comment by quetzalsly** [comment]
The only thing that worked for me was editing the actual css file (not the one in user).

**Comment by quisquous** [comment]
Editing the one in user should work.  That's very surprising that it wouldn't.  Are you putting that exact snippet in a file called `user/jobs.css`?

**Comment by waydownthehole** [comment]
I tested it again with just that snippet on it's own in a user/jobs.css and it doesn't change. I know the user file usually works since I use it to do [this](https://i.imgur.com/YAIntTk.png) normally.
I tried it inside the same user/jobs.css and it still changes the bars but does nothing for scale.
Changing the ui/jobs/jobs.css and appending that snippet doesn't work either for me, but I could be missing something since I'm not very clued in on the technical aspects of this.
It still works fine editing the body tag in ui/jobs/jobs.html but the downside is overwriting with new versions means you have to re-edit it.

**Comment by quisquous** [comment]
Is there anything else that needs to get solved here?

I'm still surprised that user/jobs.css doesn't make any difference for you.  You may need to put `!important` on the css lines.
