### ISSUE TITLE
Unfriendly TTS symbols

### ISSUE THREAD

**Issue by quetzalsly** [quisquous/cactbot#505]
E3S for example has very annoying "slash" sounds, if you change these to commas it speaks them perfectly. It would be really nice to change that and possible also look at other problematic files with a grep? like >= / all of those cause problem TTS. Thanks!

**Comment by panicstevenson** [comment]
@quisquous and I had talked about this a little, and I think we agree that the callout in question `front left / back right` can use some work in general. If you have any proposals for making the call out cleaner/more succinct without the use of any symbols I think we'd be happy to go with that.

As for the overarching intent of this issue, I agree. It has been mentioned for other turns as well.

**Comment by quetzalsly** [comment]
i tried it with a comma and it works well enough, personally i would just keep it like that. Cactbot does not know where you are so it can't narrow it down to one callout, but you simply check "Am i front or back?" and listen for the one that applies to you.

**Comment by panicstevenson** [comment]
Looking from the list of javascript files that hit `^\W+en: '.*[/<>=].*',$`, there's a lot of things that have had slashes in them. Testing out different text to speech options, they all handle slashes a bit differently; some read every slash, some never read the slash, and some won't read it if there's no spaces in the slash.

For things like `In/Out, then Water Positions` in Titania, has this procced the same effect?

**Comment by quetzalsly** [comment]
I dont remember having problems with titania but im not sure, maybe the tts was short enough not to overload my brain haha. Also I don't have windows media player installed so I can't use that API, I use the other API which can only output 1 voice at a time. I imagine a lot of people don't use windows media player anymore so the best solution would just be to fix it for everyone universally.

**Comment by quisquous** [comment]
Yeah, I think the solution here will just be to do some ad hoc replacement before playing the tts.  Maybe `/` turns into nothing, and `=>` turns into `then`.  I think there are some things where I say `go east =>` or `<= go west` and maybe I can clean those up and be consistent.

Are there other bad symbols?

**Comment by quetzalsly** [comment]
I can't think of any other bad symbols right now. Also I don't want to open a new issue but in e3s there was a change which makes the callouts awful. These 4 occurances: 'left front / back right'. First of all it has the slash and second of all it is very very hard for the brain to comprehend this because it is inconsistent! Simply changing it to 'front left, back right' works perfectly. So your brain first understands if its front or back and then which side.

**Comment by JLGarber** [comment]
On the multiple-issues thing, I can't speak for Quisquous, but multiple issues is generally how these things are expected to work. (One new issue for each new problem/question.) This way the maintainer has a definite end goal for each issue. So unless Quisquous prefers otherwise, go ahead and keep opening new ones.

As for the E3s thing, there's no reason for it not to be consistent. That's worth setting up a pull request for. In fact, if you've noticed other places where there's that sort of inconsistency with the order, you could change them all. Or, if you aren't comfortable doing that directly, you could go through the encounters, make a list of situations where this comes up, and open a new issue with that list so that someone can go through and include it themselves.

**Comment by quisquous** [comment]
I fixed the E3S ordering.  I'll probably just add user config for myself to make it say merely "right" or "left" instead of imposing that on everybody.

I think this is all fixed, so I'm going to close this now.
