### ISSUE TITLE
Timeline is broken for A6S, there is no timeline after robot 2

### ISSUE THREAD

**Issue by rrbailey89** [quisquous/cactbot#5059]
Timeline functions great for robots 1 and 2. Timeline for robots 3 and 4 does not display. Timeline for robots 3 and 4 did exist several updates ago but was broken at some point.

**Comment by quisquous** [comment]
@JLGarber did you say you had looked into this?

**Comment by JLGarber** [comment]
Yes. Granted, that was in patch 6.25, but there's nothing substantive that should have changed. I also looked at the text replacements and none of them seemed out of place, so it's *probably* not a language issue.

@rrbailey89 can you verify your language settings, just in case there's something weird going on with a non-English text replacement? And can you attach a network log of a run where the syncs didn't happen?

Oh, and it also occurs to me, are you using a chatlog-modifying Dalamud plugin of any sort?

**Comment by rrbailey89** [comment]
> 
[Network_26700_20221106.zip](https://github.com/quisquous/cactbot/files/9957494/Network_26700_20221106.zip)

My game language is English. I use the NoSol plugin that I suppose modifies the chat log.

I had to zip the network log due to its size.

**Comment by JLGarber** [comment]
Okay, so one thing that immediately jumps out at me is that you have no `00` log lines present in that log. Do you have "hide chat log for privacy" enabled in ACT? Timelines do require `00` lines to be available to make zone seal syncs work, and because of how A6 works on both difficulties, timelines are started with zone seals rather than combat engagement.

That being said, it's *probably* possible to make some changes to the timeline that would make it less reliant on memory-only syncs. I think we can safely assume that if a non-Blaster robot is attacking, we can sync to that robot's timeline section. I'll do some poking.

**Comment by rrbailey89** [comment]
> 

Welp... I suppose it may very well have been a change I made as opposed to a recent update, I did recently tick the "hide chat log for privacy" box in ACT.

**Comment by JLGarber** [comment]
Let's try that and see whether it works for you in the short term, since that at least would be a solution. @quisquous if this is the issue, I'll look into adding network line syncs to each robot to avoid this issue going forward for people who hide chat.

**Comment by quisquous** [comment]
No, I think in general cactbot intends for chat to be on, and there's a lot of other things to fix if we wanted to make it work in general without it.
