### ISSUE TITLE
raidboss: use network log lines in timeline files

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#5145]
Currently timeline files are the only things still using processed log lines and not network log lines.  They're also using regexes directly, which is a little bit awkward.  It'd be nice to switch timeline syncs to using NetRegexes in some form, however it's not clear to me what this format should look like:

```txt
# currently
1000.0 "stuff" sync / 1[56]:[^:]*:thing:32:/

# options
1000.0 "stuff" sync { type: "ability", id: 32, source: "thing" } # json
1000.0 "stuff" ability { id: 32, source: "thing" } # keyword per line type, shorter
1000.0 "stuff" sync:ability { id: 32, source: "thing" } # hybrid
1000.0 "stuff" sync "ability,id,32,source,thing" # csv???
```

These are certainly more readable than the original, but I'm not sure I'm really sold on any of them.

Other thoughts I'm having are that "ability" is so common that maybe it's the default and doesn't have to be specified, for brevity?

cc @JLGarber @valarnin @panicstevenson

**Comment by JLGarber** [comment]
Whatever we land on, I sort of think it should prioritize human-readability. Given that we have infrastructure for NetRegex parsing already in place, it will be "trivial" to parse whatever we come up with. One of the nice things about the current structure is that it's very compact for a human reader, and it would be nice if we could mostly hold to that. "CSV"-style seems like it would make life harder if the source ever contains a separator, but it would definitely be the most compact.

I wouldn't mind stuffing *everything* into the NetRegex object, but that would potentially consume a lot of horizontal space. If we're willing to accept that timelines may just end up being wide, however, that's not really a concern. If we do want to keep horizontal space contained, I would vote for option 2, "keyword per line".

Since this is already going to be a breaking change, we might also want to think about changes to how timeline keywords are handled. For instance, maybe we could split `window` out into `windowBefore` and `windowAfter`. I would *like* to start enforcing a deliberate keyword order regardless, so that, say, `window` parameters are always before `jump`s or `loop`s if they exist. (This might need to be a stylistic thing only, but it would still be nice.)

**Comment by Souma-Sumire** [comment]
Option 1 looks nice :D
