### ISSUE TITLE
Raidboss: AoE triggers should play for tanks and casters as well

### ISSUE THREAD

**Issue by Webberjo** [quisquous/cactbot#526]
Tanks have Reprisal and casters have Addle. Mitigating AoE damage is just as important as healing it.

**Comment by quisquous** [comment]
I do agree that mitigation is important, but I think I haven't done this because it's felt very noisy.  (I'm a tank, but usually I just add my own cooldown suggestions to my personal timeline as needed.) 

Addle is a 90s cooldown, and reprisal is 60s, and aoes happen way more often.  So for healers, it feels a little like they need to do something for every aoe, and casters/tanks only infrequently.  I have been a little resistant to telling people where to use cooldowns (although there is at least one place I tell people to use feint).  Maybe that's wrong, and I should have more feint/addle callouts on tankbusters too?

I don't know.  I'm a little torn on the noise vs usefulness level here for tanks and especially casters.  Maybe it makes sense for really big ones, like earthen fury in phase 3 of e4s? (Do other tanks/casters have feelings here?)

**Comment by Webberjo** [comment]
Don't forget 2 tanks means 2 Reprisals every 60 seconds.

**Comment by Tsunayoshi** [comment]
i may undstand that for tanks since beside reprisals there also other cds like shake it off, pala wings eg.
but for dps also faint is a cd that works for physical dmg and addle only for magical dmg.
so beside that it should be seperated on the type of dmg - dps aim for better dps and keep using it for bursts.
so from my view as sch healer and now going to dnc. i will check timeline and speak with our brd when we use our cds. so i only need the timeline. for healer its 100% needed since without shield and being topped ppl may die. but migations also maybe not needed. so tanks i am like 50/50.

what would be useful is something to see the cd of the other tank. so u wont use both reprisal the same time. same for samba troub and tactican

**Comment by Webberjo** [comment]
I've already written a few hundred lines in my raidboss user file to implement what I want. The fact we're able to do this is a huge boon and I commend whoever implemented the feature.

**Comment by Tsunayoshi** [comment]
i am sry as a dps i think its more distracting than helpful. i dont need to see every single aoe with a big sound, while i can only do something every 2-3minutes. its on the timeline, u can even use that to hit up to 3 aoes with 1 cd...

if someone want to implement, please add a switch so ppl who want that much information can enable it if they want.

**Comment by quisquous** [comment]
Thanks for all the input.  I'm going to try to consolidate a lot of the logic about what to say for triggers and when to say it into a few classes (so it's not duplicated), and in general I think I will move to telling tanks and folks who can addle about aoes.
