### ISSUE TITLE
TOP High-Powered Sniper Cannon Fodder callout

### ISSUE THREAD

**Issue by gituubu** [quisquous/cactbot#5320]
For TOP       id: 'TOP High-Powered Sniper Cannon Fodder'

Could we an option to adjust the callout for the other player that has the stack marker, or unmarked matching your debuff?
It has more value than calling on the other 2 stack options which is what it currently does for the conga line method.
(Similar to P8sP1 callouts)

**Comment by quisquous** [comment]
The reason it doesn't call your partner because I try not to have calls that say "don't do X".  This would be a "don't stack with X" kind of call, and even "stack (w/X)" or "stack (partner is X)" both sound like it's asking you to stack with X and not avoid X.  It seemed better to have a "stack with one of these two people", especially for a mechanic that has so much time to resolve positions correctly.

Are you doing a priority system there to figure out where to go and that's why you need your partner known?

**Comment by gituubu** [comment]
Yes, on the conga line method. The left most with stack and unmarked go left, and the right most with stack and unmarked go right. If you are stack, you dont need to worry about who is stacking with you. Only who the other stack person is so you need to go left or right. 

This is very similar to DSR and P8S methods of resolving flex mechanics.

**Comment by gituubu** [comment]
Could we just have the like partner stored in a variable? so instead of player1 player2, have a variable stored for samedebuffplayer?
