### ISSUE TITLE
Meta: 6.4 content organization

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#5405]
Just to try to prevent stepping on toes, if you're thinking about handling any particular piece of content, please respond here just so other folks know.

- Aetherfont (dungeon): @quisquous 
- Voidcast Dias (trial): ???
- Voidcast Dias Extreme (trial): @valarnin 
- P9N (raid): @foophoof 
- P10N (raid): @wexxlee 
- P11N (raid): @JLGarber 
- P12N (raid): @quisquous
- Zurvan Unreal (unreal): @JLGarber

**Comment by quisquous** [comment]
Also, if anybody has time to split the dungeons that changed in 6.4 out into separate files like we have for `sohm_al61.ts`, that would be appreciated.

**Comment by valarnin** [comment]
I'm looking at ex fight, but my parties aren't hitting enrage so I can't do a full timeline yet.

**Comment by quisquous** [comment]
> I'm looking at ex fight, but my parties aren't hitting enrage so I can't do a full timeline yet.

Partial timeline with a TODO is just fine if you don't see one.  I sometimes dig that up from fflogs too, but idk if there's any there yet.

**Comment by quisquous** [comment]
I'm going to also take a stab at the dungeon.

**Comment by JLGarber** [comment]
I will take care of Zurvan Unreal, yes. I might pick up one of the raid encounters depending on how clears go tonight.

**Comment by foophoof** [comment]
I'd be interested in giving P9N a shot, but this is my first time doing a timeline so if you want someone more experienced to try to get it done faster then that's perfectly fine ^^"

(I'll probably give it a try anyways just to learn how this works, so I guess I'll just PR up what I got if nobody else does it first)

**Comment by valarnin** [comment]
> I'd be interested in giving P9N a shot, but this is my first time doing a timeline so if you want someone more experienced to try to get it done faster then that's perfectly fine ^^

More people helping to develop for the content is always appreciated!

The skeletons for the trigger file and timeline file are already in place, so all you need to do is add to them. See the guides here:
https://github.com/quisquous/cactbot/blob/main/docs/TimelineGuide.md
https://github.com/quisquous/cactbot/blob/main/docs/RaidbossGuide.md

Note that you may need to use `npx ts-node ...` instead of just `ts-node ...` for the helper tools for timeline creation, if you don't have `npx` installed globally.

RaidEmulator can be used to test triggers and such without having to go through the content again, it works fine for every trigger except `getCombatants`-based triggers (Fixes for that soon™). To use raidemulator, run the webpack dev server with `npm run start`, then connect to it via `http://localhost:8080/ui/raidboss/raidemulator.html`. Finally, drag and drop an ACT FFXIVLogs/Network*** log file onto the page to import it, and load it using the pane at the bottom.

**Comment by wexxlee** [comment]
I'm a little short on time until the weekend, but if no one's got P10N/P11N by then, I'll work on those.

**Comment by quisquous** [comment]
> I'd be interested in giving P9N a shot, but this is my first time doing a timeline so if you want someone more experienced to try to get it done faster then that's perfectly fine ^^"

Happy to help explain anything.  @valarnin covered most of it.  I think the biggest suggestion I have is to just make sure you're using the `make_timeline` script (e.g. `ts-node utils/make_timeline.ts -f filename.log -lf` and then `-lf 3` or whatever encounter you select).

The timeline guide is really out of date (sorry). Please ask questions here or in discord if you run into anything.

**Comment by JLGarber** [comment]
I'll take P11N now that Zurvan Unreal is initially taken care of.

**Comment by quisquous** [comment]
I'm going to focus on filling out p10s a little bit more tomorrow.  If anybody has time to work more on it now, there's plenty of stuff on P9S (finishing off a timeline, two minds element callouts, chimerical firestrikes callouts (in terms of kefka-esque wait/run through), even before you get to fancier stuff for some of the other mechanics.

**Comment by wexxlee** [comment]
I'm doing a quick test on a very basic set of golbez normal triggers and timeline, which I should be able to PR in the next hour.  Will try to get some basic oopsy in there as well, but that may have to wait until tomorrow.

**Comment by quisquous** [comment]
I think we're done here.  Thank you everybody!!
