### ISSUE TITLE
Bars not showing up in preview (but alerts do)

### ISSUE THREAD

**Issue by Snsei987** [quisquous/cactbot#541]
- When I start ACT and try to preview (by unchecking 'Lock overlay'), the bars don't show up but the alerts do (ALARM TEXT; ALARM TEXT 2...).

- When beginning a fight, the bars show up perfectly so the issue is only with the preview.

- After a fight, everything in the preview work fine (the bars, the alerts...).

Maybe the init script doesn't load the bars ?

**Comment by Snsei987** [comment]
It appears you need to be in-game for them to show up, is it intended ?

**Comment by quisquous** [comment]
I think I haven't thought too hard about the preview bars.  This probably could be better.  Honestly, the preview alert texts could also give you an explanation of what to do (aka resize and then lock) instead of just saying ALARM TEXT.

If anybody wants to fix this before I do, please have at it.

**Comment by panicstevenson** [comment]
I can't confirm the aspect of needing to engage in combat to have the timelines show up, since they show up for me in or out of combat (ngld). However, I can confirm that you do need to be in game to have the timelines show up. While probably not intentionally left out from the out-of-game preview by design, the reasoning lies within the timeline [attempting to show you what your settings look like](https://github.com/quisquous/cactbot/blob/master/ui/raidboss/timeline.js#L575) instead of statically coded HTML. While probably not necessary, init() waits for information to be propagated up, such as language.

While probably still not a large body of work, it was more than I was expecting when initially looking into this, assuming that test timeline bars just needed to be added to the raidboss.html. Also, while not being able to confirm the necessity of starting combat to get a proper preview, it makes me wonder what the added user value to being able to set up the preview outside of game is.

**Comment by Snsei987** [comment]
Well, if the need to be IG is intentional, it's perfectly fine.

As for why I wanted to view the bars outside of the game, it was purely for the style preview.

I wanted to change the CSS but couldn't log into the game. That's why I would like a default bar no matter the language.
