### ISSUE TITLE
Simplifying Triggers for Locale Regex

### ISSUE THREAD

**Issue by panicstevenson** [quisquous/cactbot#543]
I was wondering what the overall feeling would be to do away with matching the locale regex for logs and instead matching on broader regex. For example:

```
14:3FF1:Leviathan starts using Tidal Wave:
14:3FF1:Leviathan starts using Tidal Wave on person:143918:1092
14:3FF1:利维亚桑 starts using Tidal Wave:
14:3FF1:Leviathan starts using Flutwelle:
14:3FF1:Léviathan starts using Raz-De-Marée:
14:3FF1:リヴァイアサン starts using タイダルウェーブ:
```

can all be matched with `14:3FF1:.+? starts using .+?:` and can be extended to include `(on \y{Name})` as well, if we wanted. Mechanic names and boss names can similarly be substituted out if we wanted that functionality as well.

This, combined with a rudimentary dictionary of common Cactbot phrases plus their translation counterparts (I'm envisioning copy/paste, but it could ultimately live in a map within the code as well), could probably reduce the translation time and effort necessary for fights. An example would be standardizing all raidwide damage to be "aoe" and its non-English equivalents, etc.

The biggest drawback I immediately see is that the ids of the triggers themselves would have to be consistently good, since the mechanic name is no longer within the trigger regex itself. Additionally, anyone looking for `タイダルウェーブ` wouldn't find it since it's now just `.+?` and I'm expecting that the trigger ids will never be non-English just due to tradition at this point.

**Comment by quisquous** [comment]
Agreed on trigger ids just not being non-English.

I think I usually put the ability name in the trigger, mostly for readability and less for the actual trigger text, if that make sense.

I think I would prefer something like `/ 14:3FF1:Leviathan/` in these cases.  I think there are cases where two enemies can use the same ability id? And I think there are some cases of overlap between players and mobs, but maybe I'm mistaken.  Having the name explicitly also makes the regex cheaper, because it doesn't have to backtrack ever and is just a literal string match.  All of the timeline syncs are all of the form `/:Leviathan:3FF1:/` for 15/16 lines and `/:3FF1:Leviathan/` for 14 lines, so cactbot alreayd depends on the "short" version.

I'm not sure what to do to make it more readable.  Maybe the trigger id is enough? Maybe there should be a comment after the regex of `// starts using Tidal Wave`? but that'd be hard to enforce.  Do you have thoughts here?

**Comment by panicstevenson** [comment]
It's a hard line to walk between readability and ease of use -- I guess I don't fully know how difficult it is to translate everything, but it does seem tedious to have to add the regex lines in for every mechanic. However, I don't know that lowering that tediousness actually makes the barrier to entry low enough, since whoever would do the translation would have to either know the ability id or at least the ability name in English still (assuming the id of the trigger is well-written). It was just an idea I was playing around with in my head to hopefully get participation barriers lower and get releases to the other locales faster. But, I don't know if sacrificing readability really helps with that -- especially since the barrier is at least as high as knowing JavaScript, git, and GitHub.

**Comment by quisquous** [comment]
The translations are mostly automatic.  There's a script that pulls things from fflogs and will generate that block at the bottom and then add regexes from that.

Some of them have capitalization issues though (esp French), and so maybe dropping the skill name would help a lot on that end.

**Comment by panicstevenson** [comment]
Oh I see; so, it's still dependent either way on people coming in for the translation of the alert text. I should have `git blame`d before making assumptions. If that's the case, then to me it seems like the regular expressions are roughly as cheap as they're going to get with the added bonus of readability.

Also, on the French note: I assume that it's not possible to titlecase everything since it would take someone fluent enough in French to determine the casing on the moves. Although, it looks like this might be the approach taken by fflogs, since [Multi-taillade Chaotique in E2S](https://github.com/quisquous/cactbot/blob/master/ui/raidboss/data/triggers/e2s.js#L566) has the [T capitalized on fflogs](https://www.fflogs.com/reports/AV7MzChNrLxfRyck#fight=1&type=casts&hostility=1&source=2) and its source, garlanddb, has it [all lowercase](https://www.garlandtools.org/db/#action/16569). And, since https://github.com/quisquous/cactbot/pull/531 looks to have specifically targeted the capitalization of one word and not the other, I'm assuming this shotgun approach does not work.

If we dropped the spell names, how would we account for `starts using <spell> on <player>`? With `.*`? The only other major option I can see currently is adding an `i` modifier to the regular expressions so that you can translate automatically and have it run case-insensitive. If we took this approach we'd probably want to see about getting the `u` modifier in as well, for unicode upper/lower-casing, which has only recently been ubiquitously supported.

**Comment by panicstevenson** [comment]
I looked into [regexes.js](https://github.com/quisquous/cactbot/blob/master/resources/regexes.js#L42) and messed around with the modifiers. I added the ignore case and it worked fairly well across all triggers. It looks like [JavaScript supports the Unicode modifier](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp), too; so, we would be able to cover French characters with their capitalized counterparts.

Are there any cases you could think of where this wouldn't be a possible boon? Assuming the speed of the regex isn't hurt too much.

**Comment by quisquous** [comment]
I think I would want to measure a little bit and understand the performance impact of case insensitivity before just turning it on everywhere.

**Comment by panicstevenson** [comment]
Forgive the awfulness of this test:

```python
import time
import re
from pathlib import Path
from collections import defaultdict

test = Path('C:/FFXIVLogs/Network.log')

regexes = {
    "ignore-case": r'(?i)20\|.*\|leviAthan\|3ff[12]\|tidal wave\|',
    "normal": r'20\|.*\|Leviathan\|3FF[12]\|Tidal Wave\|'
}

lines = test.read_text(encoding="utf8").splitlines()

totals = defaultdict(float)
counts = defaultdict(int)

runs = 100

for k, v in regexes.items():
    for i in range(runs):
        start = time.time()
        for line in lines:
            if re.search(v, line):
                counts[k] += 1
        end = time.time()
        totals[k] += end - start
    print(f'{k}: {totals[k]/runs} average seconds per run, {counts[k]//runs} average matches per run across {runs} runs')
```

returned

```
ignore-case: 0.19668999910354615 average seconds per run, 4 average matches per run across 100 runs
normal: 0.1958699893951416 average seconds per run, 4 average matches per run across 100 runs
```

The file in question has 266,070 lines.

Also, just for fun:

```python
import time
import re
from collections import defaultdict

regexes = {
    "ignore-case": r'(?i)20\|.*\|leviAthan\|3ff[12]\|tidal wave\|',
    "normal": r'20\|.*\|Leviathan\|3FF[12]\|Tidal Wave\|'
}

totals = defaultdict(float)

runs = 10000

for k, v in regexes.items():
    for i in range(runs):
        start = time.perf_counter_ns()
        re.search(v, '20|2019-09-06T16:32:41.2490000-07:00|40009077|Leviathan|3FF2|Tidal Wave|40009077|Leviathan|9.70||14ca551f11c3c2eeed8d4feaa72b43b4')
        end = time.perf_counter_ns()
        totals[k] += end - start
    print(f'{k}: {totals[k]/runs} average nanoseconds per run across {runs} runs')
```

gives

```
ignore-case: 1300.69 average nanoseconds per run across 10000 runs
normal: 1122.71 average nanoseconds per run across 10000 runs
```

granted, this test is hardly good enough to prove anything; I'd like to think I have a decent computer and also it's not the same language that cactbot is even written in (although regex should be language agnostic, _buuut_)

Still, fun to code up. I'd like to see if we could get something closer to reality, but this actually makes me feel better than I was feeling when proposing the idea of ignore case modifiers.

**Comment by panicstevenson** [comment]
Talked with @quisquous a bit more on this subject:

```js
var regex = / 14:4105:Titan starts using Weight Of The Land/;
var regex2 = /^.{14} 14:4105:(?:|Titan starts using Weight Of The Land)/;

var testGood = '[03:25:42.637] 14:4105:Titan starts using Weight Of The Land on Titan.';
var testBad = '[03:25:42.633] 15:106E60D1:Chip Chippy:4095:Glare:40016136:Titan:750003:415F0000:1C:40958000:0:0:0:0:0:0:0:0:0:0:0:0:56289349:59121560:10000:10000:0:1000:99.96179:92.14917:2.384186E-07:3.132101:78699:78699:8630:10000:0:1000:109.2089:92.05762:0:-1.562527:.';

var testBad2 = '[03:25:39.365] 1A:106BD324:A Player gains the effect of Physical Vulnerability Up from Titan for 4.00 Seconds.';

function testRegex() {
  var start = window.performance.now();

  for (var i = 0; i < 1; ++i) {
    regex.test(testGood)
    for (var j = 0; j < 100; ++j) {
      regex.test(testBad);
      regex.test(testBad2);
    }
  }

  console.debug(' 14:4105:Titan starts using Weight Of The Land', window.performance.now() - start + 'ms');
}

function testRegex2() {
  var start = window.performance.now();

  for (var i = 0; i < 1; ++i) {
    regex.test(testGood)
    for (var j = 0; j < 100; ++j) {
      regex.test(testBad);
      regex.test(testBad2);
    }
  }

  console.debug('^.{14} 14:4105:(?:|Titan starts using Weight Of The Land)', window.performance.now() - start + 'ms');
}

testRegex();
testRegex2();
```
Gets me:
```
" 14:4105:Titan starts using Weight Of The Land" "0.21500000002561137ms"
"^.{14} 14:4105:(?:|Titan starts using Weight Of The Land)" "0.06999999823165126ms"
```
It seems like `^.{14} `  is a fairly ideal prefix for most regular expressions that Cactbot comes across, given that every log will start with a timestamp and that it can enhance performance by a large margin.

Additionally, `^.{14} 14:4105:(?:|Titan starts using Weight Of The Land)` performs marginally better than `^.{14} 14:4105:Titan starts using Weight Of The Land` and can preserve the readability aspect of the regular expressions for people while not sacrificing anything if the translation is less than perfect (looking at you XIVAPI/FFLogs/everything that doesn't match with the FFXIV plugin)

**Comment by quisquous** [comment]
I am still torn on how to convert regular expressions to use this, though:

1) just be explicit: `^.{14} 14:4105:(?:|Titan starts using Weight Of The Land)`
2) `^` implicitly means `^.{14} `: `^14:4105:(?:|Titan starts using Weight Of The Land)`
3) all regular expressions include `^.{14} `, meaning something like `bows to the striking dummy` must now be `.*bows to the striking dummy`, but everything else is just `14:4105:(?:|Titan starts using Weight Of The Land)`
4) a modification of 2, with a different `regex` vs `legacyRegex` where `regex` behaves like 2 above but `legacyRegex` behaves like the current behavior

I think I'm kind of inclined towards 3, along with just fixing everything up to match that.  It seems easy to document, and seems better than pretending `^` is what it's not.

I think all the timeline regular expressions, e.g. `/:4105:Titan/` and `:Titan:4105:` could be detected via heuristics and then turned into the above form as well if they match as an optimization.

**Comment by panicstevenson** [comment]
I was running through the code, prefixing spaces to already valid triggers in an effort to make the "bad" triggers more visible, and I ran into two cases that I personally hadn't considered:

1. Timeline triggers; these can be easily dealt with, but they will likely never want a time prefix. There's a lot of possible solutions here. The ones that immediately stand out to me:
   1. When you're in the `timelineTriggers` struct, don't prefix the `regex` value
      1. The inverse of this logic may be more profound: only prefix the `regex` values when they're within `triggers`
   1. Explicitly renaming the `regex` to `timelineRegex`

   I think both have their merits, I'm possibly more in favor of the latter since `zoneRegex` != `timelineRegex` != `regex` (or maybe `triggerRegex`? To be continued...)
1. Users with custom triggers; I can't think of a way to deal with these cleanly without adding some logic to figure out if the line "should have a prefix" unless we're fine to introduce breaking changes on the users end or if we treat user triggers as separate beasts entirely

I think a good way to possibly deal with both of these issues is maintain the legacy `regex` while moving optimized regular expressions to `triggerRegex` or something similar.

**Comment by quisquous** [comment]
This sounds great.  `timelineRegex` definitely does not want a time prefix ever, as it's matching against the text in a timeline entry.  Similarly, it never needs a translation as it always matches against the English text.  They're handled by different parts of the code, so this shouldn't be an issue.

I like the idea as well of `triggerRegex` vs `regex` as a way to transition without breaking anybody.  We could even have some deprecation warnings for people using them and maybe eventually get rid of that path.

Having different words for regexes that have different semantics seems like a great direction, and the fact that it doesn't break anybody is also a plus.

**Comment by panicstevenson** [comment]
Just to add to this conversation for the purpose of `/iu` for case insensitive and unicode support. I took the test from above and played with some different data. The first has both flags enabled, compared to the second, with neither flag enabled:
```
" 14:3FF1:Leviathan starts using Tidal Wave" "0.12500002048909664ms"
" 14:4105:Titan starts using Weight Of The Land" "0.10999990627169609ms"
```

Additionally, however; it might not be necessary for this due to `^.{14} 14:4105:(?:|Titan starts using Weight Of The Land)` matching everything, and the text just being for readability. As I started to look through these a little more, I did notice cases like:
` 14:4116:Titan starts using Stonecrusher on (\y{Name})` so it's possible we would not be able to conform everything to this other standard. Additionally, things like `/ 1[56]:\y{ObjectId}:Bomb Boulder:4142:Bury:.*:(\y{Float}):(\y{Float}):\y{Float}:\y{Float}:[^:]*:?$/,` have the entity's name in them, which would still be problematic for case sensitivity.

Also, ***big note***:
The value here for the Weight Of The Land regex is a better benchmark than the one I have above, as I did not originally pre-warm the regexes, so the first one was taking a slight hit. Doesn't change that the optimized one is still better, just not as dramatic.

**Comment by quisquous** [comment]
Collecting some other thoughts from conversations elsewhere.

I think it's inconsistent to have `regex`, `regexDe`, `regexFr` etc but then `infoText` can return a dictionary of languages.  I think it'd be much simpler to just have `regex` with a dictionary.  The translation scripts would need to be updated to handle this.

Mostly, there's a concern just about how much repeating there is in regexes.  It seems maybe better to have something like a set of functions, where a trigger could look like:
```
regex: {
  en: Regexes.startsUsing('3A52', 'Neo Exdeath'),
  // etc
},
```

I think I would still want to support "general" regexes but would want to turn as many as possible into functions like this.  The list off the top of my head would look something like:
```
gamelog
  seals zone?
  unseals zone?
  npc rp text
starts using
starts using on
ability
ability on
ability with position
headmarker
tether
adds combatant
adds combatant with position
removes combatant
gains effect on, for time
loses effect on
```

I think there's some confusion on my part of how capturing would work in such a model.  Would every parameter to a `startsUsingOn` automatically capture, so that matches[1] is ability id, matches[2] is mob name, and matches[3] is whoever it is on? Would you have to specify capturing yourself, e.g. `Regexes.startsUsing('3A52', 'Neo Exdeath', '(\y{Name})'),`? and then matches[1] is who it is on? Would it be better if matches had names? Like, `matches.abilityId` and `matches.targetName`? An unfounded concern is that most things don't match, and maybe auto matching groups is slower? Maybe you need `CaptureRegexes.startsUsing('3A52', 'NeoExdeath')` if you want capturing or some such? A bit more thought needed here.

On a similar note, it might be good to have canned conditions and canned responses? Condition-wise, there's a lot of repeated "do I care about tankbusters" or "do I care about aoes" or "is this on me".  Response-wise, there's plenty of translations that we could build in and just have a function like `Responses.getOut()` or `ResponsesStackOn(matches[1])`.

I'm not sure I have all the answers here, but it does just seem that sort of adding more testing so that regexes are precise is not the answer, and it might be better to have another layer of abstraction here.

**Comment by quisquous** [comment]
Along with the optimization to have every log line start with `^.{14} ` as discussed above.  Then we would also more easily know that a line was a 14/15/16/1B line, and then could only test the regexes that were of those particular types against that line, rather than every regex against every line.  We could almost already do this now as well for anything that started with a space.

**Comment by JLGarber** [comment]
Thanks for pointing this out in 670, I had missed that there was more happening on this one.

For me, as a not-as-experienced contributor, I'm fully in favor of canned conditions/responses. That's a LOT of boilerplate that shows up in pretty much every piece of content in Heavensward on. Having something like this would be AMAZING. When I have more time tonight, I'll go through and make a list of what I've typically found... not painful, precisely, but annoying, in terms of "blah, this is the same stuff *again*".

The one concern I might have is that abstracting all this could cause issues for newer contributors. (As an example, `Responses.stackOn([TARGET])` might be a pitfall in the case of tank-only markers, or markers where [ROLE] shouldn't stack. As a parallel example, you might remember that there was a time when `data.role` was split into `tank`, `healer`, `dps-melee`, `dps-ranged`, and `dps-caster`. I hadn't dug deeply enough into how `data.role` was implemented, and just tried a condition like `data.role != 'dps'`. It was caught during review, but it wasn't obvious to me at all until pointed out. Not insurmountable by any means, but definitely needs consideration.)

On regexes-as-functions, I think it's *probably* worth auto-capturing unless there's a significant performance hit. From the perspective of the contributor, it's irrelevant whether something gets matched but never used, while consistency in indexing for each element seems like a significant benefit. (So for instance, if I were putting together a standard `14:` trigger, knowing that the target will always be `matches[INDEX]` seems like it would make things easy for contributors. It might also make errors easier to catch at review or even programmatically, because we would know that an ability code match should only ever be at such-and-such an index in `matches`.) The downside is that we wouldn't have that consistency across different log lines, but I think it's still worthwhile.

**Comment by JLGarber** [comment]
Alright, crawled through my contributions to date and came up with a short list of the stuff that I've experienced as being annoying boilerplate. First, some basic complete canned triggers:
```
Basic_Casttime_Tank_Buster(Skill_ID)
Basic_Instant_Tank_Buster(Timeline_Regex)
Basic_Casttime_Raid_Damage(Skill_ID)
Basic_Instant_Raid_Damage(Timeline_Regex)
Basic_Everyone_Spread_Marker(Marker_ID)
Basic_Everyone_Stack_Marker(Marker_ID)
Basic_Gaze_Attack(Skill_ID)
```
I can't think of an encounter that doesn't incorporate at least one of these, and combined with appropriate boilerplate responses these should be relatively simple to put together.

Next, the most common responses I've had to write in (apologies for these maybe not being formatted quite as we would want):

```
Responses.standardTankBuster()
Responses.cleavingTankBuster()
Responses.raidDamage()
Responses.spread(Targets)
Responses.stack(Target)
Responses.moveAround()
Responses.stopActions()
Responses.interruptCast(Target)
Responses.killAdd(Target)
```
I think that alone would go a long way toward reducing the annoyance of compiling triggers. Maybe make the responses take a `popup_level` parameter for `infoText`, `alertText`, or `alarmText`?

One other response that's *really* common but at the same time is complex is `Responses.moveToPositionRelativeToBoss()`, and I'm not sure what the best way to handle it is. Maybe make it take a parameter? So something like:

```
moveToPositionRelativeToBoss(Left)
moveToPositionRelativeToBoss(Behind)
moveToPositionRelativeToBoss(FrontOrBack)
moveToPositionRelativeToBoss(In)
```

**Comment by panicstevenson** [comment]
Is it fair to say that all `14:\y{Boss Name} starts using` log lines have a target? I haven't done an exhaustive search, but the ones I did pull up had the boss casting on themselves for most casts.

**Comment by quisquous** [comment]
I thiiiink so? I wonder if it's possible to have an empty target.

**Comment by quisquous** [comment]
Here's a proposal: https://github.com/quisquous/cactbot/compare/regexes.  Opinions welcome!

This differentiates `startsUsing` and `startsUsingCapture`.  I'm still not 100% sure if this is worth doing vs always capturing.

We could also arguably ignore abilityName by default too and just always accept anything.  That's an easy enough tweak.

**Comment by Akurosia** [comment]
i would say ignore abilityName by default sounds better as it would make translate trigger way quicker and easier. 
Honestly can't think of a situation where you really need the ability name and where you couldn't use ability id  (i think 15/16 are the only ones where we don't habe the id in the log line, maybe worth asking rhavan to include it)

**Comment by JLGarber** [comment]
I agree with ignoring `abilityName` on 14/15/16 lines so long as it appears in the trigger *somewhere*. (Maybe add `abilityName` as an optional trigger property that could be populated similarly to timeline translations?) For newer contributors, it's potentially helpful to be able to associate a name with an ID immediately without having to look it up.

On capturing, I don't think it's really worth differentiating as far as performance goes, but I do like the implementation defined here. (It would also make it easier for newer contributors who maybe don't understand how capture groups work. I know this would have been helpful for me when I started submitting triggers.)

That all being said, I really like this proposal. In particular, defaulting to capture groups being named properties of the match rather than bare indices just makes sense.

**Comment by Akurosia** [comment]
@JLGarber 
i would put the name of the skill as part of its id instead inside the `startsUsingCapture`, otherwise i would not really see the point of doing the rework at all (as it would not really simplifing creating trigger at all). I mean usually we do it already like in `HadesEx Shadow Spread`

Also in my eyes this rework is also not for newbies, but more for people who maintain the data in gereal. This rework makes it way harder for a newby to get started as i will not know where the data in  `Regexes.startsUsingCapture('Phantom Train', '28A3', 'Doom Strike'),` is comming from as he will not see it in the logs themself

For newbies we would like a Guide page which explains all the functions + where to find the data and how to "convert" them into the new format.

**Comment by JLGarber** [comment]
@Akurosia That's a fair point on ending up with no saved effort on the regexes themselves. I guess for me having things clearly labeled is important, since I tend to be really bad at it. But you're correct that labeling things outside the trigger ID is almost always duplicated effort.

I agree that this is going to be one more level of abstraction that new contributors have to get through, and of course it *is* worth it in the sense that the change will save regular contributors time. Within that framework, though, I think we should extend as much consideration as possible to newer users and how they might experience the rework, even if we do understand that this isn't specifically for them.

**Comment by quisquous** [comment]
Ok, I put up a pull request for what I think is a reasonable way to have canned regexes.  You can optionally specify particular fields per helper if you want something specific there (other than "matches everything").  These all capture by default with the same names as the fields you specify.

Please take a look and let me know what y'all think.

Re: regex translations.  I think what I would like to do is to try to automatically convert from old style to this new style.  Then, once things are there, I would like to try using the `timelineReplace` block directly at runtime for triggers.  In other words, you would have a `regex: Regexes.startsUsing({ name: 'Phantom Train', id: '28A3' }),` line and then in the `timelineReplace` block, you would just specify what `Phantom Train` was in that language, and the regexes would "just work".  We could test that every name in a regex has a translation as well as part of linting.
