### ISSUE TITLE
util: have log splitter apply rsv lines to ability names

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#5486]
It'd be convenient if when people used the log splitter (in util/logtools) that it applied any rsv lines (262 lines) from the same file to ability and effect names.

**Comment by xiashtra** [comment]
This could maybe be expanded into allowing the log tools to use a file of substitutions we keep in the project tree.  It would be useful for some of the other log tools (such as the timeline tools), which might get used against a partial log that is missing 262 lines.  For instance, any log split with @valarnin's [log splitter plugin](https://github.com/valarnin/ACT_FFXIV_Log_Splitter_Plugin) will not have the 262 lines, since his plugin splits on 01 zone change lines, which appear after all of the 262 lines are written currently.

**Comment by quisquous** [comment]
For what it's worth, [this log splitter](https://quisquous.github.io/cactbot/util/logtools/splitter.html) always includes 262 lines.  Maybe @valarnin's plugin could use this same logic.  The netlog_defs file has a `globalInclude` boolean which is intended to be a "always include all instances of this line even in a split log".  Similarly there's also `lastInclude` which is "always include the last instance of this line even in a split log".

**Comment by quisquous** [comment]
I think this is done now.
