### ISSUE TITLE
Trigger issues in Dun Scaith

### ISSUE THREAD

**Issue by JLGarber** [quisquous/cactbot#549]
I could use some community help for this one. After writing the initial version of the Dun Scaith triggers, I've had some time this week to revisit that. I had a list of items that needed fixing in the [initial pull request](https://github.com/quisquous/cactbot/pull/512#issue-304035684). Several are still outstanding:

1.Particle Beam Circles
2. Hand Tethers
3. Flameflow
4. Atomos Detection

On Particle Beams, I've isolated it to the log line
```[01:23:40.002] FB:Warning: 01:23:48.978 Ground AOE tick but cannot find buff ID [739]```
This consistently appears alongside the Particle Beam circles during both Scathach and Diabolos. My guess is this is something not currently supported in the ACT plugin?

On hand tethers, I'm totally stumped. No 23 log lines appear *unless the targeted person looks at the hand*. Once they look at it, then the tether will change from 0001 to 0002 and back when they look away and back at it. It's baffling.

Flameflow and Atomos are regex matching issues. On Atomos, the way things work is that Ferdiad targets himself and casts Wormhole. As he initiates the cast, the game summons 3 (in phase 1) or 4 (in phase 2) Atomos. Additionally, in phase 1 the game summons either an Aether or an Aetherial Chakram, and on phase 2 the game will summon 2 in any combination. This Aether/Chakram immediately tethers to the type of Atomos that has an even number and starts casting Juggling Sphere. At the end of the cast, the Aether/Chakram will swoop in, reappear at the untethered Atomos, and explode in either a circle or a donut.

 The relevant regex for Atomos is:
```/ 14:(\y{AbilityCode}):\y{Name} starts using Juggling Sphere on Wailing Atomos/```
And the trigger function is:
```if (matches[1] == '1C9F')``` or ```if (matches[1] == '1CA0')```

I feel like the problem is that I'm fundamentally misunderstanding exactly what the ```matches[x]``` syntax is returning. What I understood it to do is return the entire matched log line, in the case of `matches[0]`, or the matched substring in the relevant match group, in the case of `matches[1]`, as noted in the [triggers readme](https://github.com/quisquous/cactbot/blob/ca6a8bfe113d29091889548f2264c7726ce2dc48/ui/raidboss/data/triggers/README.txt#L55). Clearly this is wrong, but I haven't had much luck trying to determine what *is* the case so far.

I could just take the easy way out and write one trigger per possibility, but that's ridiculous. There's clearly a better way.

[A recent log from Dun Scaith.](https://www.dropbox.com/s/c70lua9zykz3elu/Dun%20Scaith%2020190816.zip?dl=0)

**Comment by quisquous** [comment]
Re: particle beam.  I don't see anything in the log for particle beam.  If these circles are like the e2 circles, then they apply a dot bleed, which is probably what the ground effect warning is.  However, if you're trying to warn people to stand in them, your best bet is to make a timeline and add a timeline trigger.  You can see this same sort of thing on e2s, where there's nothing in the log for the light/dark circles, and so you just have to have the trigger happen at a particular time.

Re: tethers.  If you don't mind, if you run this again, can you run it with network data turned on? https://github.com/quisquous/cactbot/blob/master/docs/LogGuide.md#fc-packetdump.  I have some thoughts that maybe you can specify an initial tether in the actor creation such as what happens in t12 redfire and t13 dark aether orbs: https://gist.github.com/quisquous/6e7077f3d69d29a808ab76a9de9953e9

Re: matching.  The `matches` object that is returned is exactly the object that is returned from a javascript regex match function: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match.  `matches` will never be null, because it has to match to get into any code.  `matches[0]` is always the full match.  Ignoring optional g flags that aren't used anywhere in cactbot, `matches[1]` will be the first capture group.  Those two if statements seem fine.

It looks like the problem in the code is that it says `alertText: function(matches) {` and it needs to be `alertText: function(data, matches) {`.

**Comment by JLGarber** [comment]
The Particle Beam circles definitely don't apply a bleed, but you're right, it's possible that might be a hidden bleed effect to indicate that the circle is occupied. If nothing else, timeline triggers are always an option. I've been putting that off because getting long enough battles to do a good timeline is difficult for the alliance raids.

I'll have to read a little more on what you've got for tethers there. That's interesting stuff. [I have a log with network capture now](https://www.dropbox.com/s/63nth8tx9x7iqg0/Dun%20Scaith%2020190818%20Network.zip?dl=0). I don't know what to look for here though, I haven't read through the documentation on network logs, so I'll have to find that and see what's what.

You were correct, the primary issue I was having was not including the data object. Not sure why I was thinking it was an optional argument.  I think I should have a pull request ready in a day or two that will take care of the Atomos section acceptably at least. There's a more elegant solution that would handle all four cases in one trigger, but I won't be at a place to do that for a while.

Thanks so much for taking the time to look at this again. I do want this to be as first-class as the Stormblood alliances, so the assistance really makes a difference.

**Comment by JLGarber** [comment]
Just a brief update, I haven't had opportunity to run Dun Scaith much, but I did get one run in today. The Atomos triggers appear to work now, but I feel like I saw one mistaken callout during the Ferdiad kill, so I'll hold off on pushing that change until I have time tomorrow to test it.

I'm still not much closer to timeline production, unfortunately. I do have a Deathgaze enrage log,, and I think I have enough information to do a Ferdiad timeline.  I may have enough of the encounter to do the second half of Scathach now, but her first half has several really odd phase pushes and I'm not sure where they are yet. (Notably, Shadow Links and Nox orbs appear to be HP%-based, while Soar appears to be fixed in the timeline.) I'll have to just keep throwing myself at it for a while until we have enough logs to figure it out.

**Comment by JLGarber** [comment]
It's been rather a while since I touched this last. I'll probably start in on it again in the next couple of weeks, now that my static seems to be doing better on Titan. I've also learned better how timeline generation should work, so I'll be able to put together *something* at least.
