### ISSUE TITLE
Feature request: Enhance P9S LC1 callouts

### ISSUE THREAD

**Issue by Flavescent** [quisquous/cactbot#5642]
In P9S, at the start of the limit cut 1 phase, the callouts should be expanded as follows:

"2" -> "2 - First dash, third tower"
"4" -> "4 - Second dash, last tower"
"6" -> "6 - First tower, third dash"
"8" -> "8 - Second tower, last dash"
(No callout) -> "No number - stand by for defamation"

Rationale: 
- This informs the numbered players of their role in the mechanic's sequence. This sequence is the same for all strats and enforced by the mechanic. 
- It also gives positive confirmation to the non-numbered players that they are the ones who need to wait for their turn to be randomly selected for the defamation (ice) marker.

PS. Cactbot is also missing an raidwide AOE damage callout just after the LC1 phase.

**Comment by xiashtra** [comment]
> PS. Cactbot is also missing an raidwide AOE damage callout just after the LC1 phase.
Post-LC1 is either `Pile Pyre` pair stacks or `Thunder III` spreads, followed by `Gluttony's Augur`, followed by `Soul Surge`.  All of these have callouts, and they are working.  What exactly is missing?

**Comment by wexxlee** [comment]
> "2" -> "2 - First dash, third tower" "4" -> "4 - Second dash, last tower" "6" -> "6 - First tower, third dash" "8" -> "8 - Second tower, last dash" (No callout) -> "No number - stand by for defamation"

**Comment by wexxlee** [comment]
> "2" -> "2 - First dash, third tower" 
> "4" -> "4 - Second dash, last tower" 
> "6" -> "6 - First tower, third dash" 
> "8" -> "8 - Second tower, last dash"

IMO, I think this would get noisy, particularly for tts.  `P9S Limit Cut Levin Orb Start and Rotation` already calls out the starting (1st) orb and rotation direction at nearly the same time, so this would be even more info for users to process, when it isn't strictly relevant until later in the mechanic.  That being said, it would be fairly easy to separate the 2/4/6/8 outputs into separate outputs instead of just a single ${num} output, so they could be customized as you prefer.

> (No callout) -> "No number - stand by for defamation"

I think this would be a good change, although I might suggest simplifying it to an infoText "Defamation on you (later)".

Happy to throw together a PR for this, unless anyone else feels differently?

**Comment by quisquous** [comment]
Re: tts being noisy.  Maybe tts could just say the number, and the text could say more?

**Comment by Flavescent** [comment]
Thanks for the quick change!

> There are already "Soak tower" and "Bait dash" calls for 2/4/6/8 that happen when it is their turn to bait or soak.
> 
> > PS. Cactbot is also missing an raidwide AOE damage callout just after the LC1 phase.
> 
> Post-LC1 is either `Pile Pyre` pair stacks or `Thunder III` spreads, followed by `Gluttony's Augur`, followed by `Soul Surge`. All of these have callouts, and they are working. What exactly is missing?

@xiashtra My mistake, the missing raidwide callout is right after the comet mechanic, Beastly or Bestial or something like that. It deals raidwide damage and has no callout.
