### ISSUE TITLE
raidboss trigger development rule question

### ISSUE THREAD

**Issue by Souma-Sumire** [quisquous/cactbot#5802]
_English is not my native language; please excuse typing errors._

I've created a trigger for GolbezEx's Gale Sphere mechanic, and I receive all four upcoming texts when the first sphere appears. Subsequently, I delay their output by 6.5, 10, and 13.5 seconds, respectively. However, to achieve this, I must create four separate triggers.

The issue that arises is that I don't need to receive the required text in the output for the next three outputs; instead, it is obtained in the output of the first trigger and then saved in data for use in the subsequent three triggers. However, this violates the 'no outputStrings in trigger' rule.

If I adhere to this rule, users would have to repetitively modify their output text four times. 

What should I do in this situation? Thank you!

<details><summary>Code Details Image</summary>
<p>

![image](https://github.com/quisquous/cactbot/assets/33572696/9f35afc7-090c-4b58-999f-c7557f2432dc)

</p>
</details>

**Comment by wexxlee** [comment]
> I've created a trigger for GolbezEx's Gale Sphere mechanic, and I receive all four upcoming texts when the first sphere appears. Subsequently, I delay their output by 6.5, 10, and 13.5 seconds, respectively. However, to achieve this, I must create four separate triggers.

Before creating a new trigger, I might suggest looking at the Gale Spheres trigger that's already in place for the Golbez Normal raid, as it already handles that mechanic.  
https://github.com/quisquous/cactbot/blob/main/ui/raidboss/data/06-ew/trial/golbez.ts

It's been a minute, but iirc, I think I shamelessly copied the logic for that trigger from valarnin's original (still WIP) PR #5425 for Golbez Ex.  Regardless, I would suggest keeping the same trigger logic that's used for Golbez normal for GolbezEx unless there's a reason to deviate (and iirc, I don't think there is).

But as to the code in your PR: it's hard to tell without seeing the full code, but I'm not sure I see a need to do four separate triggers, since I think your regex for each trigger (looks) identical.  It should just be a matter of capturing each cast, sticking the directional info in data.[whatever] (if that's even necessary).

> The issue that arises is that I don't need to receive the required text in the output for the next three outputs; instead, it is obtained in the output of the first trigger and then saved in data for use in the subsequent three triggers. However, this violates the 'no outputStrings in trigger' rule.

Again, hard to say without seeing the rest of the code, but the reason you're getting that rule is because `infoText` expects a string to be returned as output.  If you're only performing logic operations and not returning a value to be presented to the user as an alert, you can use `run` instead of `infoText`.

Hope that helps!

**Comment by Souma-Sumire** [comment]
First of all, thank you for your response.

I did indeed forget to check the trigger for the normal difficulty or the existing PR, and I appreciate the reminder.

However, I'm currently not planning to submit it to the main branch. I'm using TypeScript to help me develop my custom triggers temporarily. There's still a lot for me to learn, so for now, I'm just asking about this particular rule.

If needed, my complete code is [here](https://github.com/Souma-Sumire/cactbot/commit/25ac35333c525389075979e3aae6d7b55e95e365)

The reason I divided it into four parts is that it would be very confusing if the text was read all at once. So, I designed it to display all safe zone texts first, and the TTS (Text-to-Speech) announces the next safe zone after each judgment. Personally, I believe this is more "disability-friendly," so I did it this way. I think I need to use infoText, and I don't need outputString.

So, maybe I can "ignore" this issue? Or is there a way to manually bypass it, like `//@ts-ignore`?

Once again, thank you for your response!

**Comment by Souma-Sumire** [comment]
I find `// eslint-disable-next-line` to disable error, Maybe this is what I need.

**Comment by quisquous** [comment]
`// eslint-disable-next-line rulesdir/cactbot-output-strings` will do it more narrowly as well and not disable other errors.

And yeah, the underlying reason for this rule is that it makes it more clear to users where the output is coming from if every trigger has its own output strings. There's no way to know in the cactbot config ui that to modify the output of trigger B that you should find trigger A and modify it instead.

It's not a perfect solution and it makes things awkward in situations like this where you have one trigger with all the logic and several other triggers to call things out. Even if you do things like endsinger-ex's `const orbOutputStrings` and just `outputStrings: orbOutputStrings` for each trigger, it still does mean that users have to fill in each of them redundantly.

I think there is probably a use case for "trigger set output strings", where the triggerset itself has some shared set of output strings that users can fill in once and that apply everywhere. I think I'd still maybe want cactbot developers to fill in which outputstrings are used so we could display that in the UI though? Alternatively, maybe some way of grouping triggers together that say "hey all of these four triggers use this set of outputstrings", but the ui for that is less clear.
