### ISSUE TITLE
Sound Issues

### ISSUE THREAD

**Issue by sashaks86** [quisquous/cactbot#587]
There is a loud sound in E2S that happens with Hell Wind & Hell Wind in Waiting that knocks out the sound in-game and on discord. It is happening every single time I get in there. I have to reset the game client and discord to get sound back. Can someone please help me figure out what is going on, please?

**Comment by JLGarber** [comment]
Are you quite sure this is an issue with Cactbot and not with another trigger suite? You can look through the Hell Wind section of the [E2s triggers](https://github.com/quisquous/cactbot/blob/5fb37f64d624945bc8ae5081b6c2b0975784cb48/ui/raidboss/data/05-shb/raid/e2s.js#L454), but I'm a little baffled as to what would cause your sound driver to crash. Does this crash happen only with Cactbot enabled? Which role are you on? Does it happen 100% there, or does it also occur alongside Shadoweye? (This last one is important, because the Hell Wind triggers share a sound effect with Shadoweye.) Have you ever experienced this crash at the buddy circles? (Equilibrium)

**Comment by sashaks86** [comment]
The only other thing that is enabled is triggernometry. I disabled the triggers there that I thought were related and it still happened. It's only happening during that one sound. I believe it is the same sound hell wind and shadoweye share. It's a loud scary like sound lol. I can't describe it sorry. By the time I make it to buddy circles the sound is already out so I can say if it happens there.

**Comment by sashaks86** [comment]
My role is brd

**Comment by sashaks86** [comment]
So it was definitely cactbot. The sound for those triggers. I turned off the alarm sounds and it worked fine during e2s. I talked to a couple of other people that are having this same issue.

**Comment by ngld** [comment]
That... sounds weird... and interesting. AFAIK all the alarm sounds are played through the overlay browser and a website should *never* be able to crash your sound driver.
I wonder if this was a bug in an old version of Chrome/Chromium which is hopefully fixed by now or if it's something else related to ACT...

**Comment by quisquous** [comment]
Yeah, I haven't heard of that happening with anybody else.  I'm sorry the alarm sound is so jarring!

Glad turning off the alarm sounds worked fine.
