### ISSUE TITLE
timeline trouble: in P12S P2

### ISSUE THREAD

**Issue by aogh14** [quisquous/cactbot#5913]

**Comment by valarnin** [comment]
I know that they closed this issue, but for reference this is because of missing name translations for KO for `Pallas Athena` and `Hemitheos` in https://github.com/quisquous/cactbot/blob/main/ui/raidboss/data/06-ew/raid/p12s.ts, I'm pretty sure.

I only checked to make sure it wasn't the same problem as the issue you linked.

(cc @Bing-su, since they normally handle translations for this language)

**Comment by Bing-su** [comment]
I didn't run this raid, so I don't have any rsv data this time.

@aogh14 데이터 얻으면 업데이트 할 예정이에요.

**Comment by valarnin** [comment]
Here's the RSV lines from their original log file, if that helps @Bing-su 
[p12s korean rsvs.log](https://github.com/quisquous/cactbot/files/13314259/p12s.korean.rsvs.log)

**Comment by Bing-su** [comment]
> Here's the RSV lines from their original log file, if that helps @Bing-su [p12s korean rsvs.log](https://github.com/quisquous/cactbot/files/13314259/p12s.korean.rsvs.log)

Thanks!
