### ISSUE TITLE
Raidboss: Cactbot catching network logs randomly when two logs show at the same time

### ISSUE THREAD

**Issue by cordy5134** [quisquous/cactbot#5946]
Hi,
I know that quisquous is still progging AAI so I will not show this explicitly. Basically I have a trigger that catching multiple skill IDs, but in the raid there will be two different skill ID cast from the same source at the same time. Then it appears that cactbot is catching either one of them randomly. So when I check the replay video I can see different actual mechanisms matches the same skill ID in the cactbot. I can provide logs and screenshots if needed. Thanks in advance.

**Comment by quisquous** [comment]
I'm not sure I understand what issue you're having. What do you mean by "one or the other randomly"? You have a trigger that is catching multiple ids, and you're expecting it to fire repeatedly, but it's only firing once?

Do you have a `condition` or ` delaySeconds` or a `suppressSeconds`? What does raidemulator say?

**Comment by cordy5134** [comment]
So the boss will cast two skill IDs for the same skill name at the same time(the timestamps are identical), so I will get two lines of log like this:
`20|2023-11-18T17:58:41.3800000+00:00|someID1|Boss Name|Skill ID1|Skill Name|`
`20|2023-11-18T17:58:41.3800000+00:00|someID2|Boss Name|Skill ID2|Skill Name|`
One of them is a fake cast and I should dodge according to the other ID, which I assume is the skill ID boss actually trying to cast.
I should detect which skill ID (ID1 or ID2) comes first in order to make the trigger work, but I can see even the boss finally cast 3 different kinds of skills, the emulator always matches to a random ID of the two logs, which breaks the trigger

**Comment by quisquous** [comment]
Sorry for more questions! I'm just not understanding the problem here. Can you share more of the trigger?

> One of them is a fake cast and I should dodge according to the other ID, which I assume is the skill ID boss actually trying to cast.

Are `someID1` and `someID2` always cast at the same time together? If so, just write a trigger to match `id: 'someID1'` OR `id: 'someID2'` and it should be equivalent.

> I should detect which skill ID (ID1 or ID2) comes first in order to make the trigger work

If they're at the same time, why do you need to detect which comes first? Mostly just saying I've never seen a log issue where two casts happen at the same time and which cast appears first in the log is important.

> the emulator always matches to a random ID of the two logs

This I don't understand. The logs match in order. So if you have a trigger that matches `id: ['someID1', 'someID2']` and you have those log lines, it will first run for `someID1` and then run for `someID2`.

**Comment by cordy5134** [comment]
After checking the logs again I finally realized I was using the incorrect skill ID. Now it was fixed and everything is working just fine. Thank you for your help!
