### ISSUE TITLE
util: let test_timeline.py and make_timeline.py autoselect encounters from a file

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#646]
Right now, it's a pain to select start and end times when building and testing timelines.  If no start and end times are selected, it'd be nice to list all of the potential encounters (seal/unseal, and detected wipes) by number, and then just let you pass in `-rf` to select a single fight as you can with fflogs.

Just as a note, I've seen some issues with picking times when the network log has a different timezone (you have to specify times with local times).  It'd be good to test this with this new feature.

This was mentioned in #636, so filing it as a feature request.

**Comment by quisquous** [comment]
Also additionally it would be nice to not have to specify a timeline file, if it could somehow figure out which timelines applied based on zone.

**Comment by JLGarber** [comment]
For `make_timeline`, how open are we to parsing the file twice if no start/end are specified, once to find encounters and the second pass as it currently exists? For minimum effort, it seems we could add  `find_encounters_in_file` that would quickly iterate through and pull out the start/end times to pass to `parse_file`. Something like:

```
        for log_line in file:
            # Ignore log lines that aren't game status info
            if not (log_line[39:42] == '0839'):
                continue

            # Build start/end time groupings
            log_line_fields = log_line.split('|')
            if (log_line_fields[4].endswith('sealed off in 15 seconds!')):
                encounter_starts.append(parse_line_time(log_line))
                continue
            if (log_line_fields[4].endswith('no longer sealed!')):
                encounter_ends.append(parse_line_time(log_line))
                continue
```

From here we can easily return a list of encounter start/end pairs. With a little extra work it should be not-difficult to add the first few NPC names that appear after the zone sealing message to accompany the timestamps. Or we could just add the zone name to the timestamp and let the user work it out from there.

(Apologies for the ugly. I'm vastly unfamiliar with Python's file parsing, so I don't know whether the performance benefits of not parsing twice would be worth the effort to extend `parse_file` cleanly. Nor do I know whether native string methods would be better/worse than regex for this purpose, it's just what I grabbed out of the standard library.)

One major benefit of the extra pass would be ease of dropping encounters that are under a certain (potentially configurable) length. If we try to do it all in-line, I feel like it's a little complex to enable listing encounters from within `parse_file`. Additionally, the extra pass would only need to be incurred if the user wants to avoid using start/end flags, which seems like an acceptable trade-off in that situation.

Obviously this currently wouldn't handle single-encounter instances, either. I'm not 100% sure how best to handle that for this sort of thing. Maybe rely on the ENGAGE notification for start and then check for the 21 log line paired with that for end?

**Comment by quisquous** [comment]
Overall, I think my guidance would be to write things as simply as possible first and then optimize from there.  Parsing twice seems fine when the start/end pairs aren't listed, especially if it's cleaner.  Similarly, I wouldn't worry about native strings vs regexes, just do whatever makes the code more readable.

Engage is a possibility, but not every fight uses engage... :thinking: And sealed and engage both won't work with door fights (o4, o8, o12) where there are two bosses in the same zone.

One more complicated solution here is to read all the trigger files, and grab the zoneRegex + timelineFile listings out of them.  Then when you encounter a zone change line in a network file, you could could load that timeline file and grab all the syncs that overlap with zero as potentially "starting" syncs, and anything that matches those is the "start" of a fight.  And a wipe or a zone change is the end.  That's a bunch more work, but I think that would cover all the options.

**Comment by quisquous** [comment]
Also, if you are interested in timeline scripts, there's other thoughts in #322 as well.

**Comment by JLGarber** [comment]
It occurs to me that we might be able to use line 24, limit break generation, for the start times in single-encounter instances. From a quick look through logs from the past few days, there's a 0000 line sent at the start. I'll have to figure out how best to do that, but it's a guaranteed clean start for single-encounter instances.

**Comment by quisquous** [comment]
Ooh, that's an intriguing idea!  I think in all door boss fights there's a `The limit gauge resets!` message, so it might work for them as well.

**Comment by JLGarber** [comment]
Maybe always look for 24: 0x0000 lines no matter what, and then rely on other stuff to discard trash encounters in the event it's necessary? There would be at most 1-2 superfluous trash encounters per zone anyway under this system, and it should be reasonable to discard that first event if another start event is found. Something like:

```
current_start_event = first_start_event
if second_start_event and not first_stop_event
    current_start_event = second_start_event
```

This would have the added benefit of not raising exceptions if the user has a log with unbalanced start/stop points, as can happen when zoning into an instance in progress. It would potentially lose the ability to make timelines based on those partial encounters, but at that point the user can just specify start/stop points manually.

Naively implementing it like this would of course potentially split encounters if a limit break is used during, so perhaps the 0-value limit break can be used as a start point only after a wipe or "limit gauge resets" line.

**Comment by JLGarber** [comment]
Alright, I think this will work. I'll just talk this through so we can catch any holes in it early.

I'm going to assume that zone sealing/unsealing messages are first-class. I can't think of any situations where they wouldn't indicate a boss battle. (There are some minor situations like the trash bosses in alliance raids, but there really isn't a clean way to discard those that I can see right now, and it should be easy for the user to ignore them. Or I guess we could build timelines for them too...)

`40000010` wipe indicators and limit resets should also be first-class, obviously. Limit break 0000 messages will indicate the start of a battle IF there isn't already an encounter being tracked.

I'm thinking it would work like this:

```
if zone_seal or (0000 limit break and not started):
    started = True
if zone_unseal or limit_reset_message or 40000010 wipe or 40000003 victory:
    started = False
```

This should be effective in all post-ARR light-party content, since those all have zone seal/unseal messages. It should also handle all alliance content for the same reason. Any full-party content *should* be handled acceptably by the safety of the 0000 limit break not indicating a start point if there's already an active encounter. (Thus, using the limit break, or having a person leave the party shouldn't break things.)

Are there any edge cases in existing post-ARR content I'm not seeing here? Maybe make `zone_change` a stop condition too, as a safety?

**Comment by quisquous** [comment]
I think t5/t9/t13 are weird, because there's no zone seal and there's no wipe indicator.  I am not sure what to use there.

As a more general question, are you opposed to having something look through all the trigger/timeline files to find starting lines that apply vs trying to make a heuristic that works? For test_timeline, one thing that would be nice would be to auto-select the timeline to test against too, which is the other reason I was suggesting parsing data files.  Then you wouldn't need to figure out what are first class things or not, you'd just find syncs that can happen at t=0 from timeline files.

**Comment by JLGarber** [comment]
I'm not opposed to parsing the data files for `test_timeline`, you're absolutely correct that for that it makes more sense to just look at the existing start/stop events. I should clarify, I've mostly been looking at this for `make_timeline`, which to my mind pretty much requires heuristics. If I'm misunderstanding there, that's exactly why I'm laying this all out now so I can  redirect.

(As far as the Coils, I'm less concerned about making that work compared to Heavensward content and onward, given that the primary (only?) audience for those will be synced runners. I could have sworn T5 had a zone seal message, but that still leaves 4, 9, 12, and 13 as problems. Are there just no `21` log lines for those at all?)

**Comment by quisquous** [comment]
Oh oh oh, you're totally right.  I think I was thinking about this from the other end.  If you're doing this for `make_timeline` you have to have heuristics.  You're so so right.  (And if you have all those heuristics, then you might as well use it for both, and make sure that they cover all the existing timelines.)  It'd still be nice to auto-select timelines, but in that case all you need is the zoneRegex and not the sync lines.  I think you're correct in your assertions about post-ARR content.

Yeah, I agree that it probably doesn't matter for coil.  It's more just a question for completeness, not of prioritization.  You're right that t5 has a zone seal, but there aren't wipe lines: [t5.zip](https://github.com/quisquous/cactbot/files/3727240/t5.zip).

**Comment by JLGarber** [comment]
No, no worries. I'm not trying to push my vision of how things should be, it was more *"Well, I genuinely can't see how that's supposed to work, but I'm also not sure whether it's a miscommunication about terms, or just me misunderstanding something.*

When listing the encounters, for either of the scripts, is there any information that is necessary/useful per encounter besides the instance name/zone name and the start time? That would be simple to return with the model I have sketched out in my head, but I don't want to just lock into that without looking for other things to include.

Going back to the issues with time zones, could you expand on how they might affect the new work that's going into the scripts? Whether or not the log file that the script uses is in the user's home time zone, the information pulled from the log and presented to the user should be correct *for that log file*, if the user elects to have the script do the work for them. I think I could be missing something here that's due to my workflow not matching other peoples'.

Thank you for your patience while I work through this. It's definitely different from assembling trigger files!

**Comment by quisquous** [comment]
I think zone name, start time, and duration would be enough? The raid emulator just uses zone name and duration (in a sorted list by start time, which isn't shown), and that's plenty to pick the right one.

I think the timezone issue is more something to look out for.  I've just seen this where somebody from a different timezone has handed me a log file and `-s` and `-e` don't really take that into account, and so I've had to offset them.  It's more just a "here's a bug to look out for, and it'd be worth testing a log file from a different time zone".

**Comment by JLGarber** [comment]
Well, it's still not workable, but there's very definitely progress:

```
1. 01:06:51 01:08:49 The Astrology and Astromancy Camera
2. 01:06:51 01:09:39 The Astrology and Astromancy Camera
3. 01:30:31 01:33:32 Repurposing
4. 01:37:26 01:40:05 Aetherial Observation
5. 01:43:36 01:47:45 The Cornice
6. 01:43:36 01:47:45.675000 The Cornice
11. 01:57:27 01:59:03 The Hall of the Tainted
12. 02:00:06 02:01:08 The Walk of Lament
13. 02:01:33 02:02:37 The Hall of the Deviant
14. 02:03:50 02:05:18 The Walk of Fire
16. 02:07:04 02:08:38.349000 The Hall of the Inexorable
17. 02:07:04 02:08:38 The Hall of the Inexorable
19. 02:10:47.838000 02:18:08.061000 Rhalgr's Reach
21. 14:47:31 14:49:25 Repurposing
22. 14:52:07 14:54:02 Aetherial Observation
23. 14:56:54 14:59:45.967000 The Cornice
24. 14:56:54 14:59:45 The Cornice
26. 15:48:32.913000 15:57:28.049000 Amh Araeng
27. 15:48:32.913000 15:57:46 Amh Araeng
28. 15:57:46.297000 16:14:45.434000 Eden's Gate: Resurrection
29. 16:14:56.627000 16:16:34 Eden's Gate: Descent
30. 16:36:28.056000 16:44:57.727000 Old Gridania
31. 16:45:06.918000 16:46:12 Eden's Gate: Inundation
32. 16:54:46.020000 17:02:34.354000 Old Gridania
33. 16:54:46.020000 17:03:50 Old Gridania
34. 17:03:50.525000 18:03:00.745000 Eden's Gate: Sepulture
35. 17:03:50.525000 18:03:14 Eden's Gate: Sepulture
36. 18:03:15.252000 18:35:45.697000 Eden's Gate: Resurrection
38. 18:36:58.915000 18:46:24.621000 Eulmore
```
Yay for naive indexing! (This is just on me prepending the indices before culling rather than after, so that's not going to be an issue on release.)

I'm thinking that it may be necessary to check explicitly for "instance has begun" before permitting "is encounter started", and treat "instance has ended" lines as "encounter has stopped" in order to avoid the phantom encounters you can see there in non-instanced areas. This is due to 0000 limit break lines sometimes being sent after the `40000003` victory line. (Assuming the player doesn't stay in the instance longer than 60s after the boss dies, the phantom encounter generated by that should be culled automatically. Longer that that, and they would have a phantom encounter, but I'm not sure how to solve that without actively checking for absence of combat lines.)

Another thing I'm running into is that `datetime` objects elide `time.microsends` by default if the value is 0. It wouldn't ordinarily matter, but it does cause problems if not just listing encounters. I'm having `find_fights_in_file` return a list of strings, in the basic format of
```
[FIGHT INDEX,START TIME,END TIME,LOCATION]
```

 Currently I'm trying to insert at line [103](https://github.com/quisquous/cactbot/blob/fa2e17c7acedafcafd4baa4ceb1d1bcd0054e897/util/make_timeline.py#L103):

```
        encounters = find_fights_in_file(file)
        for line in file:
            start_time = end_time = 0
            if args.list_fights:
                start_time = (encounters[args.list_fights][1])
                end_time = (encounters[args.list_fights][2]))
            else:
                start_time = args.start
                end_time = args.end
```

All is fine if the user directly passes start/end times, but because of the elided microseconds in the generated encounter times, the comparison between the timestamp on each line and the generated start time will always fail. (That is, the log line will show `12:34:56.000`, while the generated time will show `12:34:56`. This is what causes the goofy durations on the listed fights in the sample output I showed above. When the microseconds are elided, the comparisons in the existing code at lines [104-18](https://github.com/quisquous/cactbot/blob/fa2e17c7acedafcafd4baa4ceb1d1bcd0054e897/util/make_timeline.py#L104-L108) will fail.) I could do something horrible like "if no microseconds, append '.000 after the string conversion but before inserting into the list", but there's got to be a better way, right?

Also, I've been deliberately stripping the date portion of the `datetime` objects before stringifying them into the lists, but I'm realizing that may not be a good idea. I have my copy of ACT set up to partition by 24-hour periods, so that assumption is sort of reflected in how the times are displayed. It may not be ideal, but the dates take up so MUCH horizontal real estate. What do you think?

I'm sorry this wasn't ready before 5.1. I'm hoping to have `make_timeline` at least to a point where I can reasonably do a draft pull request by Thursday or Friday. (If you like, I can try to put together a draft tonight, since there's maintenance, with fuller explanations on some things, but it's still very much under construction and a number of things in there reflect that.)

I haven't really looked into it much, but I expect that once `make_timeline` is worked out, it will be relatively simple to transfer that work over to `test_timeline`.

**Comment by JLGarber** [comment]
I think this one's probably reasonable to close now. There's still some stuff in #322 I'd like to poke at some time, but I'll probably try to update the timeline guide and complete the Heavensward dungeons first.

**Comment by quisquous** [comment]
:confetti_ball:
