### ISSUE TITLE
Custom Timelines in /user

### ISSUE THREAD

**Issue by dencur** [quisquous/cactbot#666]
Is there a way to create a custom timeline in a /user directory so that changes aren't overwritten by the packaged timelines after install?

Example:
..\Advanced Combat Tracker\OverlayPlugin\cactbot\ui\raidboss\data\05-shb\raid\e2s.txt
But if you have 
..\Advanced Combat Tracker\OverlayPlugin\user\e2s.txt
it takes priority over the one in the install raidboss folder?

Something like that?

Would be really handy, I like to edit timelines to create custom reminders.  If this isn't something that's supported, then just dropping this here as a feature request.  Thanks!

**Comment by quisquous** [comment]
Yes, definitely.

Any timelines get merged together, rather than one taking priority over the other.  So, this means you can add new entries or add hide statements that hide existing ones.  It's as if you just appended any new timeline lines to the file in cactbot itself.

See: https://github.com/quisquous/cactbot-user/blob/master/raidboss.js#L40

I really need to write an FAQ for these sorts of things, because I think it's not that clear how to do this, and I think a lot of people would want such things.

**Comment by dencur** [comment]
This is awesome!  Thank you!
