### ISSUE TITLE
Copied Factory warning style

### ISSUE THREAD

**Issue by cnieuweboer** [quisquous/cactbot#723]
Copied Factory has warnings that tell you where to stand.
For many of the attacks I think a description of the attack is far more useful.
It's far easier to recognize what is about to happen that way, and you can just decide what to do for yourself.

A few examples:

Attack: 9S-Operated Walking Fortress starts using Laser Turret
Warning: Away From Front
What I'd prefer: Frontal Laser

Serial-Jointed Command Model starts using Energy Assault
Warning: Get Behind
What I'd prefer: Frontal cone

Serial-Jointed Command Model starts using Sidestriking Spin
Warning: Go Front/Back
What I'd prefer: Flank attacks

Engels starts using Energy Barrage
Warning:  Go Sides (Near Front)
What I'd prefer: Frontal Laser (stay near boss)

Also I think for the semi random attack that come from the sides of the arena, the warning should be standardized on "look for".

An examples:

9S-Operated Walking Fortress starts using Engage Marx Support
Warning: Dodge Overhead Saws
What I'd prefer: Look for overhead saws

**Comment by JLGarber** [comment]
One thing to keep in mind is that those warnings are extremely standard across the content that Cactbot covers. This is a mostly non-negotiable thing in order to ensure consistency across the repository.

That being said, if that would help you focus better, you *can* change those warnings for yourself. If you look in the `cactbot/user` directory, you can find the `raidboss-example.js` file, which is used for customizing triggers. Rename this file to `raidboss.js`, and open it in a text editor. Then, you can add options from here. For example, let's say you wanted to change Energy Assault. You would add this block to the end of the `Options.PerTriggerOptions` section, right before the last `}` brace:

```
{
  id: 'Copied Serial Energy Assault',
  infoText: {
    en: 'Frontal Cone',
  }
}
```

You can find the trigger IDs  in [the Copied Factory file](https://github.com/quisquous/cactbot/blob/master/ui/raidboss/data/05-shb/alliance/the_copied_factory.js).

**Comment by cnieuweboer** [comment]
Ah I see. I didn't know you could do that in raidboss.js, that does help a lot.

**Comment by quisquous** [comment]
Yeah, sorry about having a different philosophy on triggers.  My feelings are generally that cactbot should behave like a human raidcaller in your party, telling you what to do (in / out / spread / stack / middle / sides) with minimal cognitive overload.  Telling you mechanics (e.g. Laser!) requires an extra step in your mind of going "ok laser is a cleave down the middle so I should move to the sides".  For mechanics where there is not an obvious thing to do, I have it call out the mechanic name itself (e.g. hello world debuffs) but I think that's the backup callout and not the primary one.

**Comment by quisquous** [comment]
I realize it might be useful to have some of this listed somewhere, so I added it here: https://github.com/quisquous/cactbot/blob/master/CONTRIBUTING.md#trigger-text
