### ISSUE TITLE
Raidboss alerts cause major fps drop

### ISSUE THREAD

**Issue by CKaleb** [quisquous/cactbot#729]
Hello, after a week of absence I updated to the latest release of cactbot, but ever since I did I'm experiencing major FPS drops every time a text alert pops up. I've tried the timeline only setting and the stutter is not present, it's only whenever a text alert pops on screen (Provoke, Shrik, aoe, "tankbuster", etc.) 

I've tried both the hibiyasleep and ngld versions yet the issue is present in both, it's worth mentioning that as soon as the text alert dissapears my framerate returns to normal. I've also disabled all overlays, such as Discord's.

**Comment by quisquous** [comment]
Is this new with newer versions of cactbot, or has it always been like that for you? Has anything changed with your setup recently?

Take a look at #71, along with all of the other issues that are linked there, and see if any of that is relevant for you.

**Comment by Shizzz104** [comment]
I have a similar issue, but it's a bit weirder.
Heavy stutter happens closer to the end of the first two bosses of The Copied Factory, and then goes away after their deaths.
Never noticed something like that.
Tried disabling any other overlays (discord, etc). 
The stutter does not occur with the raidboss module disabled.
Happens with both overlay plugins, hibiyasleep and ngld.
Still happens with today's updates (I updated ACT, ngld ovelay and cactbot simultaneously).

So far I took a look at
https://github.com/quisquous/cactbot/issues/386
https://github.com/quisquous/cactbot/issues/48
https://github.com/quisquous/cactbot/issues/71
but was unable to find a solution (tried disconnecting the second monitor, lowering resolution, playing with hardware acceleration in Chrome, to no avail).

I'm not overly concerned, since it's just the final phases of 2 not terribly hard bosses, just decided to chip in with the info I have.

**Comment by Nitrodroki** [comment]
Can confirm that the ngld version (at least, didnt test the other one) is a CPU hog for the first 2 bosses. ACT even suggests a benchmark to check if things are not overloaded. You can expect about 30-40 fps loss from cacbot during those bosses.

**Comment by quisquous** [comment]
@CKaleb Regarding stutters right when triggers come out, could you try removing this ".animate-text" block from ui/raidboss/raidboss.css (https://github.com/quisquous/cactbot/blob/master/ui/raidboss/raidboss.css#L70-L73) and see if that makes a difference?

Regarding the other issues, I'm not really sure about the copied factory issues.  Does this happen elsewhere in other alliance raids?

**Comment by quisquous** [comment]
Hi, following up to see if my suggestion helped, or if this is still happening.

**Comment by CKaleb** [comment]
Hello, I'm so sorry for not replying sooner.

I've been a bit absent, recently returned to the game, and did a complete fresh reinstall of ACT and Cactbot, the issue is now gone.

Thanks, and my apologies once again.

**Comment by quisquous** [comment]
No worries at all.  Glad you got it sorted, and thanks for the followup!
