### ISSUE TITLE
Load OverlayPlugin Problem

### ISSUE THREAD

**Issue by hdstarx** [quisquous/cactbot#75]
I tried a lot and also looked in forums for a solution, but unfortunately found nothing, which helped me :x pls help me

OverlayPlugin.dll ->New -> Cactbot:

System.MissingMethodException: Method not found: "Void RainbowMage.OverlayPlugin.OverlayConfigBase.set_GlobalHotkeyType (RainbowMage.OverlayPlugin.GlobalHotkeyType)".
   at Cactbot.CactbotOverlayConfig..ctor (String name)
   at Cactbot.OverlayAddonMain.CreateOverlayConfigInstance (String name)
   at RainbowMage.OverlayPlugin.ControlPanel.CreateAndRegisterOverlay (IOverlayAddon overlayType, String name) in d: \ Personal \ OverlayPlugin Compiler \ OverlayPlugin \ OverlayPlugin.Core \ ControlPanel.cs: Line 186.
   at RainbowMage.OverlayPlugin.ControlPanel.buttonNewOverlay_Click (Object sender, EventArgs e) in d: \ Personal \ OverlayPlugin Compiler \ OverlayPlugin \ OverlayPlugin.Core \ ControlPanel.cs: Line 181.
   at System.Windows.Forms.Control.OnClick (EventArgs e)
   at System.Windows.Forms.Button.OnClick (EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp (MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp (Message & m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc (Message & m)
   at System.Windows.Forms.ButtonBase.WndProc (Message & m)
   at System.Windows.Forms.Button.WndProc (Message & m)
   at System.Windows.Forms.NativeWindow.Callback (IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

have lastest version from hibiyasleep and cactbot, but yea.... dunno what i can do for fix

**Comment by quisquous** [comment]
Hot key types were added in OverlayPlugin 0.3.3.14.  The latest OverlayPlugin is 0.3.4.0.

If you run ACT and then go to Plugins -> Plugin Listing -> OverlayPlugin.dll, what does the plugin info say about the version?

**Comment by hdstarx** [comment]
öhhh 0.3.4.0 version

**Comment by quisquous** [comment]
Did that solve your problem?

**Comment by hdstarx** [comment]
no, unfortunately still the problem

**Comment by quisquous** [comment]
What version of OverlayPlugin are you using?

**Comment by quisquous** [comment]
:thinking: A few more questions, thne.

Do you have older versions of the OverlayPlugin inside your ACT folder?

Is CactbotOverlay.dll in the addons folder of the OverlayPlugin.dll that you have loaded?

If you add a MiniParse overlay, do you get the hotkey options like this?

![image](https://user-images.githubusercontent.com/462317/37263825-2ad2ceb8-2567-11e8-8270-f60161994fa2.png)

**Comment by hdstarx** [comment]
oh, now it works. I had another version, an old version in a subfolder. I still have a question, how can I disable the sounds for this plugin? or are they only on the dummy?

**Comment by quisquous** [comment]
Glad you got it working! :+1: 

Re: configuring.  Take a look at:
https://github.com/quisquous/cactbot/blob/master/AdvancedCactbot.md#configuring-ui-modules
https://github.com/quisquous/cactbot/blob/master/user/raidboss-example.js

**Comment by eparsyl** [comment]
I am trying to get this working as well.

I have 3.4 Overlayy, 8.0 Cactbot, no older versions in ACT folder anywhere, and I do not get the above shown options when adding a mini parse.

If I add a new mini parse, and use the url file the text shows on screen, but does not work in real time. (I went to summerfold and did the test). I have restarted my pc and ACT multiple times and cant get it working.

*** Below is copy/paste from the dialog box that pops up sorry for the length ***


See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.MissingMethodException: Method not found: 'Void RainbowMage.OverlayPlugin.OverlayConfigBase.set_GlobalHotkeyType(RainbowMage.OverlayPlugin.GlobalHotkeyType)'.
   at Cactbot.CactbotOverlayConfig..ctor(String name)
   at Cactbot.OverlayAddonMain.CreateOverlayConfigInstance(String name)
   at RainbowMage.OverlayPlugin.ControlPanel.CreateAndRegisterOverlay(IOverlayAddon overlayType, String name) in d:\Personal\OverlayPlugin-Compiler\OverlayPlugin\OverlayPlugin.Core\ControlPanel.cs:line 186
   at RainbowMage.OverlayPlugin.ControlPanel.buttonNewOverlay_Click(Object sender, EventArgs e) in d:\Personal\OverlayPlugin-Compiler\OverlayPlugin\OverlayPlugin.Core\ControlPanel.cs:line 181
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3163.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Advanced Combat Tracker
    Assembly Version: 3.3.2.257
    Win32 Version: 3.3.2.257
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3151.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3160.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
GammaJul.LgLcd
    Assembly Version: 1.1.3.0
    Win32 Version: 1.1.3.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/GammaJul.LgLcd.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
ICSharpCode.SharpZipLib
    Assembly Version: 0.85.5.452
    Win32 Version: 0.85.5.452
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/ICSharpCode.SharpZipLib.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3160.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3160.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3160.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
FFXIV_ACT_Plugin
    Assembly Version: 1.7.0.13
    Win32 Version: 3.3.2.257
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
Machina
    Assembly Version: 2.1.0.1
    Win32 Version: 3.3.2.257
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
Machina.FFXIV
    Assembly Version: 2.1.0.2
    Win32 Version: 3.3.2.257
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
OverlayPlugin
    Assembly Version: 0.3.4.0
    Win32 Version: 3.3.2.257
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
OverlayPlugin.Common
    Assembly Version: 0.3.3.13
    Win32 Version: 0.3.3.13
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/OverlayPlugin.Common.dll
----------------------------------------
OverlayPlugin.Core
    Assembly Version: 0.3.3.13
    Win32 Version: 0.3.3.13
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/OverlayPlugin.Core.dll
----------------------------------------
HtmlRenderer
    Assembly Version: 1.0.1.7
    Win32 Version: 1.0.1.7
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/HtmlRenderer.dll
----------------------------------------
Xilium.CefGlue
    Assembly Version: 3.2272.2035.0
    Win32 Version: 3.2272.2035.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/Xilium.CefGlue.dll
----------------------------------------
CactbotOverlay
    Assembly Version: 0.8.0.0
    Win32 Version: 0.8.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/addons/CactbotOverlay.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.1.19813
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/Newtonsoft.Json.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by eparsyl** [comment]
I did re-install the overlay plugin, and then i re-installed the entire folder of cactbot and then rebooted the pc and still getting the same error.

**Comment by eparsyl** [comment]
I fixed it. I had to delete ALL overlayplugin files (there is 6). So I deleted them, and then downloaded the updated exe file from redit, used that and then re-installed the overlay folder from cactbot (because that updated exe for the plugin came with cactbot 0.7.0)

**Comment by quisquous** [comment]
Nice! Glad you got it sorted.  :)
