### ISSUE TITLE
TEA: Nisi tiggers in german.

### ISSUE THREAD

**Issue by Eddie451** [quisquous/cactbot#832]
During nisi phase, when cactbot tells me to "Take color letter from name" it instead plays in german "Nimm color letter von name"

**Comment by Akurosia** [comment]
Are all other callouts in german for you?

**Comment by Eddie451** [comment]
No, just that one.

**Comment by KattTails** [comment]
This was fixed in #826, it just hasn't made it to a release yet. If you want to use the latest version you can point your raiboss overlay to `https://quisquous.github.io/cactbot/ui/raidboss/raidboss.html` or grab the `ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.js ` from the master repo.

**Comment by Akurosia** [comment]
ahh ok. missread this.
This is already fixed with 46f64fd

but since this fix, no release happend.
So either add the changes made in 46f64fd manually or wait for a new release (alternativly you could use the github version instead of the local version by pointing the url to the online file instead of the local one afaik)

**Comment by Eddie451** [comment]
Alright, thanks!

**Comment by quisquous** [comment]
I'll probably put out a cactbot release this weekend with this in it.
