### ISSUE TITLE
Ultimate Bahamut (UCoB) - Dragon Placement in Nael phase

### ISSUE THREAD

**Issue by Thork8** [quisquous/cactbot#856]
Hey, I've been doing UCoB and noticed cactbot calculates the best positions for A-B-C for all 3 dragon dives at the end of Nael phase.
what i noticed though, the skill "Dragon Favour" does spawn the dragons, but the directions for A-B-C are shown much much later in the fight, during the 2nd Fire Teather. Im the Healer responsible for placing the marks. I wonder if it is intended to show that notification that "late" in the fight instead of right when the Dragons spawn?
I like the feature, but directions are shown for only 12 sec. during a time frame where as a healer i have to deal with Tankbuster, check for fire teather out, check for Doom and check for thunder.
I tried to change the duration from 12sec to a higher number just so i dont have to rush it and kinda take my time for when im not "busy" with mechanics. when i tried to change it to a higher number, i kinda broke it. lol. i didnt had any notification of the directions anymore, so i just put back my backup^^

My question is, is there a way to show the direction for A-B-C when the dragons actually spawn? "Dragon Favour" is the skill that spawns them. OR simply extend the notification duration from 12sec to .. i dont know, even until the dives actually happen. so i dont have to rush them or trying to memorize until im not busy on my role.

if Dragon Favour does not work as a trigger to show that information, maybe a work around would work. something like, well Dragon Favour cast finishes ~8 sec after Nael spawn. maybe say 10sec after Nael spwn = show location for dragon dive markers

thanks for any tipps

**Comment by quisquous** [comment]
Yeah, I think this would be possible.  When I did the original ucob triggers, there was not position information when the dragons were added, so I had to wait for all of the dragons to do an attack so that I could know their positions.  This is why there's a delay.

If you look at the t9 logic, it uses the dragons added combatant logic, because position information existed there when I wrote the t9 triggers.

I think it would be possible to change this, but I've sort of left these triggers as-is to avoid breaking them.  I'll try to take a look when I can.

For what it's worth, the algorithm for the first two is to start north, and rotate clockwise.  If the first two dragons are together, the mark is left of those dragons, if they're apart then it's between them.  Find the third dragon.  If there's a dragon to its left, then the second mark is to the right.  If not, then the second mark is to the left.

**Comment by Thork8** [comment]
Ah okay, now that makes sense, why its shown that late. you first let each dragon attack to locate them.
i totaly think you can leave them as they are, since they work good and as you said, kinda never touch a running system. is there a way to extend the duration this information is shown though? i think this alone would do the trick, because the 12sec we can see the location, is happening during a busy moment in the fight. between each fire,doom,thunder,tankbuster mini phase is somekind of downtime, but by the time i get there the label is already gone, either i have to memorize it or pretty much rush it.

down in the picture is where i tried to just increase the 12 sec duration to a higher value by my own, but after i did that, i didnt got any information nor marker. kinda broke it, lucky had a back up.
its from cactbot>ui>raidboss>data>triggers>unending_coil_ultimate
![Unbenannt](https://user-images.githubusercontent.com/58894366/70967017-4b136680-2095-11ea-895f-3c176d86697e.PNG)

thanks for the hint in the end, i was kinda freestyling it so far. i know they dive 2-1-2 clockwise starting north, but its actually a nice tipp, thank you

**Comment by quisquous** [comment]
I can just change the duration itself.  I think it probably should just stay up for longer anyway.  Would you want it to be 16 seconds? Longer?

**Comment by Thork8** [comment]
if its me i would even let it stay for 20-30 sec, need to check if it crosses other important information, since it will become messy real quick if to many information are shown at the same time.
but 20s +/- would be perfect i think.

if thats done, you can totaly close this issue and i thank you in advance, really good stuff and I (whole community) appreciate your effort.
