### ISSUE TITLE
Radar: Some Hunts are not displayed (maybe DE specific issue)

### ISSUE THREAD

**Issue by Akurosia** [quisquous/cactbot#913]
Language: DE
cacbot version: 0.14.0.0 (self compiled)
Overlayplugin version; 0.12.1.0 (self compiled)

Some Hunts are not displayed in the Radar plugin. 

An example name from an A rank in northern Thanalan: "Letzte Flamme Dalvags"

**Comment by slashy** [comment]
This is indeed a german language specific issue. I made a [pull request](https://github.com/quisquous/cactbot/pull/916/files) for fixing those, however this is just a quick and dirty fix. Since the name for the Hunt mobs are taken from the game files directly with a python script that generates the hunts.js file where the names are found my fix will be overwritten once someone starts that script. 

Now usually parsing stuff from the game files is fine. However since german language is a b*tch, we do have all sorts of special cases for genders and what not. So in the game files "Letzte Flamme Dalvags" is noted as "Letzt[a] Flamme[p] Dalvags" 

Now I already know that [p] stands for plural and adds whatever letter(s) needs to be added to denote the plural version (in case of those names they are usually just removed as there is no plural). 

[a] as in **a**rticle (= Geschlechtswort) for gender based endings: Most of them are "e" (female) or "er" (male) depending on the gender of the name described by it.

There's also [t] which is the **t**itle (= Anrede) used, usually also denoted by the gender of whatever word/name it describes. 

**Example:** Sanu Vali [t] Tanzend[a] Schwinge would be "Sanu Vali die Tanzende Schwinge"

In this case [t] would be "die" because "Schwinge" is female and [a] would be "e" also because of Schwinge being of female origin. 

Now I don't know if the missing letters can be pulles from the game files aswell, which is why I did not modify the python-script generating the hunts.js, but instead opted for altering the actual file even though it says not to. 

I did not look too much into the radar.js, but if those names are used for regular expressions I assume one could come up with regexp-strings for replacement of each of those [*] tags. 

[p] could be removed
[t] would be /d(?>er|ie|as)/
[a] would be /er?/

So "Sanu Vali [t] Tanzend[a] Schwinge" would become "Sanu Vali d(?>er|ie|as) Tanzender? Schwinge" which would indeed match "Sanu Vali die Tanzende Schwinge".

"Letzt[a] Flamme[p] Dalvags" would be "Letzter? Flamme Dalvags" and would also match for "Letzte Flamme Dalvags".

Hope this helps to come up with something better than my pull request.

**Comment by Akurosia** [comment]
[a] can be also `es` (neutral)

**Comment by slashy** [comment]
For items I've seen that yea, but so far not for enemies. Do you have any examples?

It wouldn't change much though. The regex needs to be /e(?>r|s)?/ then. 

I think [a] could also possibly be `en` for plural if that ever shows up for enemies.

**Comment by Akurosia** [comment]
"verhextes Gerippe" e.g. is an enemy where [a] is replaced with `es`
also `en` is not really needed as you each enemy spawns sepperatly so there will be no plural in this case

**Comment by quisquous** [comment]
What's the difference between [A] and [a]?

**Comment by slashy** [comment]
> What's the difference between [A] and [a]?

I haven't seen [A] anywhere in NotoriousMonster so I'm guessing it does not exist there. Not sure where it is in the fisher data. But judging by the replacements in get_fisher_data.py it seems to be similar to what we found for [a].

Just a recap:

**[a] can potentially be `e`, `er`, or `es`** 
It could also be `en`, but that would only apply to plural versions of names.

**[t] can potentially be `der`, `die`, `das`.** 
But the correct word to use here can also be looked up in BNpcName.csv (or Items.csv). The Pronoun field is either 0 (= der), 1 (= die) or 2 (= das). 

**[p] can be removed in all cases, even for plural.** 
For some reason the [p] is also present in ALL plural version of names (items and mobs) that are in the game data. e.g. 

Singular: Letzt[a] Flamme[p] Dalvags
Plural: Letzt[a] Flammen[p] Dalvags

Flammen is already plural, only in this case [a] would be `en` and not `e`. So [p] is completely pointless.
