### ISSUE TITLE
E2S missing Shadowflame Tank callout

### ISSUE THREAD

**Issue by werewolfboy13** [quisquous/cactbot#929]
## Description

The tankbuster in E2S is not being called out even though it is showing as it should. Saw this while playing as a DRK.

## Additional information

![image](https://user-images.githubusercontent.com/43587009/71789908-4b978100-2ff3-11ea-8400-a41e924c05f1.png)

**Comment by werewolfboy13** [comment]
From what I can understand this is the line that should be triggering it:
`00|2020-01-05T18:58:26.0000000-06:00|282b||Voidwalker readies Shadowflame.|25e06c510ac48024064d0967f659c766`

this is in the e2s.js
` id: 'E2S Shadowflame Tank',`
`      regex: / 14:3E6[12]:Voidwalker starts using Shadowflame on (\y{Name})/,`
`      regexCn: / 14:3E6[12]:虚无行者 starts using 暗影炎 on (\y{Name})/,`
`      regexDe: / 14:3E6[12]:Nichtswandler starts using Schattenflamme on (\y{Name})/,`
`      regexFr: / 14:3E6[12]:Marcheuse Du Néant starts using Flamme D'[oO]mbre on (\y{Name})/,`
`      regexJa: / 14:3E6[12]:ヴォイドウォーカー starts using シャドーフレイム on (\y{Name})/,`
`      regexKo: / 14:3E6[12]:보이드워커 starts using 그림자 불꽃 on (\y{Name})/,`
`      condition: function(data, matches) {`
`        return data.me == matches[1];`

might need to be fixed. I would do it myself but I don't know how to do it.

**Comment by ngld** [comment]
For future reference: We debugged the issue further on Discord and ended up with the following conclusion:
The trigger doesn't fire because the condition fails. `data.me` is `Interesting-player Name` and `matches[1]` is `Interesting-Player Name`. The check fails due to the different capitalization.
`Interesting-player Name` is actually the correct name (which also appears in the raw (`|`) log lines) but all trigger (`:`) log lines contain the incorrect name `Interesting-Player Name`.

The name mangling happens in `FFXIV_ACT_Plugin.Common.StringHelper.ToProperCase(string)`. To fix the issue, this trigger (and all other name based triggers) either have to make the string comparison case-insensitive (i.e. `data.me.toLowerCase() == matches[1].toLowerCase()`) or change the source of either value. Matching against the network log or mangling the name in `data.me` using the same method would fix the issue.

**Comment by werewolfboy13** [comment]
So when we did the `cactbot/ui/raidboss/popup-text.js` file changes it fixed the tankbuster callouts but broke other callouts in the process.

**Comment by werewolfboy13** [comment]
im going to try fixes and see if they work

**Comment by werewolfboy13** [comment]
It didn't work. Unfortunately I don't understand how it works so well yet.

**Comment by quisquous** [comment]
[cactbot-release.zip](https://github.com/quisquous/cactbot/files/4049817/cactbot-release.zip)

Here's a build of the latest version of cactbot that includes the plugin being updated to send a different name.  Make a copy of the changes you made locally somewhere else (just in case), and then update everything with this new release and see if things work ok for you.

**Comment by werewolfboy13** [comment]
Issue is fixed with FFXIV ACT plugin version 2.0.4.16,
