### ISSUE TITLE
UCOB thunder call out not working

### ISSUE THREAD

**Issue by healrsadjust** [quisquous/cactbot#966]
UCOB thunder call out not working any more after update

**Comment by healrsadjust** [comment]
![Capture](https://user-images.githubusercontent.com/49485302/72308450-7b3e2d00-3674-11ea-8a78-cd0d60746e4b.PNG)
to clarify this is what isnt working

**Comment by healrsadjust** [comment]
And second fire out is always wrong.  It keep saying fire out go with.  Doesnt matter if you have fire or ice stack.  It will always say go with.  Both issues only after updating overlayplugin and latest cactbot

**Comment by quisquous** [comment]
Do you have a hyphen in your name?

**Comment by healrsadjust** [comment]
No hyphen in my name

**Comment by healrsadjust** [comment]
Everything else in ucob is working fine

**Comment by quisquous** [comment]
Sorry for the weird question, but there's been some capitalization issues (which is why there's a note on the latest release).

Glad everything else seems to be working ok.  I took a quick look and didn't see anything obvious.  I'll take a closer look when I get a chance.  You should be able to revert to the previous version of `ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.js`.  If the issue is related to trigger updates since the last version, then reverting will fix these issues.  If it's something else, then that'd be good to know.

**Comment by healrsadjust** [comment]
Sorry how do i revert back to test? 
I will be going into ucob tomorrow again

**Comment by quisquous** [comment]
Grab that file from the 0.14.1 release, and copy it over the top of your current file.

**Comment by healrsadjust** [comment]
Ahh right ok i will try that out and get back to you

**Comment by healrsadjust** [comment]
Hi quisquous
As you suggested i replaced 0.14.1 ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.js
file into my cactbot folder.  It 100% fixed the issue :)
Do i require to do this every future cactbot update?

**Comment by quisquous** [comment]
No, I will figure out what the issue is and I will fix it.  Thanks for the report and confirmation about what's gone wrong.  I should fix this before the next cactbot release.  If I don't, I'll comment here and let you know.
