### ISSUE TITLE
UCOB Octet twintania marker broken

### ISSUE THREAD

**Issue by KanadeT** [quisquous/cactbot#972]
I was going to post about the thunder / fire issue but someone else did,

I also noticed that the marker callout for Twintania's dive on Grand octet wasn't showing who it was targeted on. I don't know if this is an issue was to do with peoples names like you spoke about before, but I believe no ones name was with a hyphen. I

Not sure what other info you would need, sorry.

**Comment by quisquous** [comment]
I ran this through the emulator with the latest changes, and everything looked ok to me in terms of those callouts.

I think the issue is that the ability for the tower hitting which was used to figure out all the party members wasn't working properly, and so 72358c502 will have fixed this.

I'll release a new version today with these changes.  Thanks for the report, and sorry for the bugs.
